### ISSUE TITLE
is iter.linkstats.txt used anywhere, e.g. for warmstart? 

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1028]
if not , don't write it out anymore

**Comment by mr-asif-nor** [comment]
We are using this file here for the warmstart as in the attached image. So it means we should still be writing this file.

![image](https://user-images.githubusercontent.com/28714283/49949836-74e0fd00-ff18-11e8-8e9f-70c14eaded69.png)

**Comment by mr-asif-nor** [comment]
I have updated the config files to have the default linkstats module config to eliminate the linkstats.txt.gz generation.
