### ISSUE TITLE
iter.linkstats.csv: it seems to be producing a lot of redundant data

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1029]
is everything really needed for warmstart???

**Comment by wrashid** [comment]
only average travel time is really read by warmstart

**Comment by wrashid** [comment]
don't write when volume=0

**Comment by mr-asif-nor** [comment]
This writing of the linkstats.csv.gz file is done inside BeamCalcLinkStats file, which is in a jar. So should extend it and use the child class to change the logic for checking volume to be 0 to not write it.

**Comment by carloscaldas** [comment]
Not needed anymore
