### ISSUE TITLE
why are start and end coords of car path traversal changing over the iterations?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1032]
-> reproducible on sflight 10k probably even lower and maybe even beam level

**Comment by rajnikantsh** [comment]
@wrashid I have checked around 60-70 start end Coords corresponding to their links in multiple iterations with sf-light-5k and found that the coordinates are seems to be unchanged   with their respective links. Like
![Screenshot from 2019-01-04 00-24-45.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b59e2a42c7a8600132d4e2c/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f37a3dd5b768ef1236535b424aa953444d04bea6d37ef5f22e7a985959e9d7685a77c03947f8b1d319bf01bb728b1dd0b1bb825edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cf04ee54c5ca1173465ee647b.png)
