### ISSUE TITLE
fields in events are randomly ordered in XML output

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1035]
make them appear in a reasonable order

ask colin for more info on this

**Comment by bhavyalatha26** [comment]
@colinsheppard made changes to the preserve the insertion order of attributes for all events while writing to csv.
PFA the events and their attr ordering for events written to the xml file.
[events-order.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9912bc64efd30015c031a0/125516c66e82c728ace21e0d46ed829f2d9690e480fbbb46b61fbcd6395428792c07b7692ac7b62aeb142e545c594afa15510e42fcf98879a6e469778d5419f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3b88f4ec7ef3c22e38e8b4d2c53.txt)
