### ISSUE TITLE
why is car share in iteration 0 lower than in later iteraitons

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1043]
despite iteration 0 freeflow????

**Comment by rajnikantsh** [comment]
I have ran the sf-light-5k for 30 iterations and the issue i.e car car share in iteration 0 lower than in later iteraitons still coming .
![averageCarTravelTimes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b59e2a42c7a8600132d4e2c/125516c66e82c728ace21e0d46e9829f318384acace8ad77b65ce69125722e7e2c17e1673295f127b54778154d555ca9135c5941f9fa8f2ff0e235218c5c0bec836d0d21c13a19bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8b49381f04108ffa5c3ca68b06.png)

**Comment by wrashid** [comment]
this is average travel time, please share car share

**Comment by rajnikantsh** [comment]
car share in modechoice for 30 iters with sf-light(5k)
![modeChoice.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b59e2a42c7a8600132d4e2c/125516c66e82c728ace21e0d46e59b9e26a18ba686eaba01e81fe086264c22703d46f9692587b77eea1728575b091aa5105e5f44fdab8979f3b13b78984019af80330b2b9b645bf9fa9015ad00b22a8a4a81b0b4834cc9e93e22ee8b9d02.png)

**Comment by wrashid** [comment]
why is mode share of car lower in iteration 0 than later iterations, despite car travel travel time being low in iteration 0 and much higher in later iterations?

**Comment by wrashid** [comment]
sill relevant?

**Comment by carloscaldas** [comment]
Not relevant anymore. Example below
![image](https://user-images.githubusercontent.com/12264098/60035736-73ea0e80-96a5-11e9-8e86-fcd3d3e977af.png)
