### ISSUE TITLE
Update RideHailWaitingStats

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1079]
See class WaitingStatsComputation.

* There should not be a hard coded "numberOfBins" instead we should use the parameter beam.agentsim.timeBinSize and keep collecting the stats until all events are processed.

* getCategories should have one more bin at 2 minutes

* we need to create a separate output that summarizes the data slightly differently. Take the existing file "0.rideHailWaitingStats.csv" and rename it to "0.rideHailWaitingHistogram.csv" and then use the original name for this new output file.

* collect the waiting stats by time bin (timeBinSize) and by TAZ. So if timeBinSize is 3600 then the it would be hourly aggregations. Put the waiting stats into a collection then during writeCSV step we calculate the average, the median, and the length of the data and write those as separate columns along with the time bin and the TAZ, e.g.:

timeBin,TAZ,avgWait,medianWait,numberOfPickups,avgPoolingDelay,numberOfPooledPickups

* finally, for now you can just set the "pooling" statistics to 0, but put the columns in there as we will soon add those stats in a different Task

**Comment by bhavyalatha26** [comment]
@colinsheppard 
Regd "getCategories should have one more bin at 2 minutes"
Can you please tell me the units of the current category bounds being used inside this function . 
I assume it to be minutes. Can you please confirm

**Comment by colinsheppard** [comment]
@bhavyalatha26 those are in minutes

**Comment by bhavyalatha26** [comment]
@colinsheppard , I have few more questions  :
 
1. Generated and wrote the new stats(RideHailWaitingAnalysisTaz.scala) to a csv file . Do we also need to generate a graph for the new stats ?

2. Replaced ModeChoiceEvent -> ReserveRideHailEvent ,as mentioned in the description for the new stats class ( named it as RideHailWaitingAnalysisTaz.scala) as well the existing stats class(RideHailWaitingAnalysis.scala). Just to confirm , are the changes required for the existing stats (RideHailWaitingAnalysis.scala) , or was it meant to be done only for the new stats?

3. A similar stats called RideHailingWaitingSingleAnalysis.scala exists . Do we need to make the changes (mentioned in #1079 description) to this class as well , or just ignore this stats class ?

**Comment by colinsheppard** [comment]
1. No graph is necessary.

2. For both existing and new.

3. See response from @wrashid on Glip.

**Comment by bhavyalatha26** [comment]
Merged RideHailingWaitingSingleAnalysis into RideHailingWaitingAnalysis.
