### ISSUE TITLE
beam.physsim.quick_fix_minCarSpeedInMetersPerSecond still needed or is this fixed?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1098]

**Comment by wrashid** [comment]
-> start 25k if not, try 400k

**Comment by rajnikantsh** [comment]
I have checked it by debug pointer and found that we are getting travelSpeed(like 0.2) less then quick_fix_minCarSpeedInMetersPerSecond(Set to 0.5 value in conf)  .
