### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1105]
ReplanningExpBetaModeChoiceSpec -- increase test scores over iterations 

This test started failing, should be able to get it back to green by looking into the run in more detail... e.g. was it in warm start mode? Are the choice params set to something strange? Flow/capacity factors?

**Comment by wrashid** [comment]
why worst average score  going down till 20th(+?) iteration

**Comment by JustinPihony** [comment]
Is there a branch this is failing on more specifically? When I run it through master locally it works for me.

**Comment by JustinPihony** [comment]
(Side note) Would there be resource conflicts to run that test in parallel?

**Comment by bhavyalatha26** [comment]
@JustinPihony its failing on **bl/#1079-update-ride-hail-waiting-stats-4ci**

**Comment by JustinPihony** [comment]
I still saw no failures - https://beam-ci.tk/job/beam-4ci/3258/consoleFull
