### ISSUE TITLE
Error logs in R5RoutingWorker are not written to log file

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1139]
![image](https://user-images.githubusercontent.com/5107562/50984478-98f22700-1534-11e9-8145-d6fc58e3ff78.png)

**Comment by JustinPihony** [comment]
Is this only when running in cluster mode, or anytime? The biggest difference I can see is that R5RoutingWorker creates the logger itself, but that should only be in cluster mode (that should probably be moved into BeamHelper.runClusterWorkerUsing though...?).

**Comment by REASY** [comment]
Thank you, @JustinPihony, it helped!

**Comment by colinsheppard** [comment]
It is only set that way to avoid duplicate logging to console. But in this case it shouldn't have been set.
