### ISSUE TITLE
FuelUsageGraph Test Off by Tiny Amount

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1164]
This test is pretty hard for me to follow what data is coming from where, but it's failing for me due to two fuel consumption numbers off by a very small amount:

Map("bus" -> 4.926656162325561E12, "rideHail" -> 1.4517825809733E10, "walk" -> 8.751, "car" -> 2.3345351543992E10, "subway" -> 0.0) did not equal 
Map("bus" -> 4.926656162325224E12, "rideHail" -> 1.4517825809733E10, "walk" -> 8.751, "car" -> 2.3345351543992E10, "subway" -> 0.0)

I'm also a bit concerned because in the near future our energy consumption model may no longer be deterministic, so this kind of *exact* testing of outcome may no longer be possible.

For now, can you please fix, it has been marked ignored in my branch that will soon be merged into master.

**Comment by bhavyalatha26** [comment]
Hi @colinsheppard I ran the test spec FuelUsageGraphTest on master and all tests passed. Also I do not see the above map based assertions in the specs . Should I look into some particular branch ?
