### ISSUE TITLE
ParkingStats Task 2

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1165]
Thanks for your first effort on parking stats, I fixed a couple of small things but otherwise it looks good to me.

First, please make the new stats collector extend OutputDataDescription and implement data descriptions.

Now we need to calculate inboundParkingOverheadTime and inboundParkingOverheadCost

*inboundParkingOverheadTime*

Let's keep this simple and measure it as the time to walk from the car to the destination. 

So this means you just have to monitor (for the same person being tracked for the outbound metric) for the ParkEvent and note the time. Then monitor for the next PathTraversal that has the same person as "driver". Then note the arrivalTime of that path traversal and the difference between that and the park event time is the inboundParkingOverheadTime.

*inboundParkingOverheadCost*

Inside the same ParkEvent that you caught above you'll find a field "ATTRIBUTE_COST" that is the inboundParkingOverheadCost.

Thanks.

**Comment by bhavyalatha26** [comment]
Hi @colinsheppard , with inbound overhead case , we have three locations :
- ParkEvent.parkingTAZ
- PathTraversal.start
- PathTraversal.end

Which one should we pick while processing the end stats ( stats grouping by TAZ and bin) . And in the path traversal
