### ISSUE TITLE
DRIVE_TRANSIT can miss the bus

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#1175]
The agent ends up in the state below and acts accordingly, but, as the comment indicates, this probably shouldn't happen except when ride hailing, as the agent has full knowledge of all the travel times involved.

I think some little auxiliary travel time, like walking or parking, may be missing from the agent's reasoning, so the agent is late for the bus...

```
    // TRANSIT but too late
    case Event(StateTimeout, data @ BasePersonData(_, _, nextLeg :: _, _, _, _, _, _, _, _))
        if nextLeg.beamLeg.startTime < _currentTick.get =>
      // We've missed the bus. This occurs when the actual ride hail trip takes much longer than planned (based on the
      // initial inquiry). So we replan but change tour mode to WALK_TRANSIT since we've already done our ride hail portion.
      ExponentialLazyLogging.logger.warn(
        "Missed transit pickup during a ride_hail_transit trip, late by {} sec",
        _currentTick.get - nextLeg.beamLeg.startTime
      )
```

**Comment by michaz** [comment]
Or do we have some randomized parking search time already? Then this makes sense, of course.

**Comment by colinsheppard** [comment]
Correct, parking overhead time is not known at the beginning of the trip.

**Comment by michaz** [comment]
(Will change the comments then, to indicate that this is a quite normal thing to happen. Perhaps even downgrade log-level for this event from warn to debug?)
