### ISSUE TITLE
look for copy paste code

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1231]

**Comment by bhavyalatha26** [comment]
We need to find out, if there is any copy pasted code in our repository
and pin point classes which have copy pasted code 
and from where

**Comment by bhavyalatha26** [comment]
https://github.com/aaschmid/gradle-cpd-plugin
Works for java / scala

**Comment by JustinPihony** [comment]
I'm curious - was this meant to be closed? I didn't see the CPD plugin added, so figured it was closed by accident?
