### ISSUE TITLE
discuss: add default ridehail vehicle type in vehicle types?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1236]
-> this would be useful for the cacc to find out, what value to use for ridehail vehicles

**Comment by michaz** [comment]
On the other hand: https://github.com/LBNL-UCB-STI/beam/issues/1203

**Comment by michaz** [comment]
I would, in ``RideHailManager``, remove the fallback to the "default" (== non-existent in the map) car vehicle type, here:

```
    val ridehailBeamVehicleType = beamServices.vehicleTypes
      .getOrElse(ridehailBeamVehicleTypeId, BeamVehicleType.defaultCarBeamVehicleType)
```

In consequence, the configured vehicle type for ride-hailing will have to be a regular vehicle type, in the regular vehicle type file.

In consequence, the physsim (and anyone else) will be able to look up that vehicle type in the vehicle type map and use it.

**Comment by colinsheppard** [comment]
I agree with Michael.
