### ISSUE TITLE
discuss: modechoice/replanning long repetition series - fix needed?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1237]
reproduce easily: high intercept for walk_transit, but have no transit capacity.

=> should replanning have memory to avoid repetitions?

**Comment by michaz** [comment]
(Or is this not related to the duplicate link IDs and I made that up? :-) )

**Comment by wrashid** [comment]
link ids repetition and this issue seem to be separate. the patch is not completed yet - that was more debugging

**Comment by michaz** [comment]
Okay thanks, got you.

So what do we think would be behaviorally correct? I see an overcrowded bus. I wait for the next one, but not for much longer.

Something like a probability to wait for the nth bus that decreases with n?

**Comment by wrashid** [comment]
I would be fine with any of the following behaviors which is easy to implement to avoid the loop, e.g. take a different mode if unsuccessful with a mode or take bus occupancy into consideration during choice from the beginning or probability based waiting approach as suggested above or something else. At the moment it can get stuck in a loop where it selects walk transit over and over again (there is no info available to agent that buses are full at this time of the day).

**Comment by sfwatergit** [comment]
If I were in such a situation, I'd probably check once in a while to see if ridehail were a better option. As a learning behavior, I'd probably avoid taking such a full bus again... some PersonAgents might not have that luxury, in which case, they'd better hope that when urbansim hooks up w/ BEAM future years will bring enough development/growth in income that they won't have to walk 20 miles to work every day 😬

**Comment by michaz** [comment]
> I'd probably check once in a while to see if ridehail were a better option

I think they're doing that, they are just deciding with never-diminishing optimism that the next non-overcrowded bus will come any time now, so ridehail fails to appear as the better option.

Sounds like "keep replanning, but add a rising penalty to PT for every time I've seen an overcrowded bus" to me..

**Comment by michaz** [comment]
(Or aren't they? Ahhh, maybe they stay locked on the PT mode once they decided....)

**Comment by sfwatergit** [comment]
Chooses mode (line 338):
 ` // We use our car if we are not replanning, otherwise we end up doing a walk transit (catch-all below)
              // we do not send parking inquiry here, instead we wait for drive_transit route to come back and we use
              // actual location of transit station`

**Comment by colinsheppard** [comment]
I've temporarily averted this issue with a hard cap on number of replanning attempts per trip. For now it's set to 2 attempts and then sent straight to WALK. 

But this is one that we should solve more robustly in the future. I like the idea of penalizing the failed mode in the next choice. ~$1 per failure should do it.
