### ISSUE TITLE
debug: same link id repeated 10s of times in pathTraversal

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1239]
-> especially at end of simulation

**Comment by michaz** [comment]
Wait, are we going to patch those duplicated link ids out of the simulation result? I noticed this some time ago already and asked about it in the chat..

I think if we do this we will forget about it and never find out what's happening, because it won't look broken anymore.

**Comment by colinsheppard** [comment]
Totally agree with @michaz. Please revert commit 747dc1a and instead look into the source of the problem.

**Comment by wrashid** [comment]
as mentioned on other chat, asif what just debugging on the branch and this was not a patch

**Comment by wrashid** [comment]
@rajnikantsh confirmed last week, that the linkId duplications are already present in R5RoutingWorker (e.g. buildStreetPath). Is this related to #1262 @michaz?

**Comment by michaz** [comment]
Right now, I rather suspect that it.0 is correct, but the experienced plans are wrong -- something about how we move from driving to walking corrupts the experienced plans. Then in it.1, agent _start_ with bad plans with duplicated link ids, and execute them. (Not completely tested, but my current hypothesis.)

**Comment by michaz** [comment]
Or, @rajnikantsh, did you catch R5RoutingWorker produce routes with duplicated links in iteration 0, in regular route requests (not EmbodyWithCurrentTravelTime)?

**Comment by rajnikantsh** [comment]
Hi @michaz, I have verified it and found that duplicate links ids are not coming in iteration 0 but this is happening in later iterations in later hours.

**Comment by michaz** [comment]
Thanks!

**Comment by wrashid** [comment]
@rajnikantsh can you please confirm, in which scenario you are still seeing the repeated links in later iterations?

**Comment by rajnikantsh** [comment]
@wrashid I have checked the repeated links in few sf-light scenarios by taking latest pull of master and found that we are now getting repeated kinks in iteration 0 also. Here I am sharing the result with 2 iteration runs of few sf-light scenarios.
![repeated-linkids](https://user-images.githubusercontent.com/5759657/52803299-ce47e280-30a7-11e9-977f-f67aa9676922.png)

**Comment by wrashid** [comment]
just ran 15k sioux faux (competition) with beam-master, it still gives car travel time spike at the end of the day: 

![15k-sioux-falls](https://user-images.githubusercontent.com/13569531/52833354-f7657480-30a1-11e9-9514-7f7adf557967.PNG)

also easy to spot long sequences of repeated links: 

![links-repetition](https://user-images.githubusercontent.com/13569531/52833370-03e9cd00-30a2-11e9-8fcb-807afb34abc7.PNG)

**Comment by michaz** [comment]
Ok, then we've had two similar problems all along..

**Comment by wrashid** [comment]
also able to reproduce issue on 1k sioux faux (competition): 

![image](https://user-images.githubusercontent.com/13569531/52870305-2a911d80-310d-11e9-89b4-7dcddd94fc2c.png)

example pathTraversal event: 
![image](https://user-images.githubusercontent.com/13569531/52870405-66c47e00-310d-11e9-9c4b-faba85604ffa.png)

**Comment by wrashid** [comment]
another example from sioux faux 1k (confirming that the repeating sequence is not always at the end): 

![image](https://user-images.githubusercontent.com/13569531/52870708-113ca100-310e-11e9-91f1-e48fd3b3dab8.png)

**Comment by wrashid** [comment]
the issue happens already in iteration 0 (and is also present later)

**Comment by wrashid** [comment]
probably found the issue: sioux faux warmstart-plans were created before the recent fixes - confirmed that without the old/bad warmstart-plans no travel time spike on beam-master
