### ISSUE TITLE
Easier VOTT Modifications

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1247]
add parameters to config file to allow control of VOTT modulation

use the multipliers inside MNL Choice calc.

**Comment by colinsheppard** [comment]
Can we create a somewhat general purpose method on AttributesOfIndividual, call it getVot and then we pass that method whatever context we have, e.g.:

* is this travel or activity?
* if travel, what mode
* if mode is driving, what link and link conditions
* etc....

We then call a single method throughout the code-base for grabbing VOT but we can pass different data to it as contexts.

As you enable this, add in Activity as one of the contexts, then we can vary VOT depending on activity type, (e.g. work is more valuable than home)

**Comment by zneedell** [comment]
Sure! That makes sense and seems like a good way to do it.
