### ISSUE TITLE
remove unused config param

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1249]
beam.routing.r5.osmFile 

is not used anywhere, please remove

**Comment by colinsheppard** [comment]
also:

beam.agentsim.tuning.fuelCapacityInJoules 

Actually, please go through BeamConfig and test out each param and if it's not used in codebase anywhere please remove.

**Comment by bhavyalatha26** [comment]
@colinsheppard I could not find the above two params in the config . However I listed out all unused params from the beam-template.conf . Please review the list once and let me know which can be removed . Thanks.

[BEAM-unused-configs.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9912bc64efd30015c031a0/125516c66e82c728ace21e0d46cab1bb0ecf96a79afaba47e95eff9a2f4f20606b48e13b628ae92dbc56395b4d5a1ca8475d5a47fafddf7fafe73a708a5d59ed83385873ce2f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e3828a4b391d001d80fd5427ed.txt)

**Comment by JustinPihony** [comment]
@bhavyalatha26 - beam.routing.r5.osmFile is in many of the files, and starts in the template here - https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/resources/beam-template.conf#L389

**Comment by bhavyalatha26** [comment]
aah thanks @JustinPihony ! I missed searching in the sub objects , may have to review my submitted list of keys as well for the same .

**Comment by colinsheppard** [comment]
@bhavyalatha26 I just started from the top and the first several params in your list are all used in the code. These are definitely not unused, which makes me think that your technique for assessing if a param is used or not is inaccurate.

If you go into BeamConfig class and Command-Click on the name of each parameter (inside the case class where each is defined), IDEA tells you immediately if it's used anywhere outside of the BeamConfig class. 

Please do this for all parameters again.

**Comment by bhavyalatha26** [comment]
Hi @colinsheppard , 
Please review the new list
[BEAM-unused-configs.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9912bc64efd30015c031a0/125516c66e82c728ace21e0d46cab1bb0ecf96a79afaba47e95eff9a2f4f20606b48e13b628ae92dbc56395b4d5a1ca8475d5a47fafddf7fafe73a708a5d59ed83385873ce2f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e382864a371f061888fd5427ed.txt)

Also I have one question regarding the config keys 
If a particular beam config key is no where used in the source code class files but is externally referenced in matsim.conf , should we still retain the config key as it is a matsim related configuration ?

 Eg : matsim.modules.households.inputHouseholdAttributesFile is no where used in class files but is referenced in matsim.conf as 
households {
    inputHouseholdAttributesFile = ${beam.agentsim.agents.households.inputHouseholdAttributesFile}
  }
