### ISSUE TITLE
add mapping from vehicleId to vehicleTypes in beamservices

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1252]
when creating a BeamVehicle, add a mapping from vehicleId to vehicleType

=> e.g. useful for finding out, if vehicle is cacc enabled for physsim simulation

**Comment by bhavyalatha26** [comment]
Hi @wrashid before i proceed , I have a question.

There is already a map named "privateVehicles" that maps from 
beamvehicleId -> beamvehicle obj

Can not we make use of beamvehicle.beamVehicleType to achieve the same result for a given vehicleId?

**Comment by wrashid** [comment]
this new mapping would be for all vehicles (not only private vehicles), e.g. including buses, ride hail

**Comment by bhavyalatha26** [comment]
ok

**Comment by michaz** [comment]
Hmmm, I'm actually just _de_centralizing these things, trying to get rid of global maps of things. That just finally worked with vehicles.

Can't we instead just put the vehicle type id into the relevant events, in addition to the vehicle id?

**Comment by michaz** [comment]
Look: ``PathTraversalEvent`` already has the vehicle type id. So the vehicle type is already known to any event handler.

**Comment by wrashid** [comment]
thanks for the feedback Michael. Wasn't aware that vehicle type was available as a field on pathTraversal now. That is sufficient for our needs.

**Comment by wrashid** [comment]
@bhavyalatha26 I am closing this issue

**Comment by bhavyalatha26** [comment]
ok @wrashid
