### ISSUE TITLE
Update Step-by-Step Guide

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1271]
I recently updated the "Getting Started" guide in our docs, but it's clear it needs to be updated more. 

In particular, we should move instructions on setting up git LFS to the getting started guide. 

Please begin from this branch (which will be merged to master soon):

cs/bsd-release

Then please use a virtual machine or some other computer you have access to, to actually walk through the process of installing all relevant software (including IDEA) in order to add as much detail as possible to the guide so that people totally new to using IDEA and running BEAM don't experience any issues. 

Then add to the guide under 

docs/users.rst

Note that the LFS config explanation is in:

docs/developers.rst

**Comment by colinsheppard** [comment]
Also, when describing how to configure git LFS, add this caveat for windows users:

With Git LFS windows installation, it is common to have the wrong version of git-lfs installed, because in these latest git client version on windows, git lfs comes packaged with the git client. 

When installing the git client one needs to uncheck git lfs installation. If mistakenly you installed git lfs with the git client, the following steps are needed to correct it (uninstalling git lfs and installing the required version does not work...): 

* Uninstall git
* Install the git client (uncheck lfs installation)
* Install git lfs version 2.3.4 separately

**Comment by bhavyalatha26** [comment]
@colinsheppard added the required details . Please review the PR https://github.com/LBNL-UCB-STI/beam/pull/1288

Also attached a PDF view of the changed doc file for quick reference.

[new-users-doc.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9912bc64efd30015c031a0/125516c66e82c728ace21e0d46e6918d6e9790ac9dfaf247ab5eb2d86b56357c2301a03f32dfa17dbd162d545a5c48a8170c5615faf9892af4b66e258d5b03ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b98f4cc2ec3522e68b8d48360c48.pdf)
