### ISSUE TITLE
how can someone fork BEAM?

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1274]
Can we look into how one would go about forking the BEAM repo and still have access to all the git LFS data?

E.g. if someone wanted to set up their own LFS server and maintain a fork, can this be done?

Alternatively, can someone fork but still connect to and make use of our LFS server (assuming we given them write privileges)?

**Comment by colinsheppard** [comment]
Update, some very helpful notes from Alvaro on how to do this:

# Instructions for forking BEAM
These instructions are based on [this page].(https://confluence.atlassian.com/bitbucket/current-limitations-for-git-lfs-with-bitbucket-828781638.html)

 1. List item
```
git clone https://github.com/LBNL-UCB-STI/beam
```

When asked for username and password for LFS server (http://52.15.173.229:8080) enter anything but do not leave them blank.

2. Fetch Git LFS files
```
git lfs fetch origin
```
Many tutorials on cloning Git LFS repos say one should use 
```
git lfs fetch --all origin
```
However, in BEAM this represents over 15 GB data and often fails.

3. Add new origin
```
git remote add new-origin <URL to new repo>

```

4. Add push URL for new LFS repo in .lfsconfig
```
[lfs]
  url = http://52.15.173.229:8080/LBNL-UCB-STI/beam.git

  pushurl = <URL to new LFS repo>
```

5. Push to new repo
```
git push new-origin --all 
```

Note: as of this writing, the repo has around 200 MB LFS data. However, the push fails if the LFS server sets a low limit on LFS data. For example, it fails for Bitbucket free which sets a limit of 1 GB LFS data. 

6. Update .lfsconfig to have only the new LFS repo
```
[lfs]
	url = <URL to new LFS repo>
```

7. Push to new repo again
```
git push new-origin --all 
```

8. Update remotes
```
git remote set-url origin <URL to new repo>
git remote set-url --push origin <URL to new repo>
```

9. Verify that everything worked by cloning the new repo
```
git clone <URL to new repo> beam-fork
```
Note: cloning might take a few minutes since the repo is quite large.

If everything turned out well, the cloning process should not ask for the credentials for BEAM's LFS server (http://52.15.173.229:8080).

**Comment by colinsheppard** [comment]
@bhavyalatha26 please add this to developer docs

**Comment by JustinPihony** [comment]
Why was #1503 dropped? Is this no longer an issue and can be closed?
