### ISSUE TITLE
Create Test: Car and Bus PathTraversalEvents must contain road linkIds

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#128]
It has been observed that PathTraversalEvents which are passed from the AgengtSim to the PhysSim contain non-road linkIds for car and bus routes, even for the beamville scenario. We need to create a test, which captures this bug. When this test is enabled (pushed to application/master branch), the warning logging of 'numberOfLinksRemovedFromRouteAsNonCarModeLinks' can be removed in AgentSimToPhysSimPlanConverter (which serves as a reminder instead of the failing test currently).

**Comment by fdariasm** [comment]
@wrashid, is this still relevant?
