### ISSUE TITLE
add documentation for lfs installation to avoid and correct issues

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1280]
In these latest git client version on windows, git lfs comes packaged with the git client. When installing the git client one needs to uncheck git lfs installation.

If mistakenly someone installed git lfs with the git client, following steps are needed to correct it (uninstalling git lfs and installing required version does not work...): 
1. Uninstalled git
2. Installed the git client (uncheck lfs installation)
3. Install the git lfs version 2.3.4

**Comment by colinsheppard** [comment]
Redundant with #1271
