### ISSUE TITLE
SingleModeSpec runs very slow

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1284]
On my machine master branch (28bd60084b024547ac98b76870aabf61429ae1c7) takes:
```
23:24:06.706 [single-mode-test-akka.actor.default-dispatcher-48] INFO  b.a.scheduler.BeamAgentScheduler - Stopping BeamAgentScheduler @ tick 108004. Iteration 0 executed in 1451 seconds
```
It seems that `BeamService` mock makes it slow. It happens because Mockito needs to track the call to the method and for that it should allocate StackTraceElement(???) (and it looks like there is memory leak somewhere there) and simulation starts spending a lot of time in GC:
![image](https://user-images.githubusercontent.com/5107562/52814835-b5532780-30cf-11e9-923f-01735df1d271.png)
![image](https://user-images.githubusercontent.com/5107562/52814899-d4ea5000-30cf-11e9-8fff-e5a9423ad70d.png)

**Comment by michaz** [comment]
Oh. Yes, totally possible. Part of task "make things more testable by not having them rely on global-variable-like things you have to mock".

**Comment by REASY** [comment]
Closed by https://github.com/LBNL-UCB-STI/beam/pull/1285
