### ISSUE TITLE
Create tests for testing sensitivity misc. paramters

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#129]
Create tests for testing sensitivity of following parameters:

beam.agentsim.agents.rideHailing.defaultCostPerMile
beam.agentsim.agents.rideHailing.defaultCostPerMinute
beam.agentsim.tuning.transitCapacity
beam.agentsim.tuning.transitPrice
beam.agentsim.tuning.tollPrice
beam.agentsim.tuning.rideHailPrice

**Comment by carloscaldas** [comment]
No needed anymore
