### ISSUE TITLE
fix bug: why certain iterations have "mode crash"?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1291]

**Comment by wrashid** [comment]
Why mode crashes and scores spike?
![image](https://user-images.githubusercontent.com/13569531/52895457-db88ce00-3188-11e9-9315-ed6603d2d132.png)


![image](https://user-images.githubusercontent.com/13569531/52895462-e4799f80-3188-11e9-95b0-d122b6356de9.png)

**Comment by wrashid** [comment]
when one compares at the first spiking iteration (it 6), to a normal iteration, one finds the following:

![image](https://user-images.githubusercontent.com/13569531/52895478-1ab71f00-3189-11e9-99b5-d2dce0c2fa6d.png)


![image](https://user-images.githubusercontent.com/13569531/52895480-20ad0000-3189-11e9-8568-63d6125cdc52.png)

**Comment by wrashid** [comment]
also ridehail:

![image](https://user-images.githubusercontent.com/13569531/52895497-594cd980-3189-11e9-87e1-5ccd8f4b3382.png)


![image](https://user-images.githubusercontent.com/13569531/52895499-5ce06080-3189-11e9-9cd4-88f8b08be606.png)

**Comment by wrashid** [comment]
mode choice it 5 vs 6: 

http://localhost:8001/BeamCompetitions/output/sioux_faux/sioux_faux-15k__2019-02-16_04-45-40/ITERS/it.5/5.modeChoice.png

![image](https://user-images.githubusercontent.com/13569531/52895509-90bb8600-3189-11e9-818a-fb9d008e33c3.png)

**Comment by wrashid** [comment]
Hint for further debugging 1: if also looking at other stas, somehow all stats stop at hour 17 of the day.

**Comment by colinsheppard** [comment]
Really strange, like the whole agentsim crashed and and actor system shut down... the score spike would make sense since our score is all dis-utility so there's less of it if people don't finish their day.

**Comment by wrashid** [comment]
those iterations have exception in event handler, therefore all stats stop at hour 17

**Comment by wrashid** [comment]
will need to enable detailed error logging and run it again to potentially uncover more details (what is causing the crash)

**Comment by REASY** [comment]
If we set logger level for, then we can see there is `NullPointerException` in `EventsToLegs` :
```
18:47:36.261 ERROR o.m.c.e.ParallelEventsManagerImpl - Thread Events-0 died with exception while handling events.
java.lang.NullPointerException: null
	at org.matsim.core.scoring.EventsToLegs.handleEvent(EventsToLegs.java:204)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:291)
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:222)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:136)
	at org.matsim.core.events.ProcessEventThread.run(ProcessEventThread.java:93)
	at java.lang.Thread.run(Thread.java:748)
```
Most probably this is causing drops in the graph.

**Comment by REASY** [comment]
When I run with gold old `EventsManagerImpl` instead of `LoggingParallelEventsManager` for 100 iterations, it looks fine (at least 1 run):
![image](https://user-images.githubusercontent.com/5107562/52903803-8c5c9f00-3255-11e9-8048-06f4929b0a99.png)

**Comment by wrashid** [comment]
thanks @REASY  - seems solved for the moment
