### ISSUE TITLE
Complete/Update basic tests for beamville

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#131]
- running without errors
- Tests Events file creation and correctness (csv and xml)
- events file contains all bus and train routes and same as input files
- buses and trains follow stop times provided in input files

- make sure sequence of events is correct
- make sure car used is owned by household

**Comment by wrashid** [comment]
add tests for both cases where qsim endtime is/is not forcing the agentsim to end.

**Comment by colinsheppard** [comment]
While you are completing this, can we get rid of all inputs that are not a part of the 50 person scenario?

**Comment by colinsheppard** [comment]
Nevermind, I'm already doing this on the cjrs/agentsim-lccm branch. Will merge into application-sfbay once I ensure no regressions.

**Comment by fdariasm** [comment]
@wrashid this is implemented in EventsFileSpec, I think we can close issue
