### ISSUE TITLE
increase history of run in jenkins?

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1323]
We have so many CI builds, that the build history list tends to go back no more than 1-2 days.

This makes it hard for reviewers to quickly inspect the last attempt to build a branch or PR.

Can we increase this sufficiently so we have ~1 week of history?

**Comment by JustinPihony** [comment]
Done - changed from a max of 25 builds, to 7 days of builds. The only thing to keep an eye on is hard drive space. I don't believe this is bulky, and we once hit it for a task that was stuck for a day or more. Now that may have been extreme, but if 7 days of builds becomes too much then it's a possibility. Nothing to jump on right now, more of an FYI to keep in the back of your head.
