### ISSUE TITLE
Household reference in vehicles.csv is not used

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#1326]
``vehicles.csv`` contains a column for the household to which the vehicle belongs. It is parsed but never used -- the household-vehicle-association is actually done in ``households.xml``.

**Comment by colinsheppard** [comment]
We have a plan to use this, when we read all scenario data from CSV. In this context there's no clean way to specify compound, hierarchical relationships. But since it's a one-to-many, we can achieve with HHId in the vehicle file.
