### ISSUE TITLE
Make ride hail agents respect geofence

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#1328]
There are geofence attributes in each ride hail agent. We need to therefore filter out these agents when finding ridehail agents via 

getClosestIdleVehiclesWithinRadiusByETA

this will require passing destination along with origin to this search function.

also, our algorithm in PoolingAlonsoMora needs to be made aware of this constraint (in addition to a range constraint).

While we're at it, let's remove getClosestIdleVehiclesWithinRadius (not used anymore) and getClosestIdleRideHailAgent (which doesn't take ETA into account).

**Comment by robfitzgerald** [comment]
I will try and go beyond "obey" and achieve "respect", but "obey" may be all that's possible here.
