### ISSUE TITLE
make file names consistent to allow automatic checking if specified file exists

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1342]
Currently, all the following configuration keys points to a file path:

- beam.agentsim.agents.modalBehaviors.lccm.paramFile = ${beam.inputDirectory}"/lccm-long.csv"
- beam.agentsim.agents.modeIncentive.file = ${beam.inputDirectory}"/incentives.csv"
- beam.agentsim.agents.ptFare.file = ${beam.inputDirectory}"/ptFares.csv"
- beam.agentsim.agents.vehicles.beamFuelTypesFile = ${beam.inputDirectory}"/beamFuelTypes.csv"
- beam.agentsim.agents.vehicles.beamVehicleTypesFile = ${beam.inputDirectory}"/vehicleTypes.csv"
- beam.agentsim.agents.vehicles.beamVehiclesFile = ${beam.inputDirectory}"/vehicles.csv"
- beam.agentsim.toll.file=${beam.inputDirectory}"/toll-prices.csv"
- beam.agentsim.taz.file=${beam.inputDirectory}"/taz-centers.csv"
- beam.agentsim.taz.parking = ${beam.inputDirectory}"/parking/taz-parking-default.csv"
- beam.agentsim.agents.rideHail.initialization.filename=${beam.inputDirectory}"/rideHailFleet.csv"
- beam.calibration.mode.benchmarkFileLoc=${beam.inputDirectory}"/calibration/benchmark.csv"
- inputPlansFile = ${beam.inputDirectory}"/population.xml"
- inputPersonAttributesFile = ${beam.inputDirectory}"/populationAttributes.xml"
- inputFile = ${beam.inputDirectory}"/households.xml"
- inputHouseholdAttributesFile = ${beam.inputDirectory}"/householdAttributes.xml"
- beam.physsim.inputNetworkFile = ${beam.inputDirectory}"/physsim-network.xml"

All the keys should follow an uniform convention in order to automate config file validation

**Comment by carloscaldas** [comment]
Matsim references (can it be changed?):

- matsim.modules.plans.inputPlansFile = ${beam.inputDirectory}"/population.xml"
- matsim.modules.plans.inputPersonAttributesFile = ${beam.inputDirectory}"/populationAttributes.xml"
- matsim.modules.households.inputFile = ${beam.inputDirectory}"/households.xml"
- matsim.modules.households.inputHouseholdAttributesFile = ${beam.inputDirectory}"/householdAttributes.xml"

**Comment by JustinPihony** [comment]
Should this be closed as this has now been merged?

**Comment by carloscaldas** [comment]
Can be closed since it was implemented in all the following PRs:
https://github.com/LBNL-UCB-STI/beam/pull/1468
https://github.com/LBNL-UCB-STI/beam/pull/1355
https://github.com/LBNL-UCB-STI/beam/pull/1452
