### ISSUE TITLE
reproduce/fix: numberOfVehicles in root folder on production run

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1404]
![image](https://user-images.githubusercontent.com/13569531/53902239-67627d00-4006-11e9-89b3-fdd688a6d430.png)

=> is this also happening on master? => if not, how to repair on production?

**Comment by rajnikantsh** [comment]
@wrashid , Its only coming on production branch not in master. So should i create a branch from master or from production.
