### ISSUE TITLE
fix/update: key not found: ride_hail_pooled

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1408]
![image](https://user-images.githubusercontent.com/13569531/53906246-0dff4b80-4010-11e9-941e-83be6d852a4e.png)

e.g. happening on production branch - but could also happen on any other probably, if turning on pooled ride

**Comment by rajnikantsh** [comment]
@wrashid  I am not getting this error on any of the branch. Do I have to change any param in conf to generate this error ?
