### ISSUE TITLE
fix/update: has exceeded max number of messages threshold

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1409]
currently the agent is not taken out immediately when "has exceeded max number of messages threshold" in stuckfinder happens. this can lead to thousands of prints of messages like the following, where current count can go far above max:

![image](https://user-images.githubusercontent.com/13569531/53919846-d3f27180-4030-11e9-842e-33f1257383a0.png)

=> happend on Branch production-sfbay-rhm, base-cav-test.conf => iteration 1, but should be solvable without reproducing

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1422
