### ISSUE TITLE
Remaining updates for Energy Visualization (TNC Viz Conversion)

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#141]
- replace external API calls to stats data by API calls to local server (provide an endpoint for that).
- Allow changing all labels in user interface in one central file - This will allow that we can use this visualization for any purpose, e.g. energy, traffic, parking, charging demand, etc.
- the y axis of the graph on the right side should be scaled automatically if data with max value above 20k is loaded

- Currently fixed legend images are provided, can we make them generic? If too difficult, can we provide 6 scales instead of just 2, as discussed earlier as a quickfix. In this case, at least the legend text has to be changable externally as well resp. should not be part of the image anymore.

- The TAZ colors should match the legend - is this hard coded somewhere?

- Is there some bug in the data viz generation? We should 2 peaks for car energy demand over the day.

**Comment by wrashid** [comment]
DONE: replace external API calls to stats data by API calls to local server (provide an endpoint for that).

**Comment by wrashid** [comment]
Please also add documentation for how to run the server, what command line arguments and where the input data files need to be placed.

**Comment by wrashid** [comment]
Currently we just have 2 dimensions (originally pickup and dropoff). How difficult is it to add more dimensions?

Can we configure the visualization in such a way that we don't have to provide (partially dummy) data for all 7 days, but can just provide data for those days we want to show (and in the user interface only the selected days are shown)?

**Comment by wrashid** [comment]
TODO: Provide multiple color scales for choice in config
TODO: Add numbers to legend

**Comment by fdariasm** [comment]
@wrashid, this issue is completed.  All code changes are on https://github.com/LBNL-UCB-STI/tncstoday.
