### ISSUE TITLE
Resolve Application-sfbay errors in Beamville tests

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#142]
Multiple test cases are passing, but still have errors in them. Make tests fail locally, fix them and commit updated tests.

E.g. already during initialization errors are happening and also in test ModeChoiceRideHailOnly

"Since an integration test does not allow to the internal processing of the participating actors, verifying expected exceptions cannot be done directly. Instead, use the logging system for this purpose: replacing the normal event handler with the TestEventListener and using an EventFilter allows assertions on log messages, including those which are generated by exceptions:" [https://doc.akka.io/docs/akka/current/java/testing.html]

**Comment by fdariasm** [comment]
@wrashid all non-ignored tests pass without error, and ignored tests fail but there is no error.
