### ISSUE TITLE
add random seed for UniformVehiclesAdjustment

### ISSUE THREAD

**Issue by rajnikantsh** [LBNL-UCB-STI/beam#1441]

**Comment by wrashid** [comment]
use this library: https://dst.lbl.gov/ACSSoftware/colt/

and random seed: beamServices.beamConfig.matsim.modules.global.randomSeed

**Comment by carloscaldas** [comment]
Created PR https://github.com/LBNL-UCB-STI/beam/pull/1449

**Comment by JustinPihony** [comment]
Is this able to be closed now that #1449 is merged?
