### ISSUE TITLE
create test for warmstart skimmer and routehistory

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1448]

**Comment by carloscaldas** [comment]
Test for RouteHistory was already implemented in the past. The following PR added a test for load/write csv of Skimmer: https://github.com/LBNL-UCB-STI/beam/pull/1784/files

**Comment by carloscaldas** [comment]
Closed with PR https://github.com/LBNL-UCB-STI/beam/pull/1784
