### ISSUE TITLE
why bus traveltimes in DelayMetricAnalysis lower than freeFlowSpeed?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1473]
```WARN  beam.analysis.DelayMetricAnalysis -  The delay is negative and the delay``` comming a lot 

DelayMetricAnalysis:43 was before only looking at CAR mode and now it also looks at buses as well (which was a recent fix). The warning points to the fact, that bus travel times coming in are faster than the allowed road speed. This is the case both for beamville and other scenarios. 

why? E.g. Is it possible that the low travel times for buses are just due to inaccurate schedules?

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1477
