### ISSUE TITLE
ExponentialLoggerWrapperImpl might cause memory leak

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1488]
Currently no one call `ExponentialLoggerWrapperImpl.reset()` to clean-up the data which is used for https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/utils/logging/ExponentialLoggerWrapperImpl.scala#L67
Also that field is private for companion object, but can shared across multiple classes. In that case `reset` will reset the message -> counter stats for all others.

Also, why would not we use some fast hash function instead of storing the whole string to reduce memory usage. Here is great comparison of fast non-secure hash functions: https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed/145633#145633

**Comment by carloscaldas** [comment]
> Also, why would not we use some fast hash function instead of storing the whole string to reduce memory usage.

Currently is storing the first 20 characters. Storing the hash made the message useless unless we have all messages registered in the same place.

> Also that field is private for companion object, but can shared across multiple classes. In that case reset will reset the message -> counter stats for all others.

ExponentialLoggerWrapperImpl should not be referenced by other classes. Clients should be coupled to the interface not to the implementation.

**Comment by JustinPihony** [comment]
Did #1514 fix this, and it can be closed?
