### ISSUE TITLE
DelayMetricAnalysis throws null pointer exception

### ISSUE THREAD

**Issue by bhavyalatha26** [LBNL-UCB-STI/beam#1491]
StackTrace Info

```bash
java.lang.NullPointerException: null
```

DelayMetricAnalysis # 83

DelayMetricAnalysis # 73

**Comment by REASY** [comment]
Need to make sure that correct network is used. There should be warning logs before saying something like
```
16:19:12.683 [ClusterSystem-akka.actor.default-dispatcher-22] ERROR beam.utils.NetworkHelperImpl - getLinkUnsafe for 20388, when allLinks length is 380 and MaxLinkId is 379!
```

**Comment by rajnikantsh** [comment]
closing this after discussion with @bhavyalatha26 , This issue is no more now
