### ISSUE TITLE
ParkingStatsCollector: Append to Scala List is linear

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1524]
There are multiple places where append to List happens: [ParkingStatsCollector.scala#L226](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/analysis/ParkingStatsCollector.scala#L226) and [ParkingStatsCollector.scala#L265-L266](https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/analysis/ParkingStatsCollector.scala#L265-L266).
Append to [the List has linear complexity](https://docs.scala-lang.org/overviews/collections/performance-characteristics.html).

**Comment by bhavyalatha26** [comment]
ok .. will replace with prepend .. thanks for pointing it out @REASY
