### ISSUE TITLE
log vehicle category

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1525]
beamHelper current output:

Number of households: 1699643
Number of vehicles: 5257078
Number of persons: 2578046

can we add the vehicle types behind number of vehicles, e.g.

Bike (339891) , Car(687)

see example in beam.sim.RunBeam =>  - Vehicles assigned to households : Bike (339891) , PHEV_Low (687)

**Comment by JustinPihony** [comment]
Closed via #1530
