### ISSUE TITLE
Incentives in summary stats should not be normalized by cost events

### ISSUE THREAD

**Issue by sfwatergit** [LBNL-UCB-STI/beam#1564]
Currently, in PersonCostAnalysis.java the net cost for each cost category is computed; however, it is also normalized by the number of cost events for the associated cost category. 

This implies something like an average cost per trip, though not exactly. The semantics of this whole operation are unclear and should be refined.

For external use purposes, it would make sense to compute the total cost per category over all agents rather than average cost.

**Comment by wrashid** [comment]
merged
