### ISSUE TITLE
production run network quality check

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1576]
-> do matsim network properties make sense? number of lanes, speed and capacity distributions?
-> did conversion from osm work as intended, e.g. speed translation?
-> why errors logged for production run?

**Comment by REASY** [comment]
Partially fixed by https://github.com/LBNL-UCB-STI/beam/pull/1707

**Comment by REASY** [comment]
There is other fix in R5: https://github.com/conveyal/r5/issues/509
