### ISSUE TITLE
Transit not used

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#160]
When production of sf-light run, no one choose transit.

This is due to some recent changes in mode choice which now distinguish between WALK-TRANSIT and DRIVE-TRANSIT.

**Comment by colinsheppard** [comment]
Getting agents to choose these modes was easy... but now there are a couple of transit related bugs causing model to stall (skipOverBadActors is FALSE). So this issue has now morphed into debugging those.

**Comment by colinsheppard** [comment]
The transit bug was due to the GTFS data having unrealistic stop times... specifically, subsequent stops on a trip would have the exact same timestamp... when loaded and run in BEAM, this caused agents to get "confused" about StartLeg trigger should happen first... for transit trips with a large number of stops that all have the same timestamp, the agent get's stuck.

My solution to this was to amend the GTFS data and repair these stop sequences by replacing the stop times with ones that interpolated between successive stops for which there is a change in time. E.g. if previously the stops looks like A:0, B:0, C:0, D:15.... then the repaired sequence would become A:0, B:5, C:10, D:15.

**Comment by colinsheppard** [comment]
See PR #164 for the new script, under src/main/R/bin/repairStopTimes.R

**Comment by michaz** [comment]
I'm working on branch ``islandpruning``, where I removed your time window fix for the end-of-day problem again. It prevents many (all?) transit trips, since for transit trips, the actual departure time is _normally_ outside the time window.

(The time window specifies the _earliest_ departure time. R5 responds with the actual departure time.)

**Comment by michaz** [comment]
((We have a transit router test now, can't happen again.))

**Comment by colinsheppard** [comment]
Yeah, I saw that... problem is that yesterday I definitely found a case where a trip was 24 hours after the time window. So we need a filter to prevent that. My working solution right now is to filter out anything more than 30 minutes after the start of the window.

**Comment by michaz** [comment]
Okay.. and why does a trip 24 hours after the time window lead to errors on our side? Are we making yet another day-wrapping error on top of that, or is it something else?

Otherwise I'd think the agent would just go on a very late trip..

**Comment by colinsheppard** [comment]
Yeah, I think we're making a day wrapping error on top of the issue... the start times for the walk legs end up a day ahead of the start times for the transit legs.
