### ISSUE TITLE
UrbanSimScenarioSource: convert info message to error message

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1612]
only log error if rawPlanElements.size!=planElements.length
![image](https://user-images.githubusercontent.com/13569531/55362185-e2e90a00-549e-11e9-98f3-30c4adb80f65.png)

**Comment by carloscaldas** [comment]
Merged in the PR https://github.com/LBNL-UCB-STI/beam/pull/1649
