### ISSUE TITLE
make event handling resilient to errors

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1636]

**Comment by wrashid** [comment]
e.g. separate thread/try catch on highest level, add separate event handler for the events writing, so that it is never affected?

**Comment by REASY** [comment]
PR in MATSim which solves the issue: https://github.com/wrashid/matsim/pull/3

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/1549
