### ISSUE TITLE
cacc histogram wrong?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1659]

**Comment by bhavyalatha26** [comment]
Can you add little more details to this issue @wrashid

**Comment by wrashid** [comment]
on production run we had too little data for this. can you share for sflight?

**Comment by rajnikantsh** [comment]
on sf-light-5k with following configuration 

beam.physsim.jdeqsim.cacc.enabled = true
beam.physsim.jdeqsim.cacc.minRoadCapacity = 2000
beam.physsim.jdeqsim.cacc.minSpeedMetersPerSec = 20
beam.physsim.jdeqsim.cacc.speedAdjustmentFactor = 1.0

Graphs are attached
![0.caccRoadCapacityHistogram.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b59e2a42c7a8600132d4e2c/125516c66e82c728ace21e0d46b8da992281809b80e8bb60a54df19720523e5b2017b7247797e225fd0e39111d0014f9121c4d4eeefcdb2fa0b339738c585db9d83c5974c63c43acead718b809a83c990dd4e8e8d51199a26867f5819d4e3914041d8cfa5e33a39b4fc158f04ff300.png)
![0.caccRoadCapacityIncrease.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b59e2a42c7a8600132d4e2c/125516c66e82c728ace21e0d46b8da992281809b80e8bb60a54df19720523e5a2707b12e7196e66af3006b1300051bff054a5556f9ab8d2da3b33f768e0a5fe4806b5f74c76f11feed8518b713a632c91edbe2e3d7158abd7f37ed998e46341f001d8cfc5b36a29d42c85ef459ac.png)

**Comment by wrashid** [comment]
you might have to use vehicle fleet with CAVs for this

**Comment by bhavyalatha26** [comment]
PFA the resultant graphs for Sf-light 5k

![0 caccRoadCapacityHistogram](https://user-images.githubusercontent.com/13586777/56203719-69871500-6063-11e9-8e28-c56b33029aa6.png)
![0 caccRoadCapacityIncrease](https://user-images.githubusercontent.com/13586777/56203720-69871500-6063-11e9-80bd-26283fd86cf5.png)

**Comment by bhavyalatha26** [comment]
PFA the resultant graphs for Sf-light 5k

![0 caccRoadCapacityHistogram](https://user-images.githubusercontent.com/13586777/56203719-69871500-6063-11e9-8e28-c56b33029aa6.png)
![0 caccRoadCapacityIncrease](https://user-images.githubusercontent.com/13586777/56203720-69871500-6063-11e9-80bd-26283fd86cf5.png)

**Comment by bhavyalatha26** [comment]
PFA the resultant graphs for Sf-light 1k @wrashid 

![0 caccRoadCapacityHistogram](https://user-images.githubusercontent.com/13586777/56205821-79552800-6068-11e9-8da7-d815cd0b0dd5.png)
![0 caccRoadCapacityIncrease](https://user-images.githubusercontent.com/13586777/56205823-79552800-6068-11e9-8e5d-cc7b8799ae1c.png)

**Comment by bhavyalatha26** [comment]
**Update :**

- Currently the existing histogram shows only for CACC enabled roads. 
- Add a new graph to show histogram for all roads (CACC + non CACC)

**Comment by JustinPihony** [comment]
Fixed by #1738
