### ISSUE TITLE
Testing Akka Messages and Protocols

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#168]
just tested the code on rw/test-msg-protocol branch -> structure in general looks good (needs some refactoring, which we can do in next days)

Task 1: create test, which asserts that physsimActor receives a start message in the beamville test scenario, the eventManagerActor receives a "sufficient" amount of messages from the physsim, the eventManagerActor sends back a TravelTimeCalculator to the physsimActor and that the physsimActor forwards such an object to the router.

Task 2: allow simple filtering methods on AkkaMessageLogger which can be used by various tests.

Task 3: evaluate where this testing approach could be applied elsewhere in the system, e.g. standard protocols?

**Comment by michaz** [comment]
``PersonAgentSpec`` on master contains a small example of how to use Akka's logging facilities for testing. No custom infrastructure is necessary.

**Comment by michaz** [comment]
In general, collecting Events in a list and analyzing them afterwards _doesn't scale_. This doesn't work even now for the SfLight scenario.

**Comment by wrashid** [comment]
Thanks for the hint Michael, will look further into this if this can cover all test cases conveniently.

**Comment by michaz** [comment]
The ``LoggingReceive`` thing is nice though!
