### ISSUE TITLE
Figure it out and remove duplication between Vehicles and HouseHolds

### ISSUE THREAD

**Issue by carloscaldas** [LBNL-UCB-STI/beam#1690]
Currently the file vehicles.csv contains the field `houseHoldId` and the `houseHolds.xml` file contains the `vechicleId` which is a duplication.
Should identify which one is used and remove the duplication

**Comment by wrashid** [comment]
also household missing in sflight vehicles

**Comment by carloscaldas** [comment]
In the issue https://github.com/LBNL-UCB-STI/beam/issues/1691 was stated that the goal is actually the opposite (make csv files normalized and flat). Closing this Issue
