### ISSUE TITLE
OSMOSIS Clipping Issue

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#17]
When OSM data is clipped by OSMOSIS, it causes errors in while loading into R5. We are reaching out to Conveyal for help but this Issue is to track any work we do diagnosing or fixing the problem.

**Comment by zishanbilal** [comment]
An issue with exception stacktrace and initial problem analyses is created on R5 repository. Please find link on R5 https://github.com/conveyal/r5/issues/276.

**Comment by zishanbilal** [comment]
R5 team took following action to close the issue. https://github.com/conveyal/r5/commit/a55ffc309f6f82f7b8730190a41f16c9f622ad7e

**Comment by colinsheppard** [comment]
Thanks Zeeshan! The other issue I experience was due to filtering highways, which we should avoid when using R5.
