### ISSUE TITLE
Remove various hard coded local paths in beam.sim.config.BeamConfig

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#170]

**Comment by michaz** [comment]
Anything automagical should go away, e.g.: 

- reading of environment variables should disappear from code (the config framework already allows substituting them in the config file).
- a filename should always be interpreted as a filename, not first tried as a filename and then, if that doesn't exist, as a resource path.

Reason: This leads to a situation where you just move your files around until it works for some reason, but you're not sure why. And eventually, you will be using a different config file than you think.
