### ISSUE TITLE
People arrive on different modes than they depart

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#174]
See plots in iteration directories, e.g.

![0 leghistogram_walk](https://user-images.githubusercontent.com/520916/33784764-defe4ccc-dc16-11e7-9c1e-d9b9bfeac0b9.png)
![0 leghistogram_car](https://user-images.githubusercontent.com/520916/33784768-e200ee8e-dc16-11e7-9a96-5aebef2d65f5.png)

**Comment by colinsheppard** [comment]
Looks like this value is being saved in the wrong place:

      val savedLegMode = _currentRoute.tripClassifier

Should be saved not inside processNextLegOrStartActivity but rather somewhere that captures the tripClassifier at the beginning of the trip, otherwise, because _currentRoute is consumed and tripClassifier dynamically infers the mode, we end up with the wrong classification.

**Comment by michaz** [comment]
Ah, but isn't tripClassifier the "big" mode? For MATSim legs, we will need the "small" modes, e.g. driving to transit is one leg, and then taking transit is the next leg.

**Comment by colinsheppard** [comment]
So what event types produce these histograms? We're currently only throwing PersonalArrival and PersonDeparture which have a mode associated with them. It sounds like what you are looking for is the MATSim equivalent to a BEAM PathTraversalEvent?

**Comment by michaz** [comment]
Ah yeah. And PersonArrival and PersonDeparture in MATSim terms are meant the same way.

**Comment by michaz** [comment]
(I was wondering why path traversal events even exist..)

**Comment by colinsheppard** [comment]
We used them to define vehicle movements as separate from person movements.

**Comment by michaz** [comment]
Ah! Okay! Hmmmm.. and Rashid generates his JDEQSim plans from those events. Yeah, I guess then we can decide ourselves what mode we put in departure/arrival events, and whether they are trips or legs, and we should only fix the bracketing.

But in MATSim, what is called a leg is what is opened by a departure and closed by an arrival. Maybe worth noting.

**Comment by colinsheppard** [comment]
Right.... a MATSim Leg is akin to a BeamTrip.

**Comment by michaz** [comment]
Hmmhmm. Just noting that when we do multimodal trips in Matsim, we open/close multiple legs. Otherwise, we wouldn't be able to move a car over the network in the first leg, and put the person on a train in the second leg. All of this happens by leg in Matsim.

Is there a reason we're throwing the departure/arrival events the way we're doing it, or could we just switch to doing in by leg instead of by trip?

**Comment by colinsheppard** [comment]
No reason other than I must have misinterpreted how MATSim defines legs.

**Comment by michaz** [comment]
Noooo, that's our fault, really. Because _initially_ those things were the same, we use the same language for what's in the plans, and for what really happens (gets scored).

In the initial plans, of course, a leg is what is between two activities.

In the _routed_ plans, legs are already .. legs. I.e. in a transit trip, there are multiple legs.

And in the outcome (i.e. in the event stream), too.

**Comment by michaz** [comment]
![0 leghistogram_walk](https://user-images.githubusercontent.com/520916/33787517-731e942e-dc22-11e7-96c1-9e7e4a4423cc.png)

![0 leghistogram_car](https://user-images.githubusercontent.com/520916/33787521-799702aa-dc22-11e7-80e7-ea0e041590f1.png)
