### ISSUE TITLE
Stable link IDs, lack of

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#1781]
At some point, we started treating R5 link IDs as public identifiers. E.g. in warm start routing and tolls.

But they can change any time. Nowhere does R5 make any promise that the way OSM data is converted to a graph can't change. With the new R5 version, it seems to _have_ changed, so that old toll files won't be usable anymore.

Any thoughts about how to deal with this in the long term?

**Comment by michaz** [comment]
Related: #1782

**Comment by michaz** [comment]
("That's the user's problem" is totally fine.)

**Comment by REASY** [comment]
Solved in https://github.com/LBNL-UCB-STI/beam/pull/1771 via https://github.com/LBNL-UCB-STI/beam/pull/1771/commits/29e9e544d6bac8487e5d0dea490f73f29766f184

**Comment by michaz** [comment]
Not quite what I meant. Link IDs changed from the previous R5 version to the current one. Suppose people have large data files, e.g. of link tolls, these have to be completely re-created after the update. And this can happen again anytime.

I just wanted to point this out since users must be aware that they need to keep any scripts they use to create toll files, since they have to be able to re-run them after such updates.
