### ISSUE TITLE
collect data for urban network clustering

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1788]
- Download [US cencus tracts](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2018&layergroup=Census+Tracts) for a single state first.
- Visualize it with the [OSMNX library ](https://github.com/gboeing/osmnx)
- Produce an image of each Census Tract, and also produce a CSV that has the following:
`Tract ID, Sum of Road Miles of Type Residential, Sum of Road Miles of Type Arterial, ……`
 _for all of the “highway” types_

**Comment by bhavyalatha26** [comment]
**Attached graphs of first 10 areas from "Alabama" shape file**.

- These are **polygons** generated from the shape files provided as input to the **osmnx** library
- The resultant polygon graphs are saved as **png**
- Right now I used the **geoId** as the filename (there was no place name in the dataframe).

#### Script

Here is the little script I used to generate this : 

```python
import osmnx as ox
import geopandas as gpd

inputFilePath = "/home/beam/streetmaps/alabama"
outputFilePath = inputFilePath + "/results/"
calif = gpd.read_file(inputFilePath)
for row in calif.itertuples(index=False):
    polygon = row.geometry
    geoId = row.GEOID
    polygonGraph = ox.graph_from_polygon(polygon)
    G_projected = ox.project_graph(polygonGraph)
    # supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz
    filename = outputFilePath + geoId
    ox.plot_graph(G_projected, show=False, save=True, filename=filename, file_format='png')]

``` 
#### Resultant graphs

![01019955701](https://user-images.githubusercontent.com/13586777/57431114-61c82400-724f-11e9-9971-3470e7099e54.png)
![01043964100](https://user-images.githubusercontent.com/13586777/57431116-6260ba80-724f-11e9-8a9e-cb2a79960aa4.png)
![01043964200](https://user-images.githubusercontent.com/13586777/57431117-6260ba80-724f-11e9-8988-7cf99e2a3345.png)
![01043964400](https://user-images.githubusercontent.com/13586777/57431118-6260ba80-724f-11e9-9474-24c1bfae1a5b.png)
![01043964500](https://user-images.githubusercontent.com/13586777/57431120-62f95100-724f-11e9-872a-fce498626013.png)
![01043964700](https://user-images.githubusercontent.com/13586777/57431122-62f95100-724f-11e9-98b1-4620ad17cd00.png)
![01043964900](https://user-images.githubusercontent.com/13586777/57431123-62f95100-724f-11e9-9b64-70079f4c90c3.png)
![01043965000](https://user-images.githubusercontent.com/13586777/57431124-62f95100-724f-11e9-9bc3-94bb40cf85a7.png)
![01043965600](https://user-images.githubusercontent.com/13586777/57431127-6391e780-724f-11e9-8aa4-0fee2145a232.png)
![01075030000](https://user-images.githubusercontent.com/13586777/57431128-6391e780-724f-11e9-83ae-1628262207ea.png)

**Comment by colinsheppard** [comment]
@bhavyalatha26 this is a great start. Can we do a could of thing:

* Standardize the scale -- each image should be the same scale, e.g. every one should be XX meters per pixel
* Shrink the size of the blue nodes and remove their color (make them black), also let's create an alternative set of graphs that don't have any blue circles at the intersections
* Use a color scale and a variable width on each road to indicate the capacity of the road (i.e. max # of vehicles that can pass through per hour), use the same capacity values that we use in BEAM. Make the color scale continuous, e.g. from light grey to black.

**Comment by bhavyalatha26** [comment]
ok @colinsheppard

**Comment by bhavyalatha26** [comment]
Hi @colinsheppard . 
Attaching changes of the new graphs generated with the below changes :
- Standardized the scale -- each image should be the same scale
- Shrink the size of the blue nodes and remove their color (make them black)
- Color scale - grey to black

#### Code :
Here is the new snippet : 

```python
import osmnx as ox
import geopandas as gpd

inputFilePath = "/home/beam/streetmaps/alabama"
outputFilePath = inputFilePath + "/results/"
df = gpd.read_file(inputFilePath)
for row in df.itertuples(index=False):
    polygon = row.geometry
    geoId = row.GEOID
    polygonGraph = ox.graph_from_polygon(polygon)
    G_projected = ox.project_graph(polygonGraph)
    # supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz
    filename = outputFilePath + geoId
    ec = ox.get_edge_colors_by_attr(G_projected, attr='length',cmap="gray_r")
    ox.plot_graph(G_projected, show=False, save=True, filename=filename, file_format='png', node_size=50,
                  node_color='#000000', node_zorder=3, edge_linewidth=5, dpi=100, fig_height=30,
                  fig_width=30, edge_color=ec)
```
#### Graphs :

![01019955701](https://user-images.githubusercontent.com/13586777/57789718-1df58300-7757-11e9-9c3c-92420c0d38b0.png)
![01043964100](https://user-images.githubusercontent.com/13586777/57789720-1e8e1980-7757-11e9-944a-f1c96be3db38.png)
![01043964200](https://user-images.githubusercontent.com/13586777/57789721-1e8e1980-7757-11e9-8a16-ee669dcaf022.png)
![01043964400](https://user-images.githubusercontent.com/13586777/57789723-1e8e1980-7757-11e9-986e-edca53be58ba.png)
![01043964500](https://user-images.githubusercontent.com/13586777/57789724-1f26b000-7757-11e9-9aec-f2bdfe21c590.png)
![01043964700](https://user-images.githubusercontent.com/13586777/57789725-1f26b000-7757-11e9-8493-c1fd09d64646.png)

**Comment by bhavyalatha26** [comment]
Hi @colinsheppard 

Attaching the newly generated graphs with the below changes :

- Edge color and width based on edge capacities

#### Code :

Here is the new snippet :

```python
import geopandas as gpd
import osmnx as ox
import pandas as pd

uniqueEdgeColorsDict = {}
edgeHighwayCapacityDict = {
    "motorway": 2000,
    "motorway_link": 1500,
    "primary": 1500,
    "primary_link": 1500,
    "trunk": 2000,
    "trunk_link": 1500,
    "secondary": 1000,
    "secondary_link": 1000,
    "tertiary": 600,
    "tertiary_link": 600,
    "minor": 600,
    "residential": 600,
    "living_street": 300,
    "unclassified": 600
}


def get_capacity(data: dict):
    """
    Generates the total edge capacity based on the highway type and number of lanes
    :param data: the edge attributes
    :return: total capacity of the edge
    """
    no_of_lanes = data.get('lanes', 1)
    one_way = data['oneway']
    highway = data['highway']
    if type(highway) is list:
        capacity = max(map(lambda x: edgeHighwayCapacityDict.get(x, 100), highway))
    else:
        capacity = edgeHighwayCapacityDict.get(highway, 100)
    if type(no_of_lanes) is list:
        lanes = max(no_of_lanes)
    else:
        lanes = no_of_lanes
    if highway == "primary" or highway == "secondary" or highway == "trunk":
        if one_way and no_of_lanes == 1:
            lanes = 2
    print("highway ", highway)
    print("lanes ", lanes)
    print("capacity ", capacity)
    return float(lanes * capacity)


def get_edge_colors_and_widths(G, num_bins=5, cmap='viridis', start=0, stop=1, na_color='none'):
    """
    Get a list of edge colors and edge weights based on the edge capacity

    Parameters
    ----------
    G : networkx multidigraph
    num_bins : int
        how many quantiles
    cmap : string
        name of a colormap
    start : float
        where to start in the colorspace
    stop : float
        where to end in the colorspace
    na_color : string
        what color to assign nodes with null attribute values

    Returns
    -------
    list , list
    """
    if num_bins is None:
        num_bins = len(G.edges())
    attr_values = pd.Series([get_capacity(data) for u, v, key, data in G.edges(keys=True, data=True)])
    cats = pd.qcut(x=attr_values, q=num_bins, labels=False, duplicates='drop')
    colors = ox.get_colors(num_bins, cmap, start, stop)
    edge_colors = [colors[int(cat)] if pd.notnull(cat) else na_color for cat in cats]
    edge_weights = [(int(cat) * 2) + 1 for cat in cats]
    return edge_colors, edge_weights


inputFilePath = "/home/beam/streetmaps/alabama"
outputFilePath = inputFilePath + "/results/"
df = gpd.read_file(inputFilePath)
for row in df.itertuples(index=False):
    polygon = row.geometry
    geoId = row.GEOID
    polygonGraph = ox.graph_from_polygon(polygon)
    G_projected = ox.project_graph(polygonGraph)
    # supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz
    filename = outputFilePath + geoId
    (ec, ew) = get_edge_colors_and_widths(G_projected, cmap="gray")
    ox.plot_graph(G_projected, show=False, save=True, filename=filename, file_format='png', node_size=0,
                  edge_linewidth=ew, dpi=100, fig_height=30,fig_width=30, edge_color=ec)
```

#### Graphs :
![01017953800](https://user-images.githubusercontent.com/13586777/57939699-81fb8100-78e8-11e9-8187-e1ea9c7a8bdd.png)
![01017954300](https://user-images.githubusercontent.com/13586777/57939703-83c54480-78e8-11e9-98bd-5da738afa09f.png)
![01039962800](https://user-images.githubusercontent.com/13586777/57939708-87f16200-78e8-11e9-8367-8ef2bc7da775.png)
![01043965600](https://user-images.githubusercontent.com/13586777/57939779-a9524e00-78e8-11e9-8f24-49c44f5c699d.png)
![01075030100](https://user-images.githubusercontent.com/13586777/57939794-aeaf9880-78e8-11e9-91a8-f7a5e0913860.png)
![01043964700](https://user-images.githubusercontent.com/13586777/57939717-8cb61600-78e8-11e9-8013-dce7fbeeca7e.png)
![01043965000](https://user-images.githubusercontent.com/13586777/57939730-92136080-78e8-11e9-8121-0ee4704861c3.png)
