### ISSUE TITLE
Migrate RidehailFleetData to be output at the root

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#1854]
It is currently output per iteration, however each time it is duplicative. This means that these should only be loaded once at the overall start of BEAM - and utilized throughout from memory

**Comment by JustinPihony** [comment]
This one again could probably be verified by @colinsheppard also, however I am more confident in saying that he is referring to 0.rideHailFleet.csv.gz and the like. This is triggered from `new RideHailFleetInitializer().writeFleetData(beamServices, fleetData)`, and it seems that he is suggesting we can load the `fleetData` once only since it'll be the same init over and over. That part should be verified with code and by Colin

**Comment by carloscaldas** [comment]
Closed by https://github.com/LBNL-UCB-STI/beam/pull/2752

**Comment by colinsheppard** [comment]
Sorry I didn't notice this one before... but there is a rationale for having output every iteration. It allows us to carry state from one iteration to the next... specifically the starting locations, shifts, and vehicle SOC.

**Comment by carloscaldas** [comment]
Reverted by the PR https://github.com/LBNL-UCB-STI/beam/pull/2764

**Comment by JustinPihony** [comment]
@colinsheppard I thought we felt this was duplicative and pretty constant - and we should read from the root unless it is ACTUALLY changed?
