### ISSUE TITLE
Migrate UrbanSim to be output at the root 

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#1855]
It is currently output per iteration, however each time it is duplicative. This means that these should only be loaded once at the overall start of BEAM - and utilized throughout from memory

**Comment by JustinPihony** [comment]
This one was created after talking with @colinsheppard and he should be able to speak to it better. However I believe he was referring to things like plans, household, etc - but I am iffy on that.

**Comment by carloscaldas** [comment]
@colinsheppard could you clarify this ticket?

**Comment by colinsheppard** [comment]
What specific output are we talking about here?  There is no "UrbanSim" output that I'm aware of.

Can you give me the file names you are referring to?

**Comment by JustinPihony** [comment]
If there is no clear path forward then I'd say we should close this one. Maybe my recollection was off or I had a misunderstanding from our talk then. If it was important then it'll resurface at some point :)
