### ISSUE TITLE
detect duplicated config keys in config file

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#1862]

**Comment by michaz** [comment]
Hmm, what's the plan here? The config is parsed by a framework. Are you going to drill into that?

**Comment by rajnikantsh** [comment]
yes @michaz . looking into typesafe config framework

**Comment by michaz** [comment]
But if it doesn't have that feature, we are not going to patch that framework just in order to get that feature in, are we?

**Comment by rajnikantsh** [comment]
Typesafe library does not have feature to detect overwtitten keys in config files. Also this library core classes are not public they are having package lavel access so we can't access them by inheritance that means we can not change there behaviour. We are looking some way to do this without this library.

**Comment by rajnikantsh** [comment]
closed via #1880
