### ISSUE TITLE
BeamServices must die

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#1871]
I feel I'm allowed to say that, because BeamServices was modelled after MatsimServices, and I am the author of MatsimServices.

MatsimServices is a refactoring device. It was meant to be used by Matsim code which does not use dependency injection, to access things that new code should access by dependency injection.

In Beam, it is just harmful. It is a magnet for misunderstandings, and for code that makes refactorings and concise tests impossible. It is used in ways that follow no pattern, we've had _everything_:

- Injector wrapped in BeamServices
- BeamServices wrapped in Injector
- MatsimServices wrapped in BeamServices
- Methods on BeamServices that _are notified of things_
- Setters and Getters on BeamServices
- Mocked BeamServices
- Overridden BeamServices

It dispenses from trying to do what you want to do with _local_ information rather than global information, which is super-important to do, _in particular_ in actor-like programming.

Things you put in BeamServices are _worse than global variables_: A global variable can at least remain in your own code.

**Comment by JustinPihony** [comment]
This is a bit low priority last I heard - it will require quite a refactoring to handle appropriately. I'm all in for when we decide to bite the bullet though

**Comment by michaz** [comment]
> it will require quite a refactoring to handle appropriately

Yeah, I know, I do these kinds of refactorings partially, when I want to test things and can't. If I didn't, BeamServices would be twice as long. It just seems that its continued existence prevents a dialogue about alternatives from happening. ,-) So things just keep coming back.

**Comment by michaz** [comment]
BeamServices just with a couple of `def`s that reach in the wrapped `injector` is fine, that's what it was meant for. If we can get rid of the rest, put a big "DON'T PUT ANYTHING ELSE HERE EXCEPT ACCESSORS THAT DELEGATE TO THE INJECTOR" there, and it works -- fine!

**Comment by michaz** [comment]
Related: #1853 

How are you going to do this when it's unclear what order stuff in BeamServices is initialized in?

**Comment by michaz** [comment]
Also related: #1136 
A pure data structure that binds together a couple of things (person-to-household asoociation, transit fares, TAZs, whatever) is totally fine.

**Comment by michaz** [comment]
After ending the lastest refactoring cycle, I maintain my initial position that the main problem is that when a class requires `BeamServices`, it can't be reasonably tested, period.
