### ISSUE TITLE
Plans.csv are shifted by one iteration

### ISSUE THREAD

**Issue by michaz** [LBNL-UCB-STI/beam#1905]
Matsim writes its plans at the beginning of the iteration. Plans.csv is written at the end. I think it should be written at the beginning, too.

E.g. compare plans.xml and plans.csv in an it.0 -- csv contains CAV legs, xml doesn't.

**Comment by michaz** [comment]
Maybe related #1875 #1878

**Comment by carloscaldas** [comment]
Finished with PR https://github.com/LBNL-UCB-STI/beam/pull/1937
