### ISSUE TITLE
Find and move all tokens from github to the base instance which is used for the runs

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1954]
Recently we received the following message in beam-deployment Slack channel
```
Deployment UpdaterAPP [5:52 AM]
Hi,
Do you know that your slack webhook token is publicly available on github ? :sweat_smile:
I am posting the process about how did I found it in my Instagram Stories! 
https://www.instagram.com/gruppiofigo/
```
We store the token as a plain text: https://github.com/LBNL-UCB-STI/beam/blob/develop/aws/src/main/python/beam_lambda/lambda_function.py#L85. It was done just to make Slack integration done. Probably they got it via full text search at github Probably got via full text search in Github https://github.com/search?q=https%3A%2F%2Fhooks.slack.com%2Fservices&type=Code

In order to complete this, we should
1) Create new webhook
2) Add slack integration script with new token as a part of main AMI images used for simulation
3) Fix Lambda function (Please, make sure you get the latest lambda function from AWS, not the one which is under source control!)

Also good to search for other tokens in our repo.

**Comment by JustinPihony** [comment]
Where should we store tokens? How about [keybase](https://keybase.io/)?

**Comment by REASY** [comment]
I have not worked with `keybase`, can't tell much. But here is 3 possible ways to deal with it:
- Use [BlackBox ](https://github.com/StackExchange/blackbox) to safely store credentials/tokens/secrtes under source control. Basically, it is a wrapper on top of GPG command line tool. The only difficult part for it is adding new users/revoke previous keys.
- Use [Vault](https://www.vaultproject.io/). Recently we moved from `BlackBox` to `Vault` as a centralized tool to handle the secrets. But it seems to me kind of overkill for us.
- Prepare AMI image with properly populated tokens and use then as an environment variables in the scripts
