### ISSUE TITLE
Extract only the part related to the docker image

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#1977]
We definitely need to bring PR https://github.com/LBNL-UCB-STI/beam/pull/1975 to the develop, but it contains too many different changes and I'm afraid it is not the right moment to merge it to develop. Instead, let's extract only the part which is related to the docker image creation to new PR and merge it.

**Comment by kirillm-nor** [comment]
PR https://github.com/LBNL-UCB-STI/beam/pull/1980
