### ISSUE TITLE
ParkingSpec is unstable

### ISSUE THREAD

**Issue by johanneshiry** [LBNL-UCB-STI/beam#2008]
Looks like ParkingSpec *most of the time* runs successfully (=all tests in the class pass) but it randomly(?) happens that ParkingSpec:210 _"expensive parking should reduce driving"_ and ParkingSpec:224 _"empty parking access should reduce driving"_ are both failing (most of the time I observed it with a number close or equal to the base-case value).

I assume this is due to the logic how agents choose their daily plan / it's adaptions, which causes a reduction of driving behavior _randomly_ earlier or later iteration-wise. But I didn't worked with this part enough to fully confirm or even know how to fix it if it is an issue.

Maybe somebody can confirm or deny if we need to tackle this or not?

**Comment by colinsheppard** [comment]
We need to tackle this at some point. Not the highest priority at the moment. I did add "ignore" to the empty parking test on a recent PR because it was failing frequently.

**Comment by colinsheppard** [comment]
One potential reason for the issue could be that using beamville doesn't actually penalize folks for empty parking since they are still given a spot "far away" which in beamville isn't that far.

As for expensiveness, this should still cause a notable difference in mode choice, so we need to look into it.

**Comment by zneedell** [comment]
FWIW, I ran some tests on sfbay varying parking cost and availability. For availability results were expected (less parking means more transit and ridehail). But for cost, changes were minimal when increasing and decreasing cost by a factor of two. Part of this is certainly that most parking in sfbay is free, but it could be that people are less sensitive to price than we would expect.

**Comment by REASY** [comment]
Ignoring this test for now because we have to force merge it: https://github.com/LBNL-UCB-STI/beam/pull/2026/commits/27a2de293652da0357b8c3090c07cc9734a9369e

**Comment by carloscaldas** [comment]
Closed by https://github.com/LBNL-UCB-STI/beam/pull/2767
