### ISSUE TITLE
feature idea: allow semi warmstart: clean all modes besides car -> could allow for faster re calibration of intercepts from an already good solution

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2024]

**Comment by wrashid** [comment]
add param beam.warmStart.clearNonCarModes=boolean
if enabled, clean all modes in plans besides car

**Comment by wrashid** [comment]
beam.replanning.cleanNonCarModesInIteration (allow for resetting in any iteration if non negative)

**Comment by JustinPihony** [comment]
Seems closed by #2082, so closing - reopen if not
