### ISSUE TITLE
why locationX and locationY fields in events file don't use same coord system? (parking and ev charging)?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2033]
![image](https://user-images.githubusercontent.com/13569531/62595698-fc62ee00-b8a4-11e9-88a3-f6171118f6fc.png)

**Comment by colinsheppard** [comment]
Should be WGS

**Comment by carloscaldas** [comment]
Fixed by the PR https://github.com/LBNL-UCB-STI/beam/pull/2049
