### ISSUE TITLE
error during loading of parking (beamville)

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2038]
23:02:28.934 WARN  b.a.i.ZonalParkingManager$ - unable to read contents of provided parking file \test\input\beamville/parking/taz-parking-default.csv, got Failed to load parking data from row with contents '1,Workplace,FlatFee,UltraFast(250, DC),2147483647,0,RideHailManager'.
java.lang.IllegalArgumentException: invalid argument for ChargingPointType: ultrafast(250, dc).

**Comment by robfitzgerald** [comment]
We changed the format of charging types from <name>(<kwh>,<current type>) to <name>(<kwh>|<current type>). Comma to pipe.

Johannes tried to update all of the files for this fix, initially introduced by Colin, but it's possible that 1) he missed one, or 2) files were re-introduced in later PRs which had the old schema.

**Comment by wrashid** [comment]
thanks @robfitzgerald - ok, can you please the files - same issue with beamville/parking/taz-parking-empty.csv
