### ISSUE TITLE
allow pointing to s3 folder for urbansim input

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2059]
![image](https://user-images.githubusercontent.com/13569531/62974545-1ab57600-bdde-11e9-9598-adbb9cfef322.png)

beam.exchange.scenario.folder should also allow s3 path besides local path

(see example warmstart, where we also have the option to download from s3)

**Comment by JustinPihony** [comment]
Resolved via #2178 and #2177
