### ISSUE TITLE
test MultinomialCustomConfigSpec ignored as getting stuck/giving errors

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#210]
beamville scenario getting stuck and giving errors for car modeChoiceParameters:

        <alternative name="car">
          <utility>
             <param name="intercept" type="INTERCEPT">-100.0</param>
             <param name="cost" type="MULTIPLIER">-100.0</param>
             <param name="time" type="MULTIPLIER">-100.0</param>
          </utility>
        </alternative>

with java.lang.IndexOutOfBoundsException: -1 	at beam.agentsim.agents.choice.mode.ModeChoiceMultinomialLogit.apply(ModeChoiceMultinomialLogit.scala:103) ~[classes/:?]

**Comment by wrashid** [comment]
with commit 34a2f12 the test is getting stuck with run time exception (therefore test still ignored):

java.lang.RuntimeException: No choice was made

**Comment by colinsheppard** [comment]
Error was from agent having no option. This occurs if agent does DRIVE_TRANSIT for the tour, but in later trips in the tour, the router only returns a CAR alternative. At this point, because we force agents to keep using their vehicle (to get it back home) this agent has no way to travel without her vehicle, so should go to error state.

**Comment by colinsheppard** [comment]
@wrashid which test, I run the test suite locally and all passed.

If exception is thrown, agent should just stop, not bring down the sim...

**Comment by wrashid** [comment]
sorry, test MultinomialCustomConfigSpec was just pushed/merged to master

**Comment by wrashid** [comment]
test MultinomialCustomConfigSpec is ignored as it gets stuck (just tried out after checking out from master)

**Comment by colinsheppard** [comment]
The MultinomialCustomConfigSpec test is now quite out of date due to the refactor that brought the MNL choice params into the config file. Closing this and will create a new task to refactor these tests...
