### ISSUE TITLE
Summary Stats too Verbose

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#2122]
In StatsFactory we create 3 kinds of summary stats that are far too detailed and make our summaryStats.csv output unusable:

* VehicleMilesTraveled
* VehicleHoursTraveled
* NumberOfVehicles

Please remove these from this output and instead we can create a different output file (CSV file in the base output directory) that would summarize all three of these in one file in **long** format (instead of wide format).

So the output could be:

summaryVehicleStats.csv

with header:

iteration,vehicleType,milesTraveled,hoursTraveled,numberOfVehicles

**Comment by JustinPihony** [comment]
Closed via #2170
