### ISSUE TITLE
do we need to integrate tollprices and part of choice directly into router?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#213]
current implementation can lead to non-optimal/wrong route choice set being returned from router.

**Comment by wrashid** [comment]
TODO: also add test for this asap.

**Comment by michaz** [comment]
Exactly. Also the reverse: turn costs. They are used by R5, but not simulated by JDEQSim, so the congestion may always be somewhere else than R5 thinks it is.
I think that may be what's currently going on. Looking into it.

**Comment by michaz** [comment]
It's getting interesting. :-)

**Comment by michaz** [comment]
Toll has been in the router for a while.
