### ISSUE TITLE
allow controlling mode choice debug output via interval

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2142]
extract from branch: production-sfbay-develop-debug-mode 

- add time tick to table

- don't output it start folder, but instead in ITERS folder (modeChoiceOut.csv)

- introduce interval

- header: person,activity,CAR_cost,CAV_cost,WALK_cost,BIKE_cost,TRANSIT_cost,RIDE_HAIL_cost,RIDE_HAIL_POOLED_cost,RIDE_HAIL_TRANSIT_cost,DRIVE_TRANSIT_cost,WALK_TRANSIT_cost,CAR_time,CAV_time,WALK_time,BIKE_time,TRANSIT_time,RIDE_HAIL_time,RIDE_HAIL_POOLED_time,RIDE_HAIL_TRANSIT_time,DRIVE_TRANSIT_time,WALK_TRANSIT_time,mode,altUtil,altProb,expMaxUtil

**Comment by carloscaldas** [comment]
No needed anymore
