### ISSUE TITLE
person enters body vehicle sometimes missing

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2184]
reproducible on beamville: 
![image](https://user-images.githubusercontent.com/13569531/65364642-d4bbb100-dbd8-11e9-894b-4bc41f45ca34.png)

**Comment by bhavyalatha26** [comment]
Hi @wrashid 
I think I figured out the issue , but I do not understand the use case here to confirm and fix it
Please take a look at the state **PassengerScheduleEmpty** being handled here
https://github.com/LBNL-UCB-STI/beam/blob/00043f58a408f453d2175c8c23e098a3881d7298/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L649
At line **[668](https://github.com/LBNL-UCB-STI/beam/blob/00043f58a408f453d2175c8c23e098a3881d7298/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L668)** the person leaves the body (example **body-2** for person with id 2) and this should eventually remove the vehicle from the list of vehicles used by the current person stored in variable `data.currentVehicle`. This is not done here.

Also at line **[681](https://github.com/LBNL-UCB-STI/beam/blob/00043f58a408f453d2175c8c23e098a3881d7298/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L681)** when the state changes to **ProcessingNextLegOrStartActivity** ( a new activity is about to start) we are resetting the current vehicle list to **["body-2"]** but we do not precede / follow it with any **PersonEntersVehicle** for "body-2"
