### ISSUE TITLE
One-way link handling

### ISSUE THREAD

**Issue by gregmacfarlane** [LBNL-UCB-STI/beam#220]
I've jumped off the [`R5MnetBuilder`](https://github.com/LBNL-UCB-STI/beam/blob/70641ab802188438a013f19df705ac00e7a886de/src/main/java/beam/router/r5/R5MnetBuilder.java) and [`OsmToMATSim`](https://github.com/LBNL-UCB-STI/beam/blob/59b15b36f72a192dab2a7ad687c496d7b8d09fed/src/main/java/beam/router/r5/OsmToMATSim.java) classes so that I can build an OSM to MATSim converter that relies on Conveyal's routing software (which I trust more than the original MATSim stuff at the moment). I've basically been following the scala code, with a couple of my own modifications

```java
    private static void loadNetwork(File netDir, File osmFile, File netFile,
                                    String crs)
            throws Exception {
        log.info("Reading R5 network from " + osmFile);
        TransportNetwork transportNetwork = TransportNetwork.fromDirectory(
                netDir.getAbsoluteFile());
        File graphFile = Paths.get(netDir.toString(), "network.dat").toFile();
        transportNetwork.write(graphFile);
        transportNetwork = TransportNetwork.read(graphFile); // have to reload because memory dumps on write

        log.info("Create MATSim network from R5 network");
        R5MnetBuilder netBuilder = new R5MnetBuilder(
                transportNetwork, "osm.mapdb", crs);
        netBuilder.buildMNet();
        Network network = netBuilder.getNetwork();
        NetworkCleaner networkCleaner = new NetworkCleaner();
        networkCleaner.run(network);
        NetUtils.addTurnaroundLinks(network);
        log.info("MATSim network created");
        new NetworkWriter(network).write(netFile.getAbsolutePath());
        log.info("MATSim network written to " + netFile);
    }
```

Anyways, the resulting network has all links as bi-directional, whether or not the OSM field has a `one-way` tag on it. This includes both directions of motorways, etc. I went looking for where the reverse directions were being appended, and came across [this note](https://github.com/LBNL-UCB-STI/beam/blob/70641ab802188438a013f19df705ac00e7a886de/src/main/java/beam/router/r5/R5MnetBuilder.java#L65-L66):

```java
            // TODO - eventually, we should pass each R5 link to OsmToMATSim and do the two-way handling there.
            // Check if we have already seen this OSM way. Skip if we have.
```

In the [MATSim link creator method](https://github.com/LBNL-UCB-STI/beam/blob/70641ab802188438a013f19df705ac00e7a886de/src/main/java/beam/router/r5/OsmToMATSim.java#L120), I see where the `one-way` field gets handled, but I don't see that this value is ever used to create the reverse direction (or not). I also confirmed that the most recent version of the [`sf-light`](https://github.com/LBNL-UCB-STI/beam/blob/70641ab802188438a013f19df705ac00e7a886de/test/input/sf-light/physsim-network.xml) network has duplicated reverse links for all four of the links on the Golden Gate Bridge, which should probably be one-way.

**Comment by gregmacfarlane** [comment]
As a note, I don't believe that this also applies to the R5 network, because one-way routing seems to work correctly in my local server instance, but I can't be entirely sure.

**Comment by michaz** [comment]
Thank you, yes, you're completely right, of course.

There used to be code there that took a (pair of) uni-directional R5 links, matched them with a (bi-directional) OSM way, and converted all of that into a (pair of) uni-directional MATSim links again. (Unless the street was one-way.)

At some point, we were _missing_ links which should have been there, so I somewhat aggressively simplified that. Apparently, I did not rescue or fix the correct treatment of one-way streets while doing so.

The reason we haven't been paying much attention to that is that R5 works, and our agents only do what R5 tells them, so nobody is using those not-supposed-to-be-existing links.

If we had more autonomous agents, we would have to fix this, probably by looking at R5's link attributes and believing them. (Rather than _also_ looking at the OSM tags again and hoping that what R5 thinks is a one-way street and what we think is a one-way street coincide.)

**Comment by gregmacfarlane** [comment]
I guess what I don't understand is how the methods create *two* links for every edge in R5. Is it simply that R5 has both directions in its structure but only uses one? 

What do you mean when you say "believe" R5's attributes? If you are using R5 for routing, then presumably you believe at least the one-way attribute, right?

Just trying to understand, so I can see if a workaround is within my ability before y'all get around to it.

**Comment by michaz** [comment]
R5 and MATSim both have directed links: One non-one-way road segment gets two links.
We create one MATSim link for every R5 link. (At least that's what I think and what the code looks like to me..)
By believing in R5's attributes I meant looking at the flags which are probably there which say whether a directional link is accessible or not, and then creating a MATSim link or not. We don't do that currently, but create one MATSim link for every R5 link.
