### ISSUE TITLE
25k sflight extreme performance degradation - why?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2218]
the runtime for sflight 25k goes from 5min per iteration to 120min per iteration, if we increase ridehail_intercept to 100.0 (with beam.agentsim.agents.rideHail.allocationManager.name="POOLING_ALONSO_MORA")

This is worry some, as even a simulation of 300k+ agents (smart baseline) takes less time per iteration.

**Comment by wrashid** [comment]
something strange: 5% rh fleet seems to be enough to cover all demand (almost 100% rh use)

**Comment by REASY** [comment]
Here is what I see in the logs:
```
14:40:23.584 INFO  b.a.scheduler.BeamAgentScheduler - Hour 7.5 completed. 6.9(GB)
14:40:27.889 WARN  beam.agentsim.agents.PersonAgent - [32] didn't get nextActivity, PersonAgent:438
14:42:03.957 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-045100-2014000616402-0-6799180
[jfr][INFO ][2618.970] Starting recording [id=2, name=Clone of mem_ex, destination=recording.jfr, start=Sat Oct 12 14:36:12 ICT 2019, duration=8400000ms]
[jfr][INFO ][2629.511] Copied 67235811 bytes (before compression) to recording.jfr in 5 chunks
[jfr][INFO ][2629.511] Stopped recording [id=2, name=Clone of mem_ex, destination=recording.jfr, start=Sat Oct 12 14:36:12 ICT 2019, end=Sat Oct 12 15:19:54 ICT 2019, duration=8400000ms]
```
In my case, after the message `14:42:03.957 ERROR b.a.agents.ridehail.RideHailManager - Not found in waitingToReposition: rideHailVehicle-045100-2014000616402-0-6799180` nothing has happened for 40 minutes. The following screenshot shows there are no activities in any of _our threads_:
![image](https://user-images.githubusercontent.com/5107562/66697994-7c259280-ed04-11e9-8606-ccae400cf759.png)

This looks for me like a stuckness.

**Comment by estandiaa-marain** [comment]
Are you using POOLING_ALONSO_MORA? Because the simulation does not complete
with DEFAULT_MANAGER (see https://github.com/LBNL-UCB-STI/beam/issues/2206).

**Comment by REASY** [comment]
@estandiaa-marain good catch, thanks. I used `DEFAULT_MANAGER `, let me change it and try again

**Comment by REASY** [comment]
@estandiaa-marain I've proposed PR to solve performance degradation https://github.com/LBNL-UCB-STI/beam/pull/2219
