### ISSUE TITLE
inm / BEAM to MATSim visualizations images

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2274]
Put somewhere png images of visualizations. 
Each visualization has its own script and corresponding png image (or group of images).

corresponding PR with visualization scripts is https://github.com/LBNL-UCB-STI/beam/pull/2277

**Comment by irishwithaxe** [comment]
![visualization3](https://user-images.githubusercontent.com/5393513/68588696-368eed80-049b-11ea-94d5-479650f43152.png)
![visualization4](https://user-images.githubusercontent.com/5393513/68588697-37278400-049b-11ea-82f4-3daddcdf6f92.png)
![visualization5](https://user-images.githubusercontent.com/5393513/68588699-37c01a80-049b-11ea-8848-16360c45acdb.png)
![visualization6](https://user-images.githubusercontent.com/5393513/68588701-37c01a80-049b-11ea-80da-e468f802e7ed.png)
![visualization9](https://user-images.githubusercontent.com/5393513/68588702-3858b100-049b-11ea-95f4-f82751d48009.png)
![visualization11](https://user-images.githubusercontent.com/5393513/68588704-3858b100-049b-11ea-9347-31ccc9fad97f.png)
![visualization12](https://user-images.githubusercontent.com/5393513/68588705-3858b100-049b-11ea-9648-373b9a28d2b7.png)
![visualization20](https://user-images.githubusercontent.com/5393513/68588706-38f14780-049b-11ea-822a-c489f59e3bbf.png)
![visualization21](https://user-images.githubusercontent.com/5393513/68588707-38f14780-049b-11ea-89e6-d9d162fd403a.png)
![visualization22](https://user-images.githubusercontent.com/5393513/68588708-38f14780-049b-11ea-9b43-8b7d87fd8dd9.png)
![visualization23](https://user-images.githubusercontent.com/5393513/68588709-3989de00-049b-11ea-91bb-bccbac248776.png)
![visualization24](https://user-images.githubusercontent.com/5393513/68588711-3989de00-049b-11ea-996c-38aac93c30b6.png)
![visualization33](https://user-images.githubusercontent.com/5393513/68588712-3a227480-049b-11ea-808f-8777c6582735.png)
![visualization34](https://user-images.githubusercontent.com/5393513/68588713-3a227480-049b-11ea-80e0-597054303251.png)
![visualization35](https://user-images.githubusercontent.com/5393513/68588714-3a227480-049b-11ea-9e02-185508d4cab2.png)
