### ISSUE TITLE
create csv for surge price level bins with taz info

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#228]

**Comment by wrashid** [comment]
csv format: tazId, dataType (revenue | priceLevel), bin_1, bin_2,   ...

**Comment by mr-asif-nor** [comment]
currentIterationRevenue will be in the bins for the datatype = revenue
and
currentIterationSurgePriceLevel will be in the bins for the datatype=pricelevel

for this graph.
