### ISSUE TITLE
Walk mode: PersonEntersVehicle and PersonLeavesVehicle are not matching

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2284]
I got the result of the 15-th iteration of https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/sfbay/sfbay-smart-b-ht-2040__2019-10-28_20-17-54
Most probably it is easy to reproduce on beamville/sf-light-1k
Here is breakdown by event type for the walk (vehicle name would contain `body-`)
![image](https://user-images.githubusercontent.com/5107562/69364906-d29fcc80-0cc5-11ea-83fb-c1d293b455a0.png)

**Comment by JustinPihony** [comment]
What was the resolution of this?

**Comment by REASY** [comment]
@JustinPihony it was resolved by https://github.com/LBNL-UCB-STI/beam/pull/2230
