### ISSUE TITLE
Represent the travel time graphically for PR 2319

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2320]
Add the functionality to the PR https://github.com/LBNL-UCB-STI/beam/pull/2319 to plot average car travel time (the graph averageCarTravelTimes.png, an example: https://beam-outputs.s3.amazonaws.com/output/sfbay/sfbay-smart-base__2019-12-05_19-48-26/averageCarTravelTimes.png), but using the data which is calculated in the PR, lines: https://github.com/LBNL-UCB-STI/beam/pull/2319/files#diff-6c7ef19e8c5affdd8d47397fcac78123R93-R101.
~~Let's call the new graph name as averageCarTravelTimeFromPathTraversal.png~~
Updated after discussion on Standup: because PathTraversalEvent is kind of ground truth in our simulation and averageCarTravelTimes is on of the key metrics, so let's replace the old graph by this one

**Comment by bhavyalatha26** [comment]
Noted the updates @REASY ! :+1:  

Should we be replacing only the root level graph ? Because I see the other class also generates iteration level graphs

Here is the [commit](https://github.com/LBNL-UCB-STI/beam/commit/fa67eb8d1911987e8f2700da9d39fae2ebc70f20) for the changes made . Please review 

However I have one question here :

**There are two kinds of stats being computed here - SingleRideStat and IterationCarRideStats . Which one should be used for the graph ? I assume IterationCarRideStats , please correct me if I am wrong**

**Comment by REASY** [comment]
@bhavyalatha26 
> Should we be replacing only the root level graph ? Because I see the other class also generates iteration level graphs

Yes, we should update all graphs (root and iterations), but both replacements need to be only for CAR.

> There are two kinds of stats being computed here - SingleRideStat and IterationCarRideStats . Which one should be used for the graph ? I assume IterationCarRideStats , please correct me if I am wrong

Yes, you did it correct, we need to use `IterationCarRideStats`

**Comment by bhavyalatha26** [comment]
@REASY  Looking at the [PersonTravelTimeAnalysis](https://github.com/LBNL-UCB-STI/beam/blob/fa67eb8d1911987e8f2700da9d39fae2ebc70f20/src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java#L129) the iteration level graphs are drawn for 
**hour of the day** vs **average travel time during that hour**

For this the stats computed were : 
`average(list(travel times)) grouped by hour of departure event` ,
  where **travel time = arrival - previous departure**

Should we follow the same stats calculation here or should we make use of `PathTraversalEvents` here ? If PTE to be used , how should the stats be calculated ? 

I tried looking at : **hour(pte.time) vs avg(pte.linkTravelTime)**

**Comment by REASY** [comment]
@bhavyalatha26 for both iteration and root level graphs we should start using PTEs, no need to use old logic when we compute the travel time as a difference in times between `PersonDeptartureEvent` and `PersonArrivalEvent`.

I don't have events in my hands, but if I'm not mistaken `PathTraversalEvent.time` is the same as `PathTraversalEvent.departureTime`. But let's forget all of this and compute it in the following way (almost like you proposed, but use `departureTime` to remove ambiguity:
`list(SingleRideStat.travelTime) grouped by hour(pte.departureTime)`

**Comment by bhavyalatha26** [comment]
@REASY Made the changes and plotted the graph using `SingleRideStats` from PTEs.
Here is the [**commit**]( https://github.com/LBNL-UCB-STI/beam/commit/5b7fac792aaeb5faca9bd2a01d05ca182bbb418e) for the same.

**Comment by bhavyalatha26** [comment]
@REASY made the final changes and assigned you the [PR#2321](https://github.com/LBNL-UCB-STI/beam/pull/2331)

I have few questions before we close this.

1. The [PersonTravelTimeAnalysis](https://github.com/LBNL-UCB-STI/beam/blob/65ef935cfe8f97a0476ef5d7b5d807a78f6c9d3d/src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java#L28) class also generates **csv at root level** for car travel time stats , don't we need csv generation here ?
2. May be an unrelated question , but just wanted to learn what is a [**mixed_mode**](https://github.com/LBNL-UCB-STI/beam/blob/65ef935cfe8f97a0476ef5d7b5d807a78f6c9d3d/src/main/java/beam/analysis/plots/PersonTravelTimeAnalysis.java#L35) ? Does it have anything to cross check for car mode ?

**Comment by REASY** [comment]
@bhavyalatha26, regarding the first question. Yes, we do not need root level CSV file anymore. 
Regarding the second question, thanks for raising concern, but I don't think we need it, but let's wait for @wrashid comments about that

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/issues/2320
