### ISSUE TITLE
What causes the travel time from arrival/departure to be differ than from PTEs

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2321]
Travel time computed differently:
![image](https://user-images.githubusercontent.com/5107562/71838362-3867dc80-30eb-11ea-8fc2-0687101df4b9.png)

FromDepartureArrivalEvents it is the current one, graph [averageCarTravelTimes.png](http://ec2-3-133-11-127.us-east-2.compute.amazonaws.com:8000/output/sfbay/sfbay-smart-base__2020-01-05_14-54-51/averageCarTravelTimes.png), input data for the graph is from CSV file [averageCarTravelTimes.csv](http://ec2-3-133-11-127.us-east-2.compute.amazonaws.com:8000/output/sfbay/sfbay-smart-base__2020-01-05_14-54-51/averageCarTravelTimes.csv) 

FromPathTraversalEvents_IncludeParking is the new way to compute non-ridehail cars' travel time using PathTraversalEvents, the data is saved to CSV file [CarTravelTime.csv](http://ec2-3-133-11-127.us-east-2.compute.amazonaws.com:8000/output/sfbay/sfbay-smart-base__2020-01-05_14-54-51/CarTravelTime.csv). The way how it is computed is in the PR: https://github.com/LBNL-UCB-STI/beam/pull/2319

**Comment by JustinPihony** [comment]
To verify, #2319 does not resolve, but instead helps with this issue, right?
