### ISSUE TITLE
Create Plans from CTPP data

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2347]
**Create OD matrix for whole US from CTPP data**

Download data for all states from: XXXX

from: <StateCode>_2012thru2016_A302103.csv select sum(EST) group by GEOID where GEOID startswith(“C56”)

=> output: one large table with all TAZ-to-TAZ (home->work) counts (OD Database US)

(@REASY please refine, as discussed)

**Create TAZ DB**
Download US wide TAZ shapefiles
Create DB with TAZ codes consistent with CTPP, e.g. C5600US4800100003 (4354821300003410) resp.
State,city, … , TAZ, Lat, long, Area

**Filter OD Pairs for Scenario** 
Inputs: OD DB USA
Inputs: TAZ DB 
Inputs: osm.pbf

=> select relevant TAZ based on area covered by osm => select corresponding rows from OD DB USA => scenario OD pairs

**Create Plans from OD**
-> input: OD for scenario
-> TAZ DB with coordinates
	   Shape with at least relevant area (ideally USA wide or point to folder with all US TAZ shape files) or TAZ DB (slightly less precise)
-> for each TAZ-to-TAZ pair in OD, create a person, add one home activity in fromTAZ and a work activity in toTAZ. -> add at the end same home activity
-> end of first home activity:
-> work duration: not clear yet, probably from NHTS

**Comment by REASY** [comment]
Second task `Create TAZ DB` => [Build a database from Census Tract State-based Shapefile files ](https://github.com/LBNL-UCB-STI/beam/issues/2350)

**Comment by wrashid** [comment]
Forth task [Create Plans from OD](https://github.com/LBNL-UCB-STI/beam/issues/2351)

**Comment by wrashid** [comment]
Forth task [Activity endTime/duration part](https://github.com/LBNL-UCB-STI/beam/issues/2353)

**Comment by REASY** [comment]
Read household and population information => https://github.com/LBNL-UCB-STI/beam/issues/2356

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2471
