### ISSUE TITLE
Race condition in BeamVehicle

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2348]
The way how https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/vehicles/BeamVehicle.scala#L53-L71 is implemented is not thread safe. It might be related to the problem which @JustinPihony  faced. Beam uses Actor System to simulate agents' behavior. With default configuration for Akka you have no control on which thread the receive method of actor will be executed (no pinning to particular thread). This leads to a problem that the state of BeamVehicle is changed from multiple places and there is no guarantee that the changes of the fields will be propagated to all threads (remember we are mutating the same instance of BeamVehicle from multiple places). There can be multiple ways to solve it:
1) Mark all fields which are mutated from different places as volatile. Assuming that the logic on top of the mutation is correct this should be enough. Basically we want the changes made by one thread to shared data to be visible to other threads.
2) Use atomic data structures: AtomicBoolean, AtomicReference
3) Use locks (might hurt performance due to the possibly thread contention)
4) Refactor that code how BeamVehicle is working: make it as actor

I've added some logs to `BeamVehicle` to show what happens for one particular vehicle id:
```
17:58:55.309 [ClusterSystem-akka.actor.default-dispatcher-17] INFO  b.a.agents.vehicles.BeamVehicle - [1] BeamVehicle[22-0], Thread[57] called useParkingStall
18:00:11.246 [ClusterSystem-akka.actor.default-dispatcher-57] INFO  b.a.agents.vehicles.BeamVehicle - [2] BeamVehicle[22-0], Thread[111] called unsetParkingStall
18:00:22.985 [ClusterSystem-akka.actor.default-dispatcher-27] INFO  b.a.agents.vehicles.BeamVehicle - [4] BeamVehicle[22-0], Thread[67] called unsetParkingStall
18:02:44.744 [ClusterSystem-akka.actor.default-dispatcher-48] INFO  b.a.agents.vehicles.BeamVehicle - [1] BeamVehicle[22-0], Thread[88] called useParkingStall
18:03:51.309 [ClusterSystem-akka.actor.default-dispatcher-20] INFO  b.a.agents.vehicles.BeamVehicle - [2] BeamVehicle[22-0], Thread[60] called unsetParkingStall
18:03:56.811 [ClusterSystem-akka.actor.default-dispatcher-27] INFO  b.a.agents.vehicles.BeamVehicle - [4] BeamVehicle[22-0], Thread[67] called unsetParkingStall
18:06:38.383 [ClusterSystem-akka.actor.default-dispatcher-66] INFO  b.a.agents.vehicles.BeamVehicle - [1] BeamVehicle[22-0], Thread[137] called useParkingStall
18:06:43.908 [ClusterSystem-akka.actor.default-dispatcher-14] INFO  b.a.agents.vehicles.BeamVehicle - [2] BeamVehicle[22-0], Thread[54] called unsetParkingStall
18:06:49.808 [ClusterSystem-akka.actor.default-dispatcher-66] INFO  b.a.agents.vehicles.BeamVehicle - [4] BeamVehicle[22-0], Thread[137] called unsetParkingStall
18:09:32.711 [ClusterSystem-akka.actor.default-dispatcher-88] INFO  b.a.agents.vehicles.BeamVehicle - [1] BeamVehicle[22-0], Thread[188] called useParkingStall
18:09:39.145 [ClusterSystem-akka.actor.default-dispatcher-23] INFO  b.a.agents.vehicles.BeamVehicle - [2] BeamVehicle[22-0], Thread[63] called unsetParkingStall
18:09:44.561 [ClusterSystem-akka.actor.default-dispatcher-83] INFO  b.a.agents.vehicles.BeamVehicle - [4] BeamVehicle[22-0], Thread[183] called unsetParkingStall
18:11:28.305 [ClusterSystem-akka.actor.default-dispatcher-63] INFO  b.a.agents.vehicles.BeamVehicle - [1] BeamVehicle[22-0], Thread[135] called useParkingStall
18:12:37.360 [ClusterSystem-akka.actor.default-dispatcher-97] INFO  b.a.agents.vehicles.BeamVehicle - [2] BeamVehicle[22-0], Thread[211] called unsetParkingStall


```

**Comment by SHaaD94** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2402

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2402
