### ISSUE TITLE
Build a database from Census Tract State-based Shapefile files

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2350]
We need to use [US Cenus Bureau](https://www.census.gov/) data to build a database of USA. We're interested in [Census Tract State-based Shapefile Record Layout](https://www2.census.gov/geo/pdfs/maps-data/data/tiger/tgrshp2019/TGRSHP2019_TechDoc.pdf):

![image](https://user-images.githubusercontent.com/5107562/73610507-a03a1600-460a-11ea-8740-ebcb3a8570b2.png)

Terms dictionary:

- FIPS: Federal Information Processing Standards
- [Census tracts](https://transition.fcc.gov/form477/Geo/more_about_census_tracts.pdf): Census tracts are geographic entities within counties (or the statistical equivalent of counties). The entire area of a county is covered by census tracts, just as the entire area of a state is covered by counties and county equivalents.

Useful links: 

- [Concept & Definitions](https://www.census.gov/programs-surveys/acs/geography-acs/concepts-definitions.html)
- [Actual census tract data for 2019](https://www2.census.gov/geo/tiger/TIGER2019/TRACT/) 

The database should contains the following fields:
- state_fp: State FIPS code
- county_fp: County FIPS code
- tract_code: Census tract code
- geo_id: Census tract identifier; a concatenation of state FIPS code, county FIPS code, and census tract code
- land_area: Land area
- water_area: Water area
- multi_polygon: Multi-polygon of that census tract

We need to have a way to query the data in at least two ways:
- Provide bounding box and get back all the records which are in that bounding box
- Provide state and county FIPS code and get back all the records which belongs to that state and county

There can be multiple ways of implementing this database, some of them:
 
- Use PostgreSQL with [PostGIS](https://postgis.net/) which has capabilities for geo spatial queries
- Use Elasticsearch with [geo queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-queries.html)

**Comment by SHaaD94** [comment]
done in https://github.com/LBNL-UCB-STI/beam/pull/2357

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2357
