### ISSUE TITLE
Create Plans from OD

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2351]
-> input: OD for scenario
-> TAZ DB with coordinates
Shape with at least relevant area (ideally USA wide or point to folder with all US TAZ shape files) or TAZ DB (slightly less precise)
-> for each TAZ-to-TAZ pair in OD, create a person, add one home activity in fromTAZ and a work activity in toTAZ. -> add at the end same home activity
-> end of first home activity:
-> work duration: not clear yet, probably from NHS

=> filtered TAZ-to-TAZ frequency (originTAZ and destTAZ)

=> getScenarioGenerator(osmPath,dbConnection) with helper methods:
- sampleHomeToWorkTAZ(): (TAZ,TAZ)
- getTAZs() -> TAZ objects with id, coord
- available helper method sampleFromTAZ(String tazId) -> Coord
- drawFirstHomeActEndTime() -> time in seconds from midnight
- drawWorkActDuration(double firstHomeActEndTime): duration of work activity in seconds
- drawHousehold() -> householdSize, income, number vehicles
      -> vehicles per household on TAZ level (e.g. 1.3veh/hh)

=> household.csv => Do we have household and number of vehicle data in CTPP? => A1122106 (create task: in a previous step we also get this into our db).
    
- => householdIncome? => A103204 or something similar
- => vehicles? => ??????

=> taz-centers.csv

**Comment by REASY** [comment]
The final way of creating scenario is quite different that how it is described here. 
https://github.com/LBNL-UCB-STI/beam/pull/2471
