### ISSUE TITLE
create joint probability matrix for home activity endTime and work duration from NHTS

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2353]
expected output format:
![image](https://user-images.githubusercontent.com/13569531/73957803-892a4b00-48cc-11ea-9b27-9b036d21b506.png)

**Comment by colinsheppard** [comment]
can we please make this long format instead of wide.... that makes it much simpler to add new dimensions (e.g. if we want this to cary by space or by demographics we just add a new column, which we can't do if this is a matrix)

**Comment by JustinPihony** [comment]
Closed via #2361 and #2522
