### ISSUE TITLE
allow upscale xml population beyond 100% (agentSampleSizeAsFractionOfPopulation)

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2354]
-> also double check for urbansim, if it really works

**Comment by REASY** [comment]
The run on [production-sfbay-develop](https://github.com/LBNL-UCB-STI/beam/tree/production-sfbay-develop)
- commit 6d4b2c2defdbdd015a6c52d48bc5c5dd355ff4eb
- [agentSampleSizeAsFractionOfPopulation=2.47](https://github.com/LBNL-UCB-STI/beam/commit/6d4b2c2defdbdd015a6c52d48bc5c5dd355ff4eb#diff-5e9edde99047079754db4ec59fecb326R13-R14)
- [output folder](https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/sfbay/sfbay-smart-base-2.47_population__2020-03-09_18-39-42_hot)  

UrbanSimLoader didn't create more households and people than available in the CSV files. I can see only downscaling code, but not upscaling https://github.com/LBNL-UCB-STI/beam/blob/7e2c0cdacf1f6a98223cfa64417aaccfacfac38d/src/main/scala/beam/sim/BeamHelper.scala#L713
