### ISSUE TITLE
Return all TAZs from OSM map

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2358]
We need one single input regarding geo locations and let it be OSM map. It is already required for the simulation. We need to connect TAZ DB with OSM map. There should be a service which received `DataRepository ` and path to OSM map and can give back the list of TAZs inside that OSM map.

**Comment by SHaaD94** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2357

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2357
