### ISSUE TITLE
Given TAZ id and N, generate N coordinates inside that TAZ polygon

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2359]

**Comment by SHaaD94** [comment]
Done in https://github.com/LBNL-UCB-STI/beam/pull/2357

**Comment by JustinPihony** [comment]
You tagged 2357 as fixing 2350, so is this really a duplicate then? Or wrong PR noted @SHaaD94 ?

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2357
