### ISSUE TITLE
remove beam.agentsim.startTime from beamconfig/template

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2364]

**Comment by bhavyalatha26** [comment]
Should we remove in all scenario config files as well @wrashid ? If yes , then there a reference to this `beam.agentsim.startTime` in **matsim.conf** , should that be removed as well ?

**Comment by wrashid** [comment]
we can set the startTime in matsim.conf to "00:00:00" and remove beam.agentsim.startTime from everywhere
