### ISSUE TITLE
why beamville throws exception with beam.agentsim.endTime = "15:00:00"?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2365]

**Comment by bhavyalatha26** [comment]
An update : Happens for all cases with `endTime < 24:00:00`

**Comment by wrashid** [comment]
thanks for the update @bhavyalatha26 - let us try to find out why it is happening

**Comment by bhavyalatha26** [comment]
This looks more like a design issue. 
The current exception occurs at this [line of code](https://github.com/LBNL-UCB-STI/beam/blob/d892830562650c8208b3b444419f7b6a8ba3a8d4/src/main/scala/beam/replanning/ReplanningUtil.scala#L104) as it makes an assumption that size of `plan elements` is just 1 greater than the size of `trips`. So for all those cases in which the difference of lengths > 1 , it runs into an overflow exception.
