### ISSUE TITLE
create graph for absError(mode) and ridehail/car ratio for jdeqsim relaxation experiments

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2366]

**Comment by rorschach77733** [comment]
![referenceRealizedModeChoice](https://user-images.githubusercontent.com/48454797/74274721-dfefb480-4d12-11ea-9045-41b6e86d598e.png)

**Comment by rorschach77733** [comment]
![referenceRealizedModeChoice](https://user-images.githubusercontent.com/48454797/74275101-9b184d80-4d13-11ea-9937-c18af20a0f69.png)
