### ISSUE TITLE
implement JointDistribution class

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2367]
**methods**

- read(path) -> is able to read any kind of csv, with intial columns containing categories, last column containing probability
- sample(List of variables and their values sets/ranges, int sampleSize) - uses: getProbability(List of variables and their value sets/ranges) -> not all columns need to be provided 

notes:
- we could pass column types as input to constructor
- for numeric values we should be able to use beam.sim.common.Range in queries
- could use key value map as input to sample(...)

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2388
