### ISSUE TITLE
create actor which collects charging events and communicates them externally

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2373]
-> allow turning actor off, if not needed from config (default setting)
-> allow to set communication interval from config (actor will schedule messages to itself through scheduler for that interval).
-> the actor needs to collect all ev charging related events since last external communication, e.g. plugin,plugout,start refuel session,etc.

Note: as the actor receives messages from multiple actors, e.g. scheduler, vehicles, etc., we need to ensure somehow, that no more messages are coming from other actors. solution to this issue is that we run the model in 1 sec window  mode, so maximum impreciseness is that.

**Comment by bhavyalatha26** [comment]
@wrashid added the actor and the required settings in config.
Please review the [commit](https://github.com/LBNL-UCB-STI/beam/commit/a82f9bcc0e62fa54d34e0128e36940ffdae60414)

Pending : Adding support to send event triggers to this actors whenever the charging related events are created.
