### ISSUE TITLE
Replace io.github.oliviercailloux:google-or-tools by our wrapper

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2379]
Our [wrapper is ready](https://github.com/LBNL-UCB-STI/beam/issues/2378), so we can replace `io.github.oliviercailloux:google-or-tools:6.7.2` https://github.com/LBNL-UCB-STI/beam/blob/32b0dddbdcac676b74603267340c4abf85790415/build.gradle#L228

**Comment by SHaaD94** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2377

**Comment by haitamlaarabi** [comment]
@REASY @SHaaD94 
what about leaving 
` compile("io.github.oliviercailloux:google-or-tools:6.7.2") `
so that in the case when no library is available for an OS/distribution, the or-tools classes will still be recognized by scala avoiding therefore any compilation or runtime errors.

**Comment by SHaaD94** [comment]
> @REASY @SHaaD94
> what about leaving
> `compile("io.github.oliviercailloux:google-or-tools:6.7.2")`
> so that in the case when no library is available for an OS/distribution, the or-tools classes will still be recognized by scala avoiding therefore any compilation or runtime errors.

No need for that, because new wrapper also contains or-tools java classes
