### ISSUE TITLE
Configurable ride hail matching algorithm for PoolingAlonsoMora

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2380]
Currently matching algorithm is hardcoded
https://github.com/LBNL-UCB-STI/beam/blob/32b0dddbdcac676b74603267340c4abf85790415/src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala#L182-L187
but we need to make it configurable. For that we should:
- Add parameter `beam.agentsim.agents.rideHail.allocationManager.alonsoMora.matchingAlgorithm` to https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/resources/beam-template.conf
- Run `./gradlew generateConfig` to generate new [BeamConfig.scala](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/sim/config/BeamConfig.scala#L2) from template
- Update https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/ridehail/allocation/PoolingAlonsoMora.scala#L182-L187 to start respecting new parameter

Currently there are 3 algorithms available:
- [VehicleCentricMatchingForRideHail](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/ridehail/VehicleCentricMatchingForRideHail.scala#L23)
- [AlonsoMoraPoolingAlgForRideHail](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/ridehail/AlonsoMoraPoolingAlgForRideHail.scala#L26)
- [AsyncAlonsoMoraAlgForRideHail](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/ridehail/AsyncAlonsoMoraAlgForRideHail.scala)

Please, make sure https://github.com/LBNL-UCB-STI/beam/issues/2379 is solved first

**Comment by haitamlaarabi** [comment]
Great,
I would just change the parameter name to
beam.agentsim.agents.rideHail.allocationManager.matchingAlgorithm
thanks @REASY

**Comment by SHaaD94** [comment]
> Great,
> I would change the parameter name to
> beam.agentsim.agents.rideHail.allocationManager.matchingAlgorithm
> thanks @REASY

I would agree with @REASY at this point, because we are configuration algo only for alonsoMora

**Comment by SHaaD94** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2386

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2386
