### ISSUE TITLE
EventsAccumulator is not calling itself

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#2389]
+ EventsAccumulator needs to call itself every **x** seconds, with **x** referring to:
`beam.agentsim.collectEventsIntervalInSeconds`
+ EventsAccumulatorSpec to be implemented as Test class of the proper functioning of EventsAccumulator

**Comment by wrashid** [comment]
please also remove following two lines from beam.conf (these should come from template already):
beam.agentsim.collectEvents=false
beam.agentsim.collectEventsIntervalInSeconds=300

**Comment by bhavyalatha26** [comment]
Is the actor enabled @haitamlaarabi ?
`beam.agentsim.collectEvents=true`
