### ISSUE TITLE
Is routing framework scalable with od?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2392]
for CH and CCH? 
E.g. try 100k, 500k, 1M,2M,5M,10M.

can we also do tests with production network?

https://github.com/vbuchhold/routing-framework

**Comment by kirillm-nor** [comment]
https://docs.google.com/spreadsheets/d/1qHOxLwqfuehZ5mCGX6rWOZV6KHZSX4ZK7nGs79YFBE0/edit?usp=sharing

**Comment by kirillm-nor** [comment]
For 10M CCH got `AssignTraffic: /home/ubuntu/routing-framework/Algorithms/CCH/CCHMetric.h:163: CH CCHMetric::buildMinimumWeightedCH(): Assertion `!noTriangleFound' failed.`
For 10M CH got `AssignTraffic: /home/ubuntu/routing-framework/Algorithms/Dijkstra/BiDijkstra.h:114: std::vector<int> BiDijkstra<DijkstraT, StoppingCriterionT>::getEdgePathToMeetingVertex(int) [with DijkstraT = Dijkstra<Graph<VertexAttrs<>, EdgeAttrs<TraversalCostAttribute, UnpackingInfoAttribute>, false>, TraversalCostAttribute, StampedDistanceLabelContainer, SimdLabelSet<5, ParentInfo::FULL_PARENT_INFO>, AddressableKHeap<4>, CHQuery<StampedDistanceLabelContainer, SimdLabelSet<5, ParentInfo::FULL_PARENT_INFO>, AddressableKHeap<4>, true>::CHQueryPruningCriterion>; StoppingCriterionT = CHQuery<StampedDistanceLabelContainer, SimdLabelSet<5, ParentInfo::FULL_PARENT_INFO>, AddressableKHeap<4>, true>::CHQueryStoppingCriterion]: Assertion `tentativeDistances[i] != INFTY' failed.`
