### ISSUE TITLE
Austin: Produce speeds for only Austin area for CAR

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2421]
Get the results from previous results for the Austin (PathTraversalEvents) and calculate speeds only for **Austin** area:

Austin area can be represented it two ways:

- As a polygon
- As a circle with radius

Link to to output: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/sf-light/austin-prod-200k-cacc-enabled-flowCap0.08-with-skims__2020-03-17_17-30-35_fep

`PathTraversalEvents`  are stored in `#ITER_NUM#.events.csv.gz`. It's not written on every iteration because it's takes a lot of space. An interval is controlled by parameter `beam.outputs.writeEventsInterval`. In most cases you need to get the file from the latest iterations because there the network should be relaxed.

**Comment by wrashid** [comment]
add following config parameters

beam.calibration.studyArea.enableSpeedsGraph="boolean | false"
beam.calibration.studyArea.lat=
beam.calibration.studyArea.lon=
beam.calibration.studyArea.radius=

**Comment by REASY** [comment]
Implemented in e94d835bac679f833604f1a5db458d024925f90e

**Comment by REASY** [comment]
Add another way to describe the area as bounding box

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2471
