### ISSUE TITLE
Calibration: Beam travel times with Google maps

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2426]
Python script should be under `src\main\python\calibration`

Write Python script which reads `*.personal.CarRideStats.csv.gz` file and produces CSV which contains link to the Google map + all information from original ride.
Link to google map should be constructed in the following way: `s"https://www.google.com/maps/dir/${start_y}%09${start_x}/${end_y}%09${end_x}"`. When you follow that link, you will be able to see an estimation of travel time from Google, for example https://www.google.com/maps/dir/37.79843289%09-122.4323952/37.7545348908167%09-122.4063942:
![image](https://user-images.githubusercontent.com/5107562/77193016-21446280-6b10-11ea-954c-07650acb5fb3.png)

Input parameters for the script:

1. Sample size - the number of rides which we want to sample, chosen randomly. Random seed should be also provided to make it reproducible.
2. Filter for traveled distance as a range in meters
3. Filter for the departure time as a range in secods
4. Filter of interested areas where the ride should happen as a bounding box. It can be applied for departure location, arrival location or for both of them

**Comment by carloscaldas** [comment]
Implemented by https://github.com/LBNL-UCB-STI/beam/pull/2438
