### ISSUE TITLE
Gradle run should respect instance ram

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2440]
Currently you can set anything in the parameter `MAXRAM` and it will start run with that param. In case if machine has no enough RAM, it will eventually fail. Let's add some validation before actual run of AWS instance to make sure the provided param within the range.

**Comment by nikolayilyin** [comment]
I suggest to not just validate but set amount of memory by default for specified instance type with the ability to specify it manually if necessary.
