### ISSUE TITLE
Speeds calculation during PhysSim

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2443]
We have a way to compute travel time during PhysSim, it is implemented as event handler, [CarTravelTimeHandler](https://github.com/LBNL-UCB-STI/beam/pull/2403/files#diff-ec62cc86d06de8ea161de7b0a02b6e02R12) and it is used during PhysSim: https://github.com/LBNL-UCB-STI/beam/pull/2403/files#diff-2569558f4a12ac19dfc7f015a0bf3b8cR43-R46
We need another handler which does speed calculation during PhysSim. But it's not straightforward because we don't have traveled link ids, so we can't compute the total traveled distance. So we have two options:
- Save total distance as one of the attributes of a leg when we create a plan (and later during re-routing): https://github.com/LBNL-UCB-STI/beam/pull/2403/files#diff-31c39b0aed2e70023741ec77656aef3cR397
- Make a route request again when you have link_id of origin (`PersonDepartureEvent.linkId`) and destination (`PersonArrivalEvent.linkId`)

**Comment by JustinPihony** [comment]
Was this fixed in #2512 ? @REASY

**Comment by rajnikantsh** [comment]
closed via https://github.com/LBNL-UCB-STI/beam/pull/2512
