### ISSUE TITLE
rename beam.physsim.jdeqsim.cacc.minimumRoadSpeedInMetersPerSecond

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2450]
rename beam.physsim.jdeqsim.cacc.minimumRoadSpeedInMetersPerSecond to
beam.physsim.jdeqsim.cacc.adjustedMinimumRoadSpeedInMetersPerSecond

**Comment by JustinPihony** [comment]
Fixed via #2454
