### ISSUE TITLE
Simunto Via can't open the results for sf-light-1k

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2453]
Run sf-light-1k for 0 iteration with turned-on PhysSim events, add/change configs:
```
beam.physsim.writeEventsInterval = 1
beam.physsim.events.fileOutputFormats = "xml(.gz)"
```
and try to load it to SimuntoVia. Network is loaded successfully, but PhysSim events is not.

**Comment by SHaaD94** [comment]
Wasn't able to reproduce the issue please check it out again. Perhaps it is OS related issue.

**Comment by YOxan** [comment]
Can it happen because the output events not in the MatSim format?

**Comment by REASY** [comment]
@REASY should double test it, but for now, I'm closing
