### ISSUE TITLE
collect google maps austin car travel times data for validation

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2463]
1.) Run script developed in #2438 with inputs:

- https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/austin/austin-prod-200k-cacc-enabled-flowCap0.13-60hours__2020-03-25_17-16-30_iwj -> CarStats last iteration
--sampleSize=50 \
--sampleSeed=12345 \
--travelDistanceIntervalInMeters=[3000,15000] \
--departureTimeIntervalInSeconds=[28800,32400] \  and evening: [61200,64800]
--areaBoundBox=[(-97.843763,30.481509),(-97.655786,30.180919)]

2.) collect manually data from google maps for 50 morning and 50 evening peak traveltimes (use Wednesday -> use Oct 2019 and departure time from entry) -> googleReferenceTravelTimes.csv -> google spreadsheet

Link to the run: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/austin/austin-prod-200k-cacc-enabled-flowCap0.13-60hours__2020-03-25_17-16-30_iwj
Filename: `#ITER_NUMBER#.studyarea.CarRideStats.personal.csv.gz`
Full path: https://beam-outputs.s3.amazonaws.com/output/austin/austin-prod-200k-cacc-enabled-flowCap0.13-60hours__2020-03-25_17-16-30_iwj/ITERS/it.10/10.studyarea.CarRideStats.personal.csv.gz

**Comment by carloscaldas** [comment]
Link to the spreadsheet:
https://docs.google.com/spreadsheets/d/1I3mZz8GC-vWoTjtfoSDLB1ot0vXD0Ywg4i5X73qpdpo/edit#gid=758028699
