### ISSUE TITLE
create script for comparing run with reference google travel times

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2464]
input: carstats and googleReferenceTravelTimes.csv

output: compare travel times of run to googleReferenceTravelTimes -> average traveltime error

key to match on: departure time, departure coordinate, arrival coordinate.
attention: some entries might be missing.

**Comment by REASY** [comment]
https://colab.research.google.com/drive/19Qycl5kQyBxeFR7jvAqt22j-yuRZCwam
