### ISSUE TITLE
Make sure the python script call right version

### ISSUE THREAD

**Issue by carloscaldas** [LBNL-UCB-STI/beam#2469]
Create a README explaining how pip can download dependencies and also add a file `requirements.txt`

**Comment by REASY** [comment]
From the review from one of the PRs: https://github.com/LBNL-UCB-STI/beam/pull/2468/files#r399759896

**Comment by carloscaldas** [comment]
Closed by PR https://github.com/LBNL-UCB-STI/beam/pull/2753
