### ISSUE TITLE
Grafana: increase performance of collecting EV-CAV-RH metrics.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2504]
Right now, for the production run (smart-baseline.conf) there is an 8-13% increase in iteration calculation time when EV-CAV metrics are enabled.

For example iteration execution time in minutes:
for all metrics except EV-CAV:
run1 it0 - 55.77, it1 - 34.97
run2 it0 - 57.02, it1 - 35.97

for all metrics include EV-CAV:
run1 it0 - 60.23, it1 - 39.37
run2 it0 - 61.82, it1 - 41.18

**Comment by JustinPihony** [comment]
Was this fixed in #2548?

**Comment by nikolayilyin** [comment]
> Was this fixed in #2548?

yep, it was fixed, thanks!
