### ISSUE TITLE
create converter for TAZ to H3 conversion for parking

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2513]
# Parking conversion
- e.g. switch from 1000 TAZ to 500 hexes, keep totals of parking subcategories intact 

## Scenario1
**Input:**
- TAZ coordinates centers file
- TAZ parking coordinates
- TargetHexIndexes: a file containing H3 indexes

**Output:**
- Target parking file with hex

## Scenario2:

**Input:**
- parking with hexes indexes. 500 hex
- TargetHexIndexes: a file containing H3 indexes

**Output:**
- Target parking file with hex

**Comment by carloscaldas** [comment]
Closed with this PR: https://github.com/LBNL-UCB-STI/beam/pull/2537
