### ISSUE TITLE
DemandFollowingRepositioningManager: ToList is dangerous in particular place

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2515]
Under some circumstances the usage of List can hurt performance:
![image](https://user-images.githubusercontent.com/5107562/78939955-43ae1800-7adf-11ea-8960-040477adb50e.png)

There is conversion to Scala List
https://github.com/LBNL-UCB-STI/beam/blob/dafcef1470653f948017d5289d68c2658da15d86/src/main/scala/beam/agentsim/agents/ridehail/repositioningmanager/DemandFollowingRepositioningManager.scala#L171
Later on this is passed to `EnumeratedDistribution` which tries to access it by index:
https://github.com/apache/commons-math/blob/7b005845af41746e938b713b6fc8f45ff98a8e60/src/main/java/org/apache/commons/math4/distribution/EnumeratedDistribution.java#L91

Of the solution can be just rewrite it with the usage of ArrayList:
```scala
val arrList = new java.util.ArrayList[CPair[ClusterInfo, java.lang.Double]](topNClosest.length)
topNClosest.foreach { x =>
  arrList.add(new CPair[ClusterInfo, java.lang.Double](x, x.size.toDouble))
}
val distr = new EnumeratedDistribution[ClusterInfo](rng, arrList)
```

**Comment by REASY** [comment]
Created PR in commons-math to fix it there too: https://github.com/apache/commons-math/pull/134

**Comment by haitamlaarabi** [comment]
Good call!

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2529
