### ISSUE TITLE
automated test for performance degregation

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2521]
-> how can measure performance of runs over time and measure degradation?

**Comment by JustinPihony** [comment]
[Found](https://stackoverflow.com/a/1772732/779513) this is already built in via the "Trend" link:

![image](https://user-images.githubusercontent.com/1621855/79680615-89559980-81df-11ea-91de-0b6346d5bc00.png)

which gives a graph like this:

![image](https://user-images.githubusercontent.com/1621855/79680621-9bcfd300-81df-11ea-95dd-6c8bd8d0d602.png)


The only thing is that we only store the last 20 builds or 7 days (whichever hits first). So, if you want a longer history then we'll have to increase this - or output it somewhere else and go off of that - but that'd be separate development.

Additionally it shows all builds - including failed and incomplete ([and maybe only the last 20?](https://issues.jenkins-ci.org/browse/JENKINS-22008)). If you want to handle that then I could dig further into things like https://plugins.jenkins.io/view-job-filters/ and whatnot.  Or pull it out using [the JSON API](https://beam-ci.tk/job/beam-forced-prs/api/json?tree=allBuilds[number,id,timestamp,result,duration]) and again go with custom development - but this would be simpler/more straightforward.

**Comment by wrashid** [comment]
please create task to collect json data in google spreadsheet automatically for develop and production-sfbay-develop
