### ISSUE TITLE
split ZonalParkingManager into multiple actors

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2535]
When a new algorithm is ready, we have to check what happened with parking quality.

The metric to measure is parking utilization per TAZ per hour (parking utilization is the number of reservations per hour). Having this measure we can now compare the results of two different runs by computing absolute difference for the same TAZ in the same hour and plot that error.

For that first, we need to get a variability of the base algorithm (current ZonalParkingManager), for [a production run](https://github.com/LBNL-UCB-STI/beam/blob/production-sfbay-develop/production/sfbay/smart/smart-baseline.conf). Three runs with 1 iteration in each run is enough.

The same number of runs should be done for new algorithm.

**Comment by REASY** [comment]
In the case of clustering, there is a chance to have areas which do not belong to any cluster. This should be handled properly.

Full view:
![Full](https://user-images.githubusercontent.com/5107562/79640825-f5bfa100-81bd-11ea-8f66-19ffe3f922ed.png)

Zoomed
![Zoomed](https://user-images.githubusercontent.com/5107562/79640784-ab3e2480-81bd-11ea-852f-dad039fe97d3.png)

Zoomed more:
![Zoomed2](https://user-images.githubusercontent.com/5107562/79640864-46cf9500-81be-11ea-946a-c3bb593f474f.png)

**Comment by wrashid** [comment]
production test: lastIteration=0, one time default manager, cluster=1,2,4,8,16

**Comment by wrashid** [comment]
also do 50% run @REASY

**Comment by REASY** [comment]
The previous runtime can be found in the following issue: https://github.com/LBNL-UCB-STI/beam/issues/2390

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2551/

**Comment by REASY** [comment]
Link to the results: https://docs.google.com/spreadsheets/d/1Ajurlm0T89rXmBGwj0_Me94-jIrKEctCzBapi2LlSCQ/edit#gid=0
