### ISSUE TITLE
Tests fail when Wait Time parameter is set above 870 seconds

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#2536]
To reproduce this issue, 
change the following parameter in beam.conf under beamville to:
`beam.agentsim.agents.rideHail.allocationManager.alonsoMora.waitingTimeInSec = 900
then run one of the following tests:
```
RideHailPassengersEventsSpec
EventsFileSpec
```
The tests fail because some agents that trigger "ReserveRideHail", do not show up afterwards in the events file output, raising the possibility of unnoticeable crash or a stuck state.

NB. the name of the above parameter might have changed if the PR #2529 had been merged to:
`beam.agentsim.agents.rideHail.allocationManager.maxWaitingTimeInSec = 900`

**Comment by REASY** [comment]
I can see the same kind of failure happens for ParkingSpec, related issue: https://github.com/LBNL-UCB-STI/beam/issues/2547.

**Comment by YOxan** [comment]
@wrashid Is that resolved and can be closed?
