### ISSUE TITLE
TransitInitializer: Reduce initialization time by parallelization

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2544]
[This loop can](https://github.com/LBNL-UCB-STI/beam/blob/407dd18c35ec72d7830a44aedc6cff92c2e2f11b/src/main/scala/beam/router/TransitInitializer.scala#L134) be easily parallelized using, for example, built-in Scala parallel collection. This will require some changes in the type of data structures used there:
- Replace var integer by AtomicInteger: https://github.com/LBNL-UCB-STI/beam/blob/407dd18c35ec72d7830a44aedc6cff92c2e2f11b/src/main/scala/beam/router/TransitInitializer.scala#L34
- Replace mutable.Map by ConcurrentHashMap: https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/router/TransitInitializer.scala#L50

Here is what I see in the case of Austin runs:
```
21:45:01.905 [ClusterSystem-akka.actor.default-dispatcher-4] INFO  beam.router.TransitInitializer - [1] Initialized transit trips in 70752 ms. Keys: 76347, Values: 76347
```

**Comment by JustinPihony** [comment]
Closed via #2576
