### ISSUE TITLE
Allow to set minimum resolution level during creation of h3 indices

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2560]
This means, we ensure that we have nothing with lower resolution than minimum resolution.

**Comment by carloscaldas** [comment]
Improve description

**Comment by carloscaldas** [comment]
@wrashid is it supposed to be defined by config file? hard coded programming? or during class instantiation? or any other combination?

**Comment by carloscaldas** [comment]
Closed by the PR https://github.com/LBNL-UCB-STI/beam/pull/2763
