### ISSUE TITLE
prepare beam jdeqsim run data for comparison with GPU traffic simulation

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2566]

**Comment by REASY** [comment]
Branch: https://github.com/LBNL-UCB-STI/beam/tree/art/jdeqsim-benchmark
App to run: https://github.com/LBNL-UCB-STI/beam/blob/art/jdeqsim-benchmark/src/main/scala/beam/physsim/jdeqsim/JDEQSimRunnerApp.scala
Data: https://drive.google.com/file/d/12y3s1fl5QSdkVj0ada0JV5ohOjyY3pVY/view?usp=sharing
