### ISSUE TITLE
Typed Actor is production ready, shall we migrate to it?

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2580]
[Typed actors](https://doc.akka.io/docs/akka/current/typed/actors.html) are production-ready. Shall we migrate our actors to be typed?

@JustinPihony what do you think?

**Comment by JustinPihony** [comment]
I see no reason to not, however it should probably a low priority to migrate. The lifespan of classic actors is indefinite currently, so they aren't going anywhere anytime soon. Also, we could create new actors as typed and they will work together - moving into the migration over time and building a comfort level.
