### ISSUE TITLE
frank-wolf jdeqsim: why sudden change at iteration 5?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2596]
Is it memory size, if yes, what exactly happening?

The parameter which controls [FrankFolf](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/resources/beam-template.conf#L296) is:
```
beam.physsim.relaxation.type = "experiment5_0"
```
![image](https://user-images.githubusercontent.com/13569531/80839870-ad42b300-8bc1-11ea-9236-5f7f4c8cb026.png)

**Comment by rajnikantsh** [comment]
non replicative on any sf-light and urbansim scenario hance closing this.
