### ISSUE TITLE
for average speed calculations: are we doing weighting by road length?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2597]
(we might be just dividing by number of links)
check for produced csv/pngs

**Comment by YOxan** [comment]
For a moment we just get all of the speeds of Trips (which is distance divided by travelTime - [here](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/analysis/cartraveltime/models.scala#L25)) and then calculate the average of that speeds list - [here](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/Statistics.scala#L43)
