### ISSUE TITLE
refactor: replace taz and parking readers with new strongly typed ones

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2602]
see https://github.com/LBNL-UCB-STI/beam/pull/2537/files

**Comment by carloscaldas** [comment]
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/infrastructure/taz/TAZTreeMap.scala#L126
```Scala
private def readCsvFile(filePath: String): Seq[CsvTaz]
```
returns the type below:
```Scala
case class CsvTaz(id: String, coordX: Double, coordY: Double, area: Double)
```

**Comment by carloscaldas** [comment]
Closed with the PR https://github.com/LBNL-UCB-STI/beam/pull/2734
