### ISSUE TITLE
PathTraversalEvents without linkIds

### ISSUE THREAD

**Issue by SHaaD94** [LBNL-UCB-STI/beam#2626]
There are several cases of PathTraversalEvents which have empty linkIds.
I guess it should not be the case.

Seems like these is reproducible only on production runs, i guess due to high amount of traffic.

**Comment by REASY** [comment]
This is expected, it can happen for transit like SUBWAY or for bushwalking (when router couldn't find other route than WALK but it is longer than X hours). Most probably those cases were for those modes.
