### ISSUE TITLE
get routes using google api

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2639]

**Comment by carloscaldas** [comment]
Google provides 2 available APIs related to roads:
- **Snap to roads**: This service returns the best-fit road geometry for a given set of GPS coordinates. This service takes up to 100 GPS points collected along a route, and returns a similar set of data with the points snapped to the most likely roads the vehicle was traveling along. Optionally, you can request that the points be interpolated, resulting in a path that smoothly follows the geometry of the road.
- **Nearest roads**: This service returns individual road segments for a given set of GPS coordinates. This services takes up to 100 GPS points and returns the closest road segment for each point. The points passed do not need to be part of a continuous path.

Which one should be used? What is the input and output of the expected feature?

**Comment by wrashid** [comment]
we would like to get routes (startCoordinate, endCoordinate) -> route information

**Comment by carloscaldas** [comment]
#Description:

##Input
```
def findPaths(
	origin: WgsCoordinate, 
	destination: WgsCoordinate, 
	departureTime: LocalDateTime,
	avoidTools: Boolean,
	mode: Mode  <-- Driving
): Seq[Route]
```

## Output
```
Route(
	durationIntervalInSeconds: Range[Int],
	distanceInMeters: Int,
)
```

**Comment by carloscaldas** [comment]
Closed with the PR:
https://github.com/LBNL-UCB-STI/beam/pull/2667
