### ISSUE TITLE
Agentsim starts before done loading agents

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#2640]
in the course of working on #2612, I'm running into an issue where agentsim seems to start and complete before all of the agents are loaded:

> b.a.scheduler.BeamAgentScheduler - Hour 24.0 completed. 5.1(GB)
11:08:39.632 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 24.5 completed. 5.1(GB)
11:08:39.632 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 25.0 completed. 5.1(GB)
11:08:39.633 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 25.5 completed. 5.1(GB)
11:08:39.634 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 26.0 completed. 5.1(GB)
11:08:39.635 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 26.5 completed. 5.1(GB)
11:08:39.640 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 27.0 completed. 5.1(GB)
11:08:39.641 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 27.5 completed. 5.1(GB)
11:08:39.643 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 28.0 completed. 5.1(GB)
11:08:39.643 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 28.5 completed. 5.1(GB)
11:08:39.644 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 29.0 completed. 5.1(GB)
11:08:39.645 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 29.5 completed. 5.1(GB)
11:08:39.646 [ClusterSystem-akka.actor.default-dispatcher-19] INFO  b.a.scheduler.BeamAgentScheduler - Hour 30.0 completed. 5.1(GB)
11:08:39.650 [ClusterSystem-akka.actor.default-dispatcher-27] ERROR beam.agentsim.agents.PersonAgent - Cannot schedule an event ScheduleTrigger(ActivityEndTrigger(24330),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/population/11/25#272239815],0) at tick 24330 when 'nowInSeconds' is at 108001}
11:08:39.651 [ClusterSystem-akka.actor.default-dispatcher-27] ERROR beam.agentsim.agents.PersonAgent - Cannot schedule an event ScheduleTrigger(ActivityStartTrigger(0),Actor[akka://ClusterSystem/user/BeamMobsim.iteration/population/10/23#-1407711884],0) at tick 0 when 'nowInSeconds' is at 108001}

This can be reproduced by running `beamville/beam.conf` in the branch `zn/generate-secondary-activities-first-iter`

**Comment by crixal** [comment]
Looks that problem in generated plans. For example generated plan contains lesser activities than original plan
<img width="1095" alt="Screenshot 2020-06-16 at 09 46 59" src="https://user-images.githubusercontent.com/17457532/84793564-77e20f80-b01f-11ea-8c83-167679e559a0.png">
Some times generated plan can contains only one activity with undefined endTime. In this case agent sim will be started before all InitializeTrigger's are completed.
<img width="1095" alt="Screenshot 2020-06-16 at 09 48 49" src="https://user-images.githubusercontent.com/17457532/84794101-0ce50880-b020-11ea-8556-9be5b887bc5e.png">

**Comment by zneedell** [comment]
OK, makes sense why that is causing an issue. I see two possible fixes--when we're loading people's plans we can look for plans with one activity and automatically add an end time for the end of the simulation (or some other way of making the simulation robust to one-activity plans). Or if that isn't feasible I can edit the secondary activity model to either not return one-activity plans or make sure they have an end time if so. @wrashid -- thoughts as to what would work best?

This explains why the problem is coming up in Beamville, although I wonder if it would solve the issue on sf-light using Urbansim plans. Beamville has some plans with only non-work activities, so it makes sense that in some cases the secondary activity model would modify them and return plans with no activities. Urbansim plans all have a work activity, which shouldn't ever be deleted. So it'll be interesting to see whether this fixes the issue with sf-light too. If it does then I need to look more closely into the generated plans, because something unexpected must be happening.
