### ISSUE TITLE
reading from beam csv not working for various sflight configs

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2646]
![image](https://user-images.githubusercontent.com/13569531/81749199-ccb6c700-9470-11ea-8d57-d3a4c030184d.png)
e.g. test/input/sf-light/sf-light-10k-csv.conf (also correct other neighbouring files as needed)

following code might help to resolve issue:

```beam.agentsim.agents.plans {
  inputPlansFilePath = ${beam.inputDirectory}"/csvInput/plans.csv"
  inputPersonAttributesFilePath = ${beam.inputDirectory}"/csvInput/population.csv"
}
beam.agentsim.agents.households {
  inputFilePath = ${beam.inputDirectory}"/csvInput/households.csv"
  inputHouseholdAttributesFilePath = ""
}
beam.agentsim.agents.vehicles.vehiclesFilePath = ${beam.inputDirectory}"/csvInput/vehicles.csv"```

**Comment by carloscaldas** [comment]
PR: https://github.com/LBNL-UCB-STI/beam/pull/2690

**Comment by carloscaldas** [comment]
PR https://github.com/LBNL-UCB-STI/beam/pull/2690

**Comment by carloscaldas** [comment]
Closed with the PR https://github.com/LBNL-UCB-STI/beam/pull/2690
