### ISSUE TITLE
Mode Choice graphs for specific commute types

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2681]
In order to calibrate Austin and Detroit scenarios from provided data we should be able to have all mode choices graphs for the which includes both home and work. 

Requirements:
- Try to avoid code duplication
- Is it possible to extend the current mode choice graphs/csvs with extra filter and adjust output file name?

**Comment by wrashid** [comment]
beam.exchange.scenario.urbansim.activitySimEnabled="boolean | false"

**Comment by carloscaldas** [comment]
Closed with the PR https://github.com/LBNL-UCB-STI/beam/pull/2724
