### ISSUE TITLE
Leg histogram drive_transit "en route" does not go to zero.

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#272]
-> not yet reproducible for sf-light, but easily reproducible for application-sfbay, e.g. 30k agents.

**Comment by wrashid** [comment]
![image](https://user-images.githubusercontent.com/13569531/39835571-5c9b5cb6-5385-11e8-9034-8ec2f87796da.png)

**Comment by wrashid** [comment]
[events_2agents.txt](https://github.com/LBNL-UCB-STI/beam/files/1989653/events_2agents.txt)

**Comment by wrashid** [comment]
confirmed: does not happen to same set of agents in each run.

**Comment by colinsheppard** [comment]
Determined the issue is a mislabeling between drive_transit and walk_transit. Looking into it by investigating the circumstances for the misclassification...

![image](https://user-images.githubusercontent.com/333206/40038397-c73a91aa-57c6-11e8-8348-7dc66b1cde45.png)

**Comment by colinsheppard** [comment]
Created a test and fixed the issue, but waiting to hear from @michaz about whether there was a good reason to redirect folks from drive_transit into walk_transit when in replanning after departure.
