### ISSUE TITLE
How much memory is needed to run CCH

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2748]
Austin run with CCH on c5.9xlarge(72 Gbytes RAM) has failed with OOM. Is it possible to get some understanding of the amount of memory needed to run CCH? What is taking so much memory? OD pairs generation?

Branch: AK/#2624-merg-urbansim-with-austin
Commit: dcea0555c8fc2dbe4f5ce82c2553108b44d0e4c4
Config: test/input/texas/austin-prod-200k_cch.conf
Run output: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/austin/austin-prod-200k-cch__2020-06-11_19-38-23_fog
Check [cloud-init.log](https://beam-outputs.s3.amazonaws.com/output/austin/austin-prod-200k-cch__2020-06-11_19-38-23_fog/cloud-init-output.log) for error:
```
c0eaa7ff9700: Pull complete
Digest: sha256:dfedadb067d1ab4a185dafeb119d188ff431a04adf50c3ac9447e6cc060d4e22
Status: Downloaded newer image for beammodel/routing-framework:1.0

> Task :run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/jdk1.8.0_231/bin/java'' finished with non-zero exit value 137

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':run'.
```

**Comment by SHaaD94** [comment]
> OD pairs generation?

OD pairs generation is pretty lightweight and straightforward.
Last line in log is launch of routing framework. Will try to get some info about framework ram consumption.

**Comment by SHaaD94** [comment]
Here are some measurements i made in different setups:
```
California pbf
VERTEXES 1522785
EDGES 3573885

RANDOM ODS 1: OOM
-----------------
Detroid PBF:

VERTEXES 240317
EDGES 597776
RANDOM ODS
ODS 1:  2GB RAB
ODS 1kk: 8GB RAB
----------------
Simplified Austin PBF:
VERTEXES 105289
EDGES 250051

RANDOM ODS:
10k: 3.5gb
1kk: 4 gb
10kk: 5gb

MAX DISTANCE OD:
10k: 5.1gb
100k: 9.2gb

Acutal ODS from failed run
118k Hour 5 - 5.6gb
812k Hour 18 - 7.3gb
```
So these numbers are pretty low and they should not be the problem.
Will try to reproduce the RAM usage by launching beam itself.
