### ISSUE TITLE
Detroit: Init ActivitySim calibration

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2749]
We got initial ActivitiySim model: https://detroit-activitysim.s3.us-east-2.amazonaws.com/base/asim_outputs.zip

We need to update Detroit scenario with new data. One can use Austin set up as an example and merge this branch to the Detroit branch:
Branch: [AK/#2624-merg-urbansim-with-austin](https://github.com/LBNL-UCB-STI/beam/tree/AK/%232624-merg-urbansim-with-austin)
Config: [test/input/texas/austin-prod-200k.conf](https://github.com/LBNL-UCB-STI/beam/blob/AK/%232624-merg-urbansim-with-austin/test/input/texas/austin-prod-200k.conf)
Compressed input file location: https://github.com/LBNL-UCB-STI/beam/tree/AK/%232624-merg-urbansim-with-austin/test/input/texas/urbansim_v2_autosharing_off

New way of loading scenario is controlled by parameter beam.exchange.scenario.source equals to urbansim_v2: https://github.com/LBNL-UCB-STI/beam/blob/AK/%232624-merg-urbansim-with-austin/test/input/texas/austin-prod-200k.conf#L331-L338

**Comment by nikolayilyin** [comment]
s3 output path to the results of calibrated run with ActivitySim - https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/detroit/detroit-200k-cutmap-flowCap-0.07-speedScal-1.2__2020-06-29_16-48-54_jvy
