### ISSUE TITLE
is there a reason for having two tasks checkScalafmt and checkScalaFmt when we look at the IntelliJ gradle plugin?

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2781]
![image](https://user-images.githubusercontent.com/13569531/85896091-794cce00-b7bd-11ea-903d-6683e1ebd4f9.png)

**Comment by JustinPihony** [comment]
This is a naming thing. I looked into the code of the plugin's `checkscalafmt` and all it does is check that the files are set up appropriately to be formatted. That said, I think this is the second time I looked into this and as such will make a change to the naming on our end to be even more explicit.
