### ISSUE TITLE
prepare for graph hopper integration with help of michael

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#2795]
understand router integration in beam and graph hopper basics -> work on integration of graph hopper with michael: https://github.com/graphhopper/graphhopper

**Comment by REASY** [comment]
Both StaticGH and QuasiGH are now in develop branch. They are controlled by the parameter `beam.routing.carRouter`: https://github.com/LBNL-UCB-STI/beam/blob/96729a106772e18cdae57bcaf8ba877c61788743/src/main/resources/beam-template.conf#L766-L767
