### ISSUE TITLE
New York: Collect more data

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2815]
Data collected for Wednesday in the beginning of the February and Wednesday in the beginning of the July.

- [ ] Traffic counts/volumes (the use - choose one day, aggregate it hourly and sum up counts in hour). Introduce the concept of study area (rough) to reduce the number of roads.
- [ ] Public transportation counts (how many people are using public transport): average number of people entering/leaving transit per hour, train occupancy
- [ ] Parking (off-street, on-street, garage)
- [ ] Other networks with speeds/capacities/number of lanes
- [x] GTFS (done by @REASY , commits e16f3f2f1698712f96b10e0fb51dd31dab89f04f and bf6a26fcd2d6d551cbb1c5315e4e73cff630aa86)

**Comment by REASY** [comment]
Traffic Volume Counts (2014-2018): https://data.cityofnewyork.us/Transportation/Traffic-Volume-Counts-2014-2018-/ertz-hr4r
![image](https://user-images.githubusercontent.com/5107562/87332611-0639aa80-c566-11ea-9862-4d595302507e.png)

**Comment by REASY** [comment]
New York DOT (Department of Transportation) Data Feeds: https://www1.nyc.gov/html/dot/html/about/datafeeds.shtml

**Comment by REASY** [comment]
![mobility-report-2018-print.pdf](https://user-images.githubusercontent.com/5107562/87337986-95e35700-c56e-11ea-979e-2ca3b05ccc4b.png)
via http://www.nyc.gov/html/dot/downloads/pdf/mobility-report-2018-print.pdf

**Comment by REASY** [comment]
Parking from mobility report:
![image](https://user-images.githubusercontent.com/5107562/87338569-97614f00-c56f-11ea-9ead-0b92922feee3.png)
via http://www.nyc.gov/html/dot/downloads/pdf/mobility-report-2018-print.pdf

**Comment by REASY** [comment]
Traffic counts on 2018-04-11 (Wednesday)
![image](https://user-images.githubusercontent.com/5107562/87429583-32a90180-c60e-11ea-92ff-6e0ff1fb21c4.png)

**Comment by nikolayilyin** [comment]
GTFS agencies table: https://docs.google.com/spreadsheets/d/1Rt_aXaXJ4Df8sbsqH6baY23dd7k85ROzNwDIrjNDbfM/edit#gid=323341130
GTFS stops shapefiles:
https://beam-outputs.s3.us-east-2.amazonaws.com/new_city/newyork/gtfs/agency-shape.zip
https://beam-outputs.s3.us-east-2.amazonaws.com/new_city/newyork/gtfs/sourse-shape.zip

**Comment by REASY** [comment]
![image](https://user-images.githubusercontent.com/5107562/87965300-b9198380-cae5-11ea-9d97-174562a32b52.png)
via https://www.nymtc.org/Portals/0/Pdf/Travel%20Patterns/2019/Travel%20Patterns-Q4%202019.pdf?ver=2020-06-24-105340-547

**Comment by REASY** [comment]
![image](https://user-images.githubusercontent.com/5107562/87965888-a94e6f00-cae6-11ea-93b1-ea98d225a347.png)
via https://www.nymtc.org/Portals/0/Pdf/Hub%20Bound/2018%20Hub%20Bound/DM_TDS_Hub_Bound_Travel_2018.pdf?ver=2020-01-29-145050-030
