### ISSUE TITLE
New York: GTFS with New York and surroundings 200k

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2817]
This is needed to get some sense of performance with large transit. If it is too slow, it will require either the crop map or remove some of the providers.

**Comment by nikolayilyin** [comment]
done, gtfs data are in NYC branch, all present runs done with gtfs 
for example here are gtfs data files - https://github.com/LBNL-UCB-STI/beam/tree/art/new-york-scenario/test/input/newyork/r5-prod
