### ISSUE TITLE
Secondary activities. Create a test to check secondary activities generation.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2843]
One needs to create a test for secondary activities generation. 
To enable secondary activities generations there is a configuration entry:
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/resources/beam-template.conf#L99
Also to generate secondary activities one needs to provide two files. Here are files for "sf-light urbansim" scenario:
https://github.com/LBNL-UCB-STI/beam/blob/develop/test/input/sf-light/activity-intercepts.csv
https://github.com/LBNL-UCB-STI/beam/blob/develop/test/input/sf-light/activity-params.csv
To test that secondary activities were calculated one may compare 'modechoice' and 'modechoice_commute' graphs (csv).
Graphs with '_commute' suffix are representing mode choice for work\home locations when other graphs represent a summary of all modes chosen.

**Comment by wrashid** [comment]
test: number of activities increasing, new types of activities added, other tests: set all secondary activity weights to zero and one to high and see what happens.

**Comment by JustinPihony** [comment]
Resolved by #2879
