### ISSUE TITLE
Entering/Leaving counts for particular area

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2856]
- Area should be provided by polygon (or simple bounding box)
- Output should aggregated by modes:  absolute numbers  and ratio

Reference data: https://www.nymtc.org/Portals/0/Pdf/Hub%20Bound/2018%20Hub%20Bound/DM_TDS_Hub_Bound_Travel_2018.pdf?ver=2020-01-29-145050-030

**Comment by dimaopen** [comment]
Created a jupyter notebook that calculates the number of people entering CBD of New-York by modes. As an input parameter it takes pandas dataframe loaded from $it.events.csv
https://gist.github.com/dimaopen/f76b6b0dd342149e4dd7a6dd793f4440

It takes about 5 min to process NY-200k output.
