### ISSUE TITLE
CARRouter: R5 (Default), staticGH, quasiDynamicGH

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2880]
We need to introduce a new parameter. Parameter name `beam.routing.carRouter` which can get three values: "R5" (default), "staticGH" and "quasiDynamicGH".
- staticGH: The travel time is not changed over the iterations, static travel time
- quasiDynamicGH: There is a feedback loop from PhysSim to the GH router. GH router knows the travel time on the link for particular hour

**Comment by crixal** [comment]
https://github.com/LBNL-UCB-STI/beam/pull/2896
