### ISSUE TITLE
Detroit network: Analysis of disconnected islands

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2884]
Branch: inm/merge-urbansim-with-detroit
Network: https://github.com/LBNL-UCB-STI/beam/blob/inm/merge-urbansim-with-detroit/test/input/detroit/r5/detroit-big.osm.pbf

@robfitzgerald raise an issue with Detroit network (probably because we modified the network by removing residential roads):
>I have mostly gotten Detroit to work, but, there seem to be disconnected link stubs all over the network. Those interfere with our MEP calculations. I am trying to confirm that these are an artifact of the file I was sent, but for future reference, since we conduct a nearest neighbor search from MEP centroids to road network links, having disconnected links can be a problem for us.

> So this particular stub supports “car;walk;bike” modes, but, is connected to only one link which supports only “walk;bike” modes. so, after we filter to the car network for our MEP drive isochrone, this link becomes a singleton

> I have been testing for disconnected components using a bottom-up search, and, as I increase the number of search steps, I continue to find more disconnected islands in the drive network:
```
13:02:30.741 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 11 - removed 5206 rows
13:02:54.218 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 12 - removed 5231 rows
13:03:20.871 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 13 - removed 5251 rows
13:03:58.655 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 14 - removed 5272 rows
13:04:38.924 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 15 - removed 5289 rows
13:05:24.589 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 16 - removed 5302 rows
13:06:17.047 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 17 - removed 5313 rows
13:07:25.650 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 18 - removed 5322 rows
13:08:57.435 [main] INFO  gov.nrel.mbap.mep.app.asdfjkl$ - step limit 19 - removed 5336 rows
```

> here’s the output with the set of (bad) link ids which are parts of islands which i could find within a 20-step spanning tree search rooted in each link (5,347 links). i’m still going about confirming my results.
[physsim-drive-isolated-20.csv.gz](https://github.com/LBNL-UCB-STI/beam/files/5035897/physsim-drive-isolated-20.csv.gz)

> an example of coloring some of the bad downtown links
![image](https://user-images.githubusercontent.com/5107562/89550797-4d991b00-d834-11ea-8201-290ad59f04ae.png)

> mostly a problem downtown with short roadways connecting arterials to neighborhoods. only a few strange spots outside of downtown too.
![image](https://user-images.githubusercontent.com/5107562/89550819-5689ec80-d834-11ea-9ffc-ca244adc9969.png)

> even with a search distance of 20 links, i still have not identified all disconnected components, for example:
![image](https://user-images.githubusercontent.com/5107562/89550863-6275ae80-d834-11ea-823b-ea1cbbb35414.png)

**Comment by robfitzgerald** [comment]
I also found this to be the case for the Austin as well.
![Screen Shot 2020-08-06 at 2 59 37 PM](https://user-images.githubusercontent.com/7003022/89589296-9afc9480-d802-11ea-9dea-7cacba81845e.png)

There's this one strange cluster
![Screen Shot 2020-08-06 at 3 00 33 PM](https://user-images.githubusercontent.com/7003022/89589345-ab147400-d802-11ea-9b59-20478a59a2d2.png)

But most of the issue seems to be due to these small links in the downtown
![Screen Shot 2020-08-06 at 3 01 14 PM](https://user-images.githubusercontent.com/7003022/89589357-b5cf0900-d802-11ea-8bc0-9342eeb817dd.png)
