### ISSUE TITLE
Refactor: Change name of modeChoiceAlternativesWhenRHPooled.csv.gz into more accurate name.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2885]

**Comment by REASY** [comment]
https://github.com/LBNL-UCB-STI/beam/commit/ff36ec3c0e4ef780db58f5408e8ca659ec5e5411

**Comment by JustinPihony** [comment]
This was not pushed to develop - I assume you wouldn't have closed otherwise, but making sure :)
