### ISSUE TITLE
BugFix: fix the removal of people according to industry

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2908]
in the current implementation, we are using a not really fair method to calculate whom to be removed.

there is a fix for removal -> https://github.com/LBNL-UCB-STI/beam/commit/9e416dd8a530401ead41782a5062a15afa34faa7
but this fix doing the wrong things.

ideally, we should check each person and remove each person with specific probability (specified in specific file) and in the result population, we should see some difference between the size of the population from run to run.

In the current implementation, we always have the same number of the population removed which is not fair.

Also, it is worth adding logging with the size of population before and after removal.

**Comment by REASY** [comment]
d1a82f44d000f4edfc9805fb824bd8642f8dfb72

**Comment by JustinPihony** [comment]
This is another scenario where it seems to not have been put into develop - should it?

**Comment by nikolayilyin** [comment]
I think we will merge these changes into develop together with the rest of NYC branch
