### ISSUE TITLE
Google API: Do we really need Direction API advanced?

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2909]
Seems like we currently use [Direction API advanced](https://developers.google.com/maps/documentation/directions/usage-and-billing#directions-advanced) which costs double 8 USD instead of 4 USD per 1000 request. Do we really need it?
Code related to Google API:
- https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/mapsapi/googleapi/GoogleAdapter.scala
- https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/events/handling/TravelTimeGoogleStatistic.scala

**Comment by rajnikantsh** [comment]
We are using traffic information https://github.com/LBNL-UCB-STI/beam/blob/72246f696af4c748a05413b16dfd527d87469725/src/main/scala/beam/utils/mapsapi/googleapi/Route.scala#L11 which are only available in Direction API advanced 

![Screenshot from 2020-08-25 19-54-28](https://user-images.githubusercontent.com/5759657/91186676-f7b9e380-e70c-11ea-90df-c2220ec65c78.png)
