### ISSUE TITLE
AWS Notification to the person who has started the machine

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2931]
#aws-notification channel does a good job, but seems like it is not enough. We need some solution (Slack bot, Slack app) which will send personal message to the people who instantiated AWS instance that it is idle state

**Comment by JustinPihony** [comment]
I do not think we can solve this 100%, but we can probably get as close as possible with the following plan:
* Cover instances started by the gradle jobs
 * Use the github email that is already provided and stored as an instance tag
 * If there is no email found in the github profile when launching the instance then throw an exception and force it to be provided explicitly
* Cover instances started directly via AWS
 * Tag all users in AWS with their email, then use Cloudtrail or something to get the user and send to their tagged email

The question is if email is the appropriate venue, or if we should somehow enforce slack ids so they can be auto @'d? Ultimately there should probably be a master group that is attached to ALL notifications (google group and/or slack group)
