### ISSUE TITLE
CI: develop branch is red/broken

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2933]
5 times in a row develop branch is red:
![image](https://user-images.githubusercontent.com/5107562/90983656-eac8b300-e599-11ea-9390-019c274ad0fa.png)

The links to the builds:
- https://beam-ci.tk/job/develop/515/consoleFull
- https://beam-ci.tk/job/develop/514/consoleFull
- https://beam-ci.tk/job/develop/513/consoleFull
- https://beam-ci.tk/job/develop/512/consoleFull
- https://beam-ci.tk/job/develop/511/consoleFull

There are two test constantly failing:
```
20:46:14 Running a beamville scenario with cosimulation
20:46:14 - must result event being published and read *** FAILED *** (14 seconds, 244 milliseconds)
20:46:14   java.lang.IllegalArgumentException: requirement failed
20:46:14   at scala.Predef$.require(Predef.scala:268)
20:46:14   at beam.cosim.helics.BeamFederateSpec.$anonfun$new$1(BeamFederateSpec.scala:56)
20:46:14   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
20:46:14   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
20:46:14   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
20:46:14   at org.scalatest.Transformer.apply(Transformer.scala:22)
20:46:14   at org.scalatest.Transformer.apply(Transformer.scala:20)
20:46:14   at org.scalatest.FlatSpecLike$$anon$5.apply(FlatSpecLike.scala:1682)
20:46:14   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
20:46:14   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
```

```
19:13:07 Person cost analyser
19:13:07 - must calculate average trip expense (0 milliseconds)
19:13:07 - must calculate total cost !!! IGNORED !!!
19:13:07 - must calculate total ride_hail incentive !!! IGNORED !!!
19:13:07 - must calculate total car toll *** FAILED *** (12 milliseconds)
19:13:07   0.0 was equal to 0 (PersonCostAnalysisSpec.scala:32)
```

**Comment by JustinPihony** [comment]
For the federate spec I added an assertion to verify my assumption that it is 0:

> must result event being published and read *** FAILED *** (33 seconds, 501 milliseconds)
> 0 was not greater than 0 Charging Plugin Event expected to be greater than 0 but is 0 (BeamFederateSpec.scala:56)

As such, I'm going to see if I can dig in and find why this is flaky..

**Comment by JustinPihony** [comment]
Additionally I found that the issue is as expected - there are no charging events reliably being created in the given config. Should we maybe bump the config so that it guarantees a charge? @haitamlaarabi ?
