### ISSUE TITLE
WALK_TRANSIT exhaustion: Check which type causes exhaustion

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2949]
Look to the PathTraversalEvents (capacity, usage) for transit or extend ReplanningEvent and add extra information, like transit vehicle id

**Comment by nikolayilyin** [comment]
Exhaustion caused buses with capacity 57. With transit capacity set to 0.06, we got buses of total size 5, which was not enough to fit all actors willing to use buses.

here is a histogram of PathTraversal events by different types of transport. The histogram shows that there are many full buses with a maximum capacity of 5. 
![image](https://user-images.githubusercontent.com/5393513/91843491-7dceb080-ec5e-11ea-85e7-397ec001c973.png)

**Comment by nikolayilyin** [comment]
We decided to increase bus capacity by 2.6 times up to 150 with 75 sitting places and 75 standing places.
