### ISSUE TITLE
NYC. Dashboard. Ridership comparison for selected area.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2964]
There is a function to do ridership comparison for trips through a specified area.
Something is wrong with this function - either our simulation is wrong or the comparison of simulation vs baseline.
One needs to figure it out.

There is the problem with car trips - in the selected area we have more car trips (in some runs) than in baseline run.
here is an analysis for the same group of runs vs the same baseline:

this is how ridership comparison vs baseline looks like for the whole simulation
![image](https://user-images.githubusercontent.com/5393513/92144963-2b3cf200-ee20-11ea-8c40-ef2d59cd5261.png)
this is how ridership comparison vs baseline looks like for the selected area
![image](https://user-images.githubusercontent.com/5393513/92145044-4f003800-ee20-11ea-9352-fb0a41e81aea.png)

**Comment by nikolayilyin** [comment]
Current function to get data:

`def people_flow_in_cbd_s3(s3url, iteration):
    s3path = get_output_path_from_s3_url(s3url)
    events_file_path = s3path + "/ITERS/it.{0}/{0}.events.csv.gz".format(iteration)
    return people_flow_in_cbd_file_path(events_file_path)


def people_flow_in_cbd_file_path(events_file_path, chunksize=100000):
    events = pd.concat([events[events['type'] == 'PathTraversal'] for events in
                        pd.read_csv(events_file_path, low_memory=False, chunksize=chunksize)])
    return people_flow_in_cdb(events)


def diff_people_flow_in_cbd_s3(s3url, iteration, s3url_base, iteration_base):
    s3path = get_output_path_from_s3_url(s3url)
    events_file_path = s3path + "/ITERS/it.{0}/{0}.events.csv.gz".format(iteration)
    s3path_base = get_output_path_from_s3_url(s3url_base)
    events_file_path_base = s3path_base + "/ITERS/it.{0}/{0}.events.csv.gz".format(iteration_base)
    return diff_people_flow_in_cbd_file_path(events_file_path, events_file_path_base)


def diff_people_flow_in_cbd_file_path(events_file_path, events_file_path_base, chunksize=100000):
    events = pd.concat([events[events['type'] == 'PathTraversal'] for events in
                        pd.read_csv(events_file_path, low_memory=False, chunksize=chunksize)])
    events_base = pd.concat([events[events['type'] == 'PathTraversal'] for events in
                             pd.read_csv(events_file_path_base, low_memory=False, chunksize=chunksize)])
    return diff_people_in(events, events_base)


def people_flow_in_cdb(df):
    polygon = Polygon([
        (-74.005088, 40.779100),
        (-74.034957, 40.680314),
        (-73.968867, 40.717604),
        (-73.957924, 40.759091)
    ])

    def inside(x, y):
        point = Point(x, y)
        return polygon.contains(point)

    def num_people(row):
        mode = row['mode']
        if mode in ['walk', 'bike']:
            return 1
        elif mode == 'car':
            return 1 + row['numPassengers']
        else:
            return row['numPassengers']

    def benchmark():
        data = """mode,Entering,Leaving
subway,2241712,2241712
car,877978,877978
bus,279735,279735
rail,338449,338449
ferry,66932,66932
bike,33634,33634
tram,3528,3528
        """
        return pd.read_csv(StringIO(data)).set_index('mode')

    f = df[(df['type'] == 'PathTraversal')][['mode', 'numPassengers', 'startX', 'startY', 'endX', 'endY']].copy(
        deep=True)

    f['numPeople'] = f.apply(lambda row: num_people(row), axis=1)
    f = f[f['numPeople'] > 0]

    f['startIn'] = f.apply(lambda row: inside(row['startX'], row['startY']), axis=1)
    f['endIn'] = f.apply(lambda row: inside(row['endX'], row['endY']), axis=1)
    f['numIn'] = f.apply(lambda row: row['numPeople'] if not row['startIn'] and row['endIn'] else 0, axis=1)

    s = f.groupby('mode')[['numIn']].sum()
    b = benchmark()

    t = pd.concat([s, b], axis=1)
    t.fillna(0, inplace=True)

    t['percentIn'] = t['numIn'] * 100 / t['numIn'].sum()
    t['percent_ref'] = t['Entering'] * 100 / t['Entering'].sum()

    t = t[['numIn', 'Entering', 'percentIn', 'percent_ref']]

    t['diff'] = t['percentIn'] - t['percent_ref']
    t['diff'].plot(kind='bar', title="Diff: current - reference, %", figsize=(7, 5), legend=False, fontsize=12)

    t.loc["Total"] = t.sum()
    return t


def get_people_in(df):
    polygon = Polygon([
        (-74.005088, 40.779100),
        (-74.034957, 40.680314),
        (-73.968867, 40.717604),
        (-73.957924, 40.759091)
    ])

    def inside(x, y):
        point = Point(x, y)
        return polygon.contains(point)

    def num_people(row):
        mode = row['mode']
        if mode in ['walk', 'bike']:
            return 1
        elif mode == 'car':
            return 1 + row['numPassengers']
        else:
            return row['numPassengers']

    f = df[(df['type'] == 'PathTraversal') & (df['mode'].isin(['car', 'bus', 'subway']))][
        ['mode', 'numPassengers', 'startX', 'startY', 'endX', 'endY']].copy(deep=True)

    f['numPeople'] = f.apply(lambda row: num_people(row), axis=1)
    f = f[f['numPeople'] > 0]

    f['startIn'] = f.apply(lambda row: inside(row['startX'], row['startY']), axis=1)
    f['endIn'] = f.apply(lambda row: inside(row['endX'], row['endY']), axis=1)
    f['numIn'] = f.apply(lambda row: row['numPeople'] if not row['startIn'] and row['endIn'] else 0, axis=1)

    s = f.groupby('mode')[['numIn']].sum()
    s.fillna(0, inplace=True)

    # s['percentIn'] = s['numIn'] * 100 / s['numIn'].sum()

    return s['numIn']


def diff_people_in(current, base):
    def reference():
        data = """date,subway,bus,car
07/05/2020,-77.8,-35,-21.8
06/05/2020,-87.2,-64,-30.8
05/05/2020,-90.5,-73,-50.3
04/05/2020,-90.5,-71,-78.9
03/05/2020,0.0,4,-0.1
        """
        ref = pd.read_csv(StringIO(data), parse_dates=['date'])
        ref.sort_values('date', inplace=True)
        ref['month'] = ref['date'].dt.month_name()
        ref = ref.set_index('month').drop('date', 1)
        return ref

    b = get_people_in(base)
    c = get_people_in(current)
    b.name = 'base'
    c.name = 'current'

    t = pd.concat([b, c], axis=1)
    t['diff_absolute'] = t['current'] - t['base']
    t['diff_percent'] = t['diff_absolute'] / t['base'] * 100

    pc = reference()

    run = t['diff_percent'].to_frame().T
    run = run.reset_index().drop('index', 1)
    run['month'] = 'Run'
    run = run.set_index('month')
    result = pd.concat([run, pc], axis=0)

    result.plot(kind='bar', title="Diff current - reference, %", figsize=(10, 10), legend=True, fontsize=12)
    return result`

**Comment by dimaopen** [comment]
That's the number of people entering the Central Business District of NY by cars calculated with 2 methods:
1. By PathTraversal event
2. By ModeChoice and Activity Start. They are different for some reason (I think that it is caused that the number of people who traveled for ModeChoice and PathTraversal is calculated differently)
  | Run NY-8 | Base
-- | -- | --
Num people by PathTraversal | 12151 | 12142
Num people by ModeChoice & ActivityStart | 11220 | 11205

In general, the trend is the same: The base run has a bit fewer people traveled to the CBD by car.

**Comment by dimaopen** [comment]
Actual data for the latest Manhattan data
![correct_pic](https://user-images.githubusercontent.com/1764256/92470346-f09bd680-f1de-11ea-89e8-ebf398a6ece6.png)

**Comment by dimaopen** [comment]
Data when empty taxis are excluded
![correct_pic](https://user-images.githubusercontent.com/1764256/92616521-ff5db880-f2c6-11ea-8c47-de7f490fd5e2.png)

**Comment by dimaopen** [comment]
Graphs for results when empty taxis are excluded.
![diff_current_baseline_04-07](https://user-images.githubusercontent.com/1764256/92616572-113f5b80-f2c7-11ea-82db-9935d0a4521d.png)

**Comment by dimaopen** [comment]
The latest runs produce the following picture:
![diff_apr_2_baseline](https://user-images.githubusercontent.com/1764256/92617967-895a5100-f2c8-11ea-9f93-bf13435f0c85.png)

**Comment by dimaopen** [comment]
Results for the baseline: https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/newyork/nyc-200k-baseline__2020-09-07_17-51-04_naj
![cbd-2](https://user-images.githubusercontent.com/1764256/94343132-bde74000-001e-11eb-8c25-51f1ac433242.png)
