### ISSUE TITLE
NYC. Calibration. Create a tool to manipulate choice between different walk transit vehicle types

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2966]
Currently, we can not tune the choice between BUS vs SUBWAY vs RAIL vs other walk transit kind of transport. 
One needs to create a tool to forse actors to choose one or another kind of public transport.

**Comment by wrashid** [comment]
beam.agentsim.agents.modalBehaviors.transitVehicleTypeVOTMultipliers = "[BUS:1000.0,SUBWAY:2.0]"

PopulationAttributes: getGeneralizedTimeOfLegForMNL

**Comment by wrashid** [comment]
if modalBehaviors.transitVehicleTypeVOTMultipliers for transit vehicle mode not present, take modeVotMultiplier.transit

**Comment by REASY** [comment]
Initial implementation is in 875d8585420cc24fe809f993da06f110c34b6dc4

**Comment by nikolayilyin** [comment]
done, implemented in art/new-york-scenario branch
