### ISSUE TITLE
NYC: Sample activities and render them with Via

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2979]

**Comment by nikolayilyin** [comment]
this script was used to create a visualization of activities -> https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/beam_to_matsim/visualization/via/visualization_12.scala

**Comment by nikolayilyin** [comment]
duplicated - https://github.com/LBNL-UCB-STI/beam/issues/2973
