### ISSUE TITLE
NYC. Investigate speed reference values from transcom

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#2981]
One needs to investigate why there is a speed drop in transcom reference values for month 7 and why there are no speed increase in months from 4 to 7

![image](https://user-images.githubusercontent.com/5393513/92644300-cf74dc00-f2eb-11ea-8467-c54a61e8df42.png)

**Comment by dimaopen** [comment]
Transcom speed by hour for different months (Tue-Thu):
![speeds_by_hour](https://user-images.githubusercontent.com/1764256/92732899-b7e73300-f37f-11ea-80fc-8312ae47f855.png)
Speed dencity for hour 16 for different months:
![speed_dencity_16](https://user-images.githubusercontent.com/1764256/92732981-d2211100-f37f-11ea-966c-7313d0808f56.png)
List of links where the average speed was decreased significantly (> 20 MPH) for each month compared to April.
https://docs.google.com/spreadsheets/d/1W4MAgvX35cytgWNpPZXWAY54Yv999TbYrO1T_qsN7i4/edit?usp=sharing

**Comment by nikolayilyin** [comment]
Investigation showed nothing specific. Transcom data has this strange pattern and it seems, there is nothing we can do with it.
