### ISSUE TITLE
AWS S3: Tool to get the size of our folders

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2986]
The tool (can use either AWS CLI or API) to compute the size of the folders. UI shows 12.3 TB:
![image](https://user-images.githubusercontent.com/5107562/92987173-4bd50e00-f4ea-11ea-8f1a-8e02ce9bcea5.png)

Overall beam-outputs:
![image](https://user-images.githubusercontent.com/5107562/92987212-b6864980-f4ea-11ea-8f7a-cf3b0cd13529.png)

**Comment by JustinPihony** [comment]
We could probably add this to the lambda and cloudwatch we already have set up. What would be the limits that should trigger it is my question? @wrashid @REASY 12.3 tb is $280/month at .023/gb - what is acceptable?
