### ISSUE TITLE
NYC: Why we need to put very low RH intercept (< -1000)?

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#2987]
File modeChoiceDetailed.csv.gz under iteration folder can be helpful in order to understand what happened during mode choice and why the person has chosen ride hail? Is it because there were no other modes?

**Comment by dimaopen** [comment]
Nikolay says the issue happens at least at these runs
https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/newyork/nyc-200k-fixed-probabilities-04-1__2020-09-13_23-09-56_buz
https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/newyork/nyc-200k-fixed-probabilities-04-2__2020-09-13_23-09-55_tzt
https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/newyork/nyc-200k-fixed-probabilities-04-3__2020-09-13_23-09-56_upg

**Comment by dimaopen** [comment]
Only persons with high income choose the ride_hail. For the run nyc-200k-fixed-probabilities-04-2__2020-09-13_23-09-55_tzt. We have the following income of the "ride_hail" persons
```
persons = all_data[(all_data['altType'] == 'ride_hail') & (all_data['wasChosen'] == 1)]
persons['income'].describe()
```
```
count    2.077500e+04
mean     6.807673e+05
std      2.306579e+05
min      1.714000e+05
25%      5.342000e+05
50%      6.040000e+05
75%      7.736000e+05
max      1.646000e+06
```

income of people who choose walk_transit:
```
count    2.624310e+05
mean     2.345967e+05
std      2.045172e+05
min     -1.030000e+04
25%      8.300000e+04
50%      1.588000e+05
75%      3.300000e+05
max      1.830000e+06
```

income of people who choose car
```
count    3.520600e+05
mean     2.169949e+05
std      2.005217e+05
min     -5.800000e+03
25%      7.450000e+04
50%      1.396000e+05
75%      3.050000e+05
max      1.830000e+06
```

In general this low value of RH intercept corrects the personal value of money/time so that most of people don't choose the RH.

**Comment by nikolayilyin** [comment]
looks like the high income of people explains why they are still using RH even when -150 intercept is set.
