### ISSUE TITLE
Implement Vehicle Agents - Step 1

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#3]
Under

`docs/uml/VehicleAgentSpec.puml`

I've drafted a preliminary spec for three classes that will play a role in defining vehicle agents in BEAM. I've also created stubs for these classes under the package

`beam/agentsim/agents/vehicles/`

These should be pretty quick to implement because few methods are actually specified (more will come soon). 

One feature that may not be totally clear is the Trajectory class, the idea here is that a trajectory holds a collection of tuples containing a coordinate (use the Matsim Coord class) and a time (times are doubles). 

When the getLocation method is used from this class, it should efficiently determine the location associated with that time by storing the collection of tuples in a tree and by interpolating between coordinates when an exact match isn't found on the time. 

Also, if the time provided to the method is before the first time in the collection or after the last time, then it should be assumed that the location is the starting point or ending point, respectively.

**Comment by colinsheppard** [comment]
See latest changes to the spec: 651e249

After some discussion today, we decided that vehicles should not be BeamAgents but rather should just be plain actors. So please rename to BeamVehicle (which distinguishes these vehicles from MATSim vehicles) and extend Actor instead of BeamAgent.

**Comment by dserdyuk** [comment]
@colinsheppard I would also suggest to rename `enclosingVehicle` to `carrier`

**Comment by colinsheppard** [comment]
Yes, I like that better, please make that change.

**Comment by dserdyuk** [comment]
@colinsheppard consider this closed

**Comment by dserdyuk** [comment]
following work in #18
