### ISSUE TITLE
NYC: Test run without other transits rather than SUBWAY

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3007]

**Comment by nikolayilyin** [comment]
Done, 
looks like it is done during this simulation =>  https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/newyork/new-york-200k-baseline-no-bus__2020-09-24_20-00-26_geb

The idea was very helpful and ended up with solution for beam runs with two routers - one with only subway routes
