### ISSUE TITLE
AWS: Update JVM on base AMI

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3011]
Created ami-0460cc54d96505eb4 with the latest Oracle JDK 8u261-b12 and updated simulateBeam lambda

**Comment by JustinPihony** [comment]
I updated CI also. I'll try to get to the task of updating jenkins when the updateDependencies task runs next week. I'm also wondering if there is a way we could enforce/warn when simulate is not on the latest....I bet we can since it follows conventions.
