### ISSUE TITLE
Bug: PopulationAdjustment.logModes doesn't expect a collection in excluded-modes attribute

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3014]
Branch: [dogurtsov/gh-walk-ny-test](https://github.com/LBNL-UCB-STI/beam/tree/dogurtsov/gh-walk-ny-test)
Commit: bd258b73881551e5bcd82fe89bbcc901b893b487
Config: [test/input/newyork/new-york-100k-car-only-gh-sampled.conf](https://github.com/LBNL-UCB-STI/beam/blob/dogurtsov/gh-walk-ny-test/test/input/newyork/new-york-100k-car-only-gh-sampled.conf)

![image](https://user-images.githubusercontent.com/5107562/94334353-d09f4c00-0001-11eb-8264-da8d8152d152.png)

https://github.com/LBNL-UCB-STI/beam/blob/ebf1e3037f9786cc02b2d0f18e5d297ebf278324/src/main/scala/beam/sim/population/PopulationAdjustment.scala#L65

**Comment by jctim** [comment]
Hi Art @REASY please take a look at https://github.com/LBNL-UCB-STI/beam/pull/3049

**Comment by JustinPihony** [comment]
Closed un #3049
