### ISSUE TITLE
Put params throughout codebase into config file

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#302]
Right now there are many parameters in the code base that should get added to the config file. 

E.g. class DrivingCostDefaults. 

There are others, look through the TODO's or for notes saying things like "put in config" or "don't hard code", etc.

Please may an initial attempt to move these into the config file and submit a pull request for others to review.

**Comment by zishanbilal** [comment]
Following places left, please suggest for these;
- AgentSimToPhysSimPlanConverter.java (64, 56) private Random rand = MatsimRandom.getRandom(); // TODO: check, if this is better then general random resp. seeded from beam config
- RideHailSurgePricingManager.scala (88, 12) val rand = new Random // TODO: seed following random to some config seed?
- BeamVehicleType.scala (61, 8) Powertrain.PowertrainFromMilesPerGallon(360) // TODO: Don't hardcode!!!
- EnergyEconomyAttributes.scala(86, 6) // TODO: don't hardcode... Couldn't these be put into the Enum for [[BeamVehicleType]]?
- SpaceTime.scala (18, 71) Json.fromDoubleOrNull(MathUtils.roundDouble(a.loc.getX, 5)), // TODO: Hardcoded. Should this be configurable?
- TAZMain.scala (48, 4) // TODO: attriutes or xml from config file - allow specifying multiple files

**Comment by zishanbilal** [comment]
random seed configured from beam config
