### ISSUE TITLE
NYC: Integrate rideship python scripts into Beam

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3027]
In the end of simulation we have to run ride-ship analysis and put it to the output folder of Beam. Please, come up with the file names. Aggregated data has to be stored in CSV. 

One of the important parts of this issue is to update our AMI in order to have all the needed dependencies to run our scripts: Pandas, GeoPandas, Matplotlib and so on

**Comment by nikolayilyin** [comment]
Closed because it is too specialized for NYC and probably will not have any usage for other cities simulations.
