### ISSUE TITLE
RideHailIterationsStatsCollector: Do we really need it?

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3032]

**Comment by dimaopen** [comment]
This class is used to produce log entries like the following after each iteration.
04:50:41.293 [scala-execution-context-global-19283] INFO  b.a.a.r.RideHailIterationsStatsCollector - 3450 rideHail vehicles (out of 140526) were never moved and 19802 vehicles were moved without a passenger, during whole day.
It works with the physsim in parallel and but sometimes longer than physsim.

**Comment by dimaopen** [comment]
I found that this RideHailIterationsStatsCollector is also used for gathering ridehail statistic and then provide this statistic to RideHailIterationHistory. On the next iterations, this statistic is used within ridehail package (ie RepositioningLowWaitingTimes).

**Comment by REASY** [comment]
@dimaopen thanks  for investigation. That's proves that it is used only by `RepositioningLowWaitingTimes` so it is safe to make `RideHailIterationsStatsCollector` rely on the type of repositioning manager - only when it is `REPOSITIONING_LOW_WAITING_TIMES`. The place where repositioning managers are created: https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/ridehail/allocation/RideHailResourceAllocationManager.scala#L248-L274
