### ISSUE TITLE
Bug: Industry is not properly assigned 

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3035]
https://github.com/LBNL-UCB-STI/beam/blob/ffc6ca941e971a2693d12af63b75795a41b84523/src/main/scala/beam/utils/csv/readers/BeamCsvScenarioReader.scala#L99

Branch: art/new-york-scenario

**Comment by jctim** [comment]
Hey Art @REASY 
Please take a loot at https://github.com/LBNL-UCB-STI/beam/pull/3048
