### ISSUE TITLE
Ride hail initialization type FILE does not access matching algorithms

### ISSUE THREAD

**Issue by natelant** [LBNL-UCB-STI/beam#3089]
I made the following changes to the `sf-light-5k.conf`. Now, when ride hail initialization type is set to FILE, the allocation manager  does not access the matching algorithms `AsyncGreedyVehicleCentricMatching.scala` or `AlonsoMoraMatchingWithAsyncGreedyAssignment.scala`. (Note that using the PROCEDURAL initialization type, the allocation manager does successfully access these matching algorithms.) Is there something that I could change so that these matching algorithms are accessed? 

`beam.agentsim.agents.rideHail.initialization.initType = "FILE"`

`beam.agentsim.agents.rideHail.allocationManager.name="DEFAULT_MANAGER"`
`beam.agentsim.agents.rideHail.allocationManager.requestBufferTimeoutInSeconds = 0`
`beam.agentsim.agents.rideHail.allocationManager.matchingAlgorithm="ASYNC_GREEDY_VEHICLE_CENTRIC_MATCHING"`

`beam.outputs.baseOutputDirectory = "/output"`
`beam.outputs.baseOutputDirectory = ${?BEAM_OUTPUT}`
`beam.outputs.addTimestampToOutputDirectory = false`

`# To keep all logging params in one place, BEAM overrides MATSim params normally in the controller config module`
`beam.outputs.defaultWriteInterval = 1`
`beam.outputs.writePlansInterval = ${beam.outputs.defaultWriteInterval}`
`beam.outputs.writeEventsInterval = ${beam.outputs.defaultWriteInterval}`
`beam.physsim.writeEventsInterval = ${beam.outputs.defaultWriteInterval}`
`beam.physsim.writePlansInterval = ${beam.outputs.defaultWriteInterval}`
`beam.outputs.writeAnalysis = false`
`beam.outputs.writeLinkTraversalInterval = 0`
`beam.physsim.linkStatsWriteInterval = 0`

`# Events for physsim`
`beam.physsim.events.eventsToWrite = "ActivityEndEvent,ActivityStartEvent,LinkEnterEvent,LinkLeaveEvent,PersonArrivalEvent,PersonDepartureEvent,VehicleEntersTrafficEvent,VehicleLeavesTrafficEvent"`
`beam.physsim.events.fileOutputFormats = "xml.gz"`
`beam.physsim.eventsForFullVersionOfVia = true`
`beam.physsim.eventsSampling = 1.0`

**Comment by JustinPihony** [comment]
I am surprised that you say it worked with Procedural set. How did you verify that? I only ask because currently only the POOLING_ALONSO_MORA allocation manager supports ASYNC_GREEDY_VEHICLE_CENTRIC_MATCHING. Would you be able to share your logs so that we can verify - as well as which branch you are working from (develop/master/tagged release/etc)?

**Comment by natelant** [comment]
You are correct; I had been using the POOLING_ALONSO_MORA allocation manager. I am verifying that "it worked" when the code stops at a breakpoint in the ASYNC_GREEDY_VEHICLE_CENTRIC_MATCHING when running the debugger. Like you said, it doesn't stop when using the default allocation manager. It only stops at the breakpoint when using procedural (not file) and running pooling_alonso_mora. I would like to be able to use file eventually.

I am working from the develop branch. I shared the log file when using FILE and pooling_alonso_mora allocation manager.
[beamLog.zip](https://github.com/LBNL-UCB-STI/beam/files/5766202/beamLog.zip)

**Comment by natelant** [comment]
Here is another attempt at explaining the issue.

In scenario 1, we are running the default matching algorithm with a file input. We confirmed that this works.
```
beam.agentsim.agents.rideHail.initialization.initType = "FILE"

beam.agentsim.agents.rideHail.allocationManager.name="DEFAULT_MANAGER"
beam.agentsim.agents.rideHail.allocationManager.requestBufferTimeoutInSeconds = 0

beam.outputs.baseOutputDirectory = "/output"
beam.outputs.baseOutputDirectory = ${?BEAM_OUTPUT}
beam.outputs.addTimestampToOutputDirectory = false

# To keep all logging params in one place, BEAM overrides MATSim params normally in the controller config module
beam.outputs.defaultWriteInterval = 1
beam.outputs.writePlansInterval = ${beam.outputs.defaultWriteInterval}
beam.outputs.writeEventsInterval = ${beam.outputs.defaultWriteInterval}
beam.physsim.writeEventsInterval = ${beam.outputs.defaultWriteInterval}
beam.physsim.writePlansInterval = ${beam.outputs.defaultWriteInterval}
beam.outputs.writeAnalysis = false
beam.outputs.writeLinkTraversalInterval = 0
beam.physsim.linkStatsWriteInterval = 0

# Events for physsim
beam.physsim.events.eventsToWrite = "ActivityEndEvent,ActivityStartEvent,LinkEnterEvent,LinkLeaveEvent,PersonArrivalEvent,PersonDepartureEvent,VehicleEntersTrafficEvent,VehicleLeavesTrafficEvent"
beam.physsim.events.fileOutputFormats = "xml.gz"
beam.physsim.eventsForFullVersionOfVia = true
beam.physsim.eventsSampling = 1.0
```
Then, we change the pooling method to the `alonso_mora` method and specified the matching algorithm (async_greedy). A debug point / log statement inserted into the `async_greedy_vehicle_centric_matching.scala` class never gets triggered.

```
beam.agentsim.agents.rideHail.allocationManager.name="POOLING_ALONSO_MORA"
beam.agentsim.agents.rideHail.allocationManager.requestBufferTimeoutInSeconds = 200

beam.agentsim.agents.rideHail.allocationManager.matchingAlgorithm="ASYNC_GREEDY_VEHICLE_CENTRIC_MATCHING"
```

Then, we changed the specification method to the `procedural` input. This triggered our breakpoints.

```
beam.agentsim.agents.rideHail.initialization.initType = "PROCEDURAL"
```
Is it possible to access the `async_greedy_vehicle_centric_matching` while supplying a `file` input?

Again, working from the develop branch

**Comment by JustinPihony** [comment]
Could you share a bit more specifics. I added a log and saw it in both procedural and file as expected. If you can share the conf you are using and command then I can try that to reproduce.

**Comment by natelant** [comment]
We found the issue. The problem is in a misspecified input file `rideHailFleet.csv`. We found spaces in the column header after noticing in the log that the value in column 'rideHailManagerId' is null (see chunk below). After removing all spaces in the input file, the allocation manager properly calls the matching algorithm when using `FILE` type initialization.

```
18:15:35.432 [ClusterSystem-ride-hail-manager-pinned-dispatcher-12] ERROR beam.sim.RideHailFleetInitializer$ - Could not initialize fleet from 'C:\WAV\BEAM\test\input\sf-light/rideHailFleet_wav.csv': assertion failed: Value in column 'rideHailManagerId' is null
...
	at beam.sim.RideHailFleetInitializer$.toRideHailAgentInputData(RideHailFleetInitializer.scala:22)
	at beam.sim.RideHailFleetInitializer$.$anonfun$readFleetFromCSV$1(RideHailFleetInitializer.scala:105)
```
