### ISSUE TITLE
Deploy:  Add profiler option to the deploy properties

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3098]
We need to add a new parameter [profiler_type](https://github.com/LBNL-UCB-STI/beam/blob/develop/aws/build.gradle#L84) which can be in three states:
- null: no profiler
- Cpu: only CPU profiler (`jfr` in build.gradle)
- CpuMem: CPU and Memory profiler (`jfrWithMem` in build.gradle)
If `profiler_type` is provided during deployment Beam has to automatically apply it to to [applicationDefaultJvmArgs](https://github.com/LBNL-UCB-STI/beam/blob/develop/build.gradle#L509). It can be done in the same way as `logbackConfig`

**Comment by JustinPihony** [comment]
This was resolved in #3100
