### ISSUE TITLE
Investigate tolls on roads in sf-bay area.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3101]
For sf-bay area I was unable to find any simulation results with non zero tolls, so, I assume, something is wrong with tolls in sf-bay area.

I was able to find a non zero tolls for NYC, but, when I plot all PathTraversal events with non zero tolls on a map, the distribution of them is strange.
Here is an example for New York
![image](https://user-images.githubusercontent.com/5393513/106514191-ffb05780-64e4-11eb-8bd5-55ff7dc3832e.png)
[toll_PTEs_2.zip](https://github.com/LBNL-UCB-STI/beam/files/5906560/toll_PTEs_2.zip)

So, one needs to configure tolls for sf-bay area and check if distribution of events with non zero tolls looks good.
Also it is worth checking if there are any paid roads in sf-bay area at all.

**Comment by zneedell** [comment]
FYI--the toll-prices.csv file is the same in all cities, assuming that is what's being used to assign tolls then I think we just haven't been updating it. 

In theory OSM has toll data but I have no idea if it's accurate or complete.

**Comment by rajnikantsh** [comment]
@zneedell , I have print toll data of sfbay OSM file but i can see only one entry for toll in sfbay OSM file

**Comment by JustinPihony** [comment]
Fixed via #3111
