### ISSUE TITLE
NERSC: Use NERSC to compute block group skims

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3144]
In order to run Beam in NERSC as container we need to slightly modify our build.gradle, https://github.com/LBNL-UCB-STI/beam/pull/3149. After this we need to create a new Beam image and push it to Docker Hub. 
NERSC uses Shifter to run containers in high-performance computing (HPC) environment which can run docker containers (still there are differences, https://docs.nersc.gov/development/shifter/how-to-use/#differences-between-shifter-and-docker)

Here is an example how to run beamville at NERSC:
1. Pull the image using `shifterimg pull`, choose the right version of Beam image https://hub.docker.com/repository/docker/beammodel/beam
```bash
abalaian@cori02:~> shifterimg pull beammodel/beam:0.8.6.4-nersc
2021-03-24T05:54:42 Pulling Image: docker:beammodel/beam:0.8.6.4-nersc, status: READY
```
2. Run scenarion, in this case I'm running test/input/beamville/beam.conf
```bash
abalaian@cori02:~> shifter --image=beammodel/beam:0.8.6.4-nersc /app/entrypoint.sh --config /app/test/input/beamville/beam.conf
OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)

  ________
  ___  __ )__________ _______ ___
  __  __  |  _ \  __ `/_  __ `__ \
  _  /_/ //  __/ /_/ /_  / / / / /
  /_____/ \___/\__,_/ /_/ /_/ /_/

 _____________________________________


Received 2 arguments: List(--config, /app/test/input/beamville/beam.conf)
Java version: 1.8.0_222
JVM args: List(-XX:+UnlockExperimentalVMOptions, -XX:+UseCGroupMemoryLimitForHeap)
Heap size: 1.9 GB
Heap max memory: 26.7 GB
Heap free memory: 1.8 GB
05:55:50.016 INFO  beam.sim.RunBeam$ -
```

An example of slum job `sf-light-10k.sl`:
```bash
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --constraint=haswell
#SBATCH --time=00:40:00
#SBATCH --qos=regular
#SBATCH --account=XXX
#SBATCH --image=beammodel/beam:0.8.6.4-nersc

srun -n 1 -c 32 shifter -e JAVA_OPTS='-Xmx64g' /app/entrypoint.sh --config /app/test/input/sf-light/sf-light-10k.conf
```
And to schedule it run `sbatch ./sf-light-10k.sl`

References: 
- https://github.com/NERSC/Shifter-Tutorial/blob/master/03-hands-on.md
- https://docs.nersc.gov/development/shifter/how-to-use/#using-shifter-at-nersc

**Comment by nikolayilyin** [comment]
Now we have a gradle task to run BEAM on nercs (https://github.com/LBNL-UCB-STI/beam/pull/3220)
