### ISSUE TITLE
Pilates test runs

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#3146]
Test Pilates with Beam. Are all the components interacting with each other? Do we see output of Beam?

**Comment by zneedell** [comment]
Repository is here https://github.com/ual/PILATES/tree/v2 (note, using the v2 branch). Let's also leave Urbansim turned off for now by keeping `land_use_freq: 0` in settings.yaml

**Comment by nikolayilyin** [comment]
It seems the functionality works fine
