### ISSUE TITLE
Flag to fix agent's activities and modes in plans

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#3160]
It would be nice to have a flag for an agent when we are loading in population/plans so that the agent's modes and trips remain fixed from iteration to iteration, even if clear modes is turned on in replanning. So basically we could have a subset of the population where the only thing they're doing from iteration to iteration is choosing a route.

**Comment by nikolayilyin** [comment]
@zneedell ,
apart from replanning we also have the generation of secondary activities, what should we do with an agent with this flag set during generation of secondary activities?

**Comment by zneedell** [comment]
@nikolayilyin to be honest I totally forget what the use case for this was going to be. Closing it for now
