### ISSUE TITLE
Mode Choice using skim values

### ISSUE THREAD

**Issue by dimaopen** [LBNL-UCB-STI/beam#3172]

**Comment by dimaopen** [comment]
I created the following code as a solution: https://github.com/LBNL-UCB-STI/beam/tree/do/%233172-mode-choice-using-skim. We decided not to go with it because it increases complexity a lot but doesn't give a real performance improvement (because of lacking most modes in the skims)

**Comment by JustinPihony** [comment]
@dimaopen Should we close this issue given the above?

**Comment by zneedell** [comment]
Actually @haitamlaarabi and I were just talking about this. We now have full block group to block group skims for SFBay, so potentially this could be worth trying again this week. Let's discuss on Monday.

Thanks for flagging, @Justin

**Comment by dimaopen** [comment]
@zneedell 
Should we close this issue? I think the code is not relevant now.
