### ISSUE TITLE
Skims: Generate skims for provided OD pairs and mods

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3193]
There is a branch `art/#2701-skims-in-parallel-4ci` with the implementation of generation of skims for all possible OD pairs based on all present TAZ centers.

skims - the results of route request + additional information about trip from O to D
OD - origin location to destination location (X, Y)
TAZ - traffic analysis zone or transportation analysis zone

The entry point for generator -> src/main/scala/beam/router/skim/urbansim/BackgroundSkimsCreator.scala.
The idea of existing code is the following: generator creates skims for all possible combinations of TAZ's in two steps. 
First, starting with BEAM simulation, walk and walk-transit skims are generated because there is no traffic impact on walking and public transport.
Then drive skims are generated at the end of the simulation when traffic information is available.

One needs to:
1. modify the background skims creator in order to reuse it for generation of skims for specified OD's and mods.
2. write a script to generate skims for specified input parameters.

input parameters:
1. CSV input file with the origin, destination, and mode
2. optional 'linkstats' file with congestion information
3. optional ODskims (FullODSkims) 
4. parallelism parameter to specify how many background workers will be used for skims calculation

output:
1. skims file

a note about additional parameter ODSkims: If ODSkims provided (certain fields not zeros) for desired OD pair with desired mode then return skims from ODSkims, otherwise calculate skims by modified BackgroundSkimsCreator.

**Comment by alex-vv** [comment]
These additional features are needed after a discussion:

- [ ] Add a missing time period in input.csv
- [ ] Make input.csv optional, if not set then calculate all skims
- [ ] Add optional output.csv compression (maybe automatically guess it based on a file extension)
