### ISSUE TITLE
Avoid parking/charging infrastructre downsampling

### ISSUE THREAD

**Issue by dimaopen** [LBNL-UCB-STI/beam#3201]
Downsampling may cause having zero of charing stations in a big number of TAZes. It causes statistic discrepancies. As a solution, we could instead of downsampling the parking data claim multiple parking stalls for each parking vehicle.

**Comment by dimaopen** [comment]
I created a solution here https://github.com/LBNL-UCB-STI/beam/tree/do/%233201_claim_multiple_stalls_during_parking. This increases complexity so we decided not to go with it.

**Comment by JustinPihony** [comment]
So are you attempting something else - or should we close this as not going to happen?

**Comment by dimaopen** [comment]
This issue was resolved in a different manner.
