### ISSUE TITLE
ActivitySim skims: using OMX format

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3232]
ActivitySim team is using OMX format for skims, this format is pretty fast for reading and mode effective for storage comparing to csv file.

There are [libraries for Python and Java](https://github.com/osPlanning/omx) to work with OMX.
In [this python notebook](https://colab.research.google.com/drive/1goo7zWy2RNgdVufjxoorc0hDIbla3pOh?usp=sharing)  there are examples of how to work with OMX as well as code to produce OMX skims out of BEAM csv skims.

We need to be able to produce our activitySim skims in OMX format, either by creating them in OMX or converting them from csv.gz into OMX.

Probably a simple scala util to convert csv.gz skims into OMX would be better

**Comment by dimaopen** [comment]
Within this task, the project [libraries for Python and Java](https://github.com/osPlanning/omx) was ported to gradle so that it can be easily used as a dependency. The repository is here https://github.com/LBNL-UCB-STI/omx-java.
A sample activitysim skim file in OMX format was generated and provided to the Urbansim team for review.

**Comment by dimaopen** [comment]
@zneedell The Urbansim team has not reviewed the new skim format. Should we close this issue?

**Comment by zneedell** [comment]
@dimaopen Since we opened this I've spent enough time working with the omx skims in pilates where I think I should be able to confirm that they're working as expected. I'll test it out this week and hopefully get it merged soon -- thanks for re-surfacing this

**Comment by dimaopen** [comment]
@zneedell The branch that I used to create the [OMX skims](https://beam-outputs.s3.amazonaws.com/skims/sf-light/full_skims.omx) is https://github.com/LBNL-UCB-STI/beam/tree/do/%233232-activitysim-skims-omx-format.
Please let me know what to do with this task.

**Comment by dimaopen** [comment]
This was implemented with this PR https://github.com/LBNL-UCB-STI/beam/pull/3736.
