### ISSUE TITLE
Skims: generate full OD skims for Austin in activitySim format 

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3236]
For the calculation, we need to generate block group centers using information from here - https://regional-open-data-capcog.opendata.arcgis.com/datasets/CAPCOG::block-groups-2020/about 

The generated blockgroup-centers.csv.gz file should be stored in test/input/texas/ folder.
Our taz-centers located here (in develop branch) - test/input/texas/taz-centers.csv.gz

Also, we need to use not all of them, but only those block groups that contain at least one taz center, or that overlap with the convex hull around the taz centers, or some other way of filtering out the additional block groups that don’t overlap with the model area.

In the following picture there is a comparison of block groups and our taz-centers
![image](https://user-images.githubusercontent.com/5393513/125170691-c2997100-e1b8-11eb-9bf9-e3806ab1f9bc.png)

**Comment by dimaopen** [comment]
I'm suggesting these block groups:
![austin_block_groups](https://user-images.githubusercontent.com/1764256/125321187-1afd7980-e345-11eb-9844-abb2d0b31e7a.png)

Though there are some empty block groups (that don't have TAZ centroids inside). But they pretty close to some of TAZ centroids and I think that we can still assign some data to them.
![no_taz_centers_inside](https://user-images.githubusercontent.com/1764256/125321200-1df86a00-e345-11eb-8d7e-90d028fe6fd3.png)

**Comment by zneedell** [comment]
Yep, that looks great to me, thanks!

**Comment by dimaopen** [comment]
test/input/texas/taz-centers.csv.gz contains strange areas of the TAZ. Does it look right?
```
taz,coord-x,coord-y,area
4849100000123,2965472.4183966145,3664299.0226117913,6.920068649889972E-5
4845300000055,2956925.8697230937,3631038.691737053,4.443195504928893E-4
4845300001536,2947913.7229686803,3635486.759407475,3.9404276999364317E-4
```

**Comment by dimaopen** [comment]
@zneedell provided the new blockgroups that come directly from Urbansim.
[block_groups_austin.zip](https://github.com/LBNL-UCB-STI/beam/files/7114681/block_groups_austin.zip)
The generated skim file for these block groups is https://beam-outputs.s3.amazonaws.com/output/austin/skims/austin-skims-res-full-new.csv.gz
