### ISSUE TITLE
AverageCarSpeed.png: color swap

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3248]
Personal and RideHail from time to time swap colors - Personal blue to green, RideHail from green to blue. 
Colors should not swap. 

Also green is barely visible, would be great to fix this as well.

**Comment by nikolayilyin** [comment]
An example of color swap:
![AverageCarSpeed](https://user-images.githubusercontent.com/5393513/127130137-b6f57c90-b26a-4bf6-8e4a-aaff0b41bf7e.png)
![AverageCarSpeed](https://user-images.githubusercontent.com/5393513/127130320-5fc2f972-8cb7-48a4-a438-1d4451ec03d7.png)

**Comment by dgm90** [comment]
Fixed in #3260
