### ISSUE TITLE
Matsim output files are not being deleted

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#3251]
The old logic to delete files was overridden in [this change](https://github.com/LBNL-UCB-STI/beam/commit/41e63982ac92edb4ab7bb8d09a9c0088c6f0860d#diff-4417dc7cbacdcba99a0f7e2432a69db72978ae1becb77d9f7f09ded4c1d21c05L531-L549) and since then we have seen the following in CI:

> 03:13:37 07:13:50.747 [ScalaTest-1-running-TransitPriceSpec] ERROR beam.sim.BeamSim - Failed to delete MATSim root files: beamville__2021-07-29_07-05-01_vuu
> 03:13:50 07:13:50.747 [ScalaTest-1-running-TransitPriceSpec] ERROR beam.sim.BeamSim - Failed to delete MATSim iteration files: 0.

A quick triage seems that the beam config is never set. We should have a meaningful default (ie. traveldistancestats.txt, traveldistancestats.png, tmp were the old ones) **and** have no yielding when the config is empty. Note that `String.split` will return an empty single value even for an empty string - and that needs to be protected against.

**Comment by dgm90** [comment]
@JustinPihony Could you give me a hint how to reproduce this issue, please? I tried to run `beamville` and `sf-light-1k` scenarios, but there was no such error.

**Comment by JustinPihony** [comment]
This seems to have been fixed by https://github.com/LBNL-UCB-STI/beam/commit/6a75733a29fe2086c9fc6b2bb069f6a0e9980f96#diff-4417dc7cbacdcba99a0f7e2432a69db72978ae1becb77d9f7f09ded4c1d21c05
