### ISSUE TITLE
Config: there are too many values pointing to map.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3268]
There are too many values that needs to point at the same folder with the map.
It leads to problems when some of values are pointed to one folder and some to another.
There are following config values that should point at the same folder (or files within):

`beam.routing.r5.directory` - most important

`beam.physsim.inputNetworkFilePath`
`beam.routing.r5.osmFile`
`beam.routing.r5.osmMapdbFile`

`beam.agentsim.scenarios.frequencyAdjustmentFile` (this one under question, probably the file itself might be placed anywhere)

One needs to reduce the number of config values that needs to point at the same location or add some sanity check during Beam initialization to reduce the number of human-made errors

**Comment by alex-vv** [comment]
If I got it correctly then probably HOCON substitution may be useful here 
https://github.com/lightbend/config/blob/master/HOCON.md#substitutions

something like 
```
beam.physsim.inputNetworkFilePath = some/path
beam.routing.r5.directory = ${beam.physsim.inputNetworkFilePath}
beam.routing.r5.osmFile = ${beam.routing.r5.directory}/file.osm
...
```

probably there should be some additional common dir config value so in the end the actual path can be specified only in one place.

**Comment by dgm90** [comment]
Fixed
