### ISSUE TITLE
Optimization of the updated SFBay map

### ISSUE THREAD

**Issue by dimaopen** [LBNL-UCB-STI/beam#3274]
Branch production-gemini-develop contains `production/sfbay/r5-updated/sf-bay.osm.pbf` file with the updated  (most reacent) network of SF bay area. It shows 2.5 times worse performance in R5 router comparing to the old map (`r5-simple-no-local`).
This updated map needs to be optimized.
Some approaches described here https://docs.google.com/document/d/1DwDiy3BCCRHAGfphG-9JcbC6qYt7gtCpXdGSKVh4pJY/edit
[PrepareOsmToR5.zip](https://github.com/LBNL-UCB-STI/beam/files/7061036/PrepareOsmToR5.zip)
Added a zipped scala app that allows removing nodes.

**Comment by nikolayilyin** [comment]
We need to to figure out why is this slowness happening to prevent the same problem for other maps.
If it is possible - we need a script / instruction how to detect and fix this issue.

**Comment by dimaopen** [comment]
The number of links on the old map = 50k, on the updated map = 350k.
The updated map contains all the small streets/roads while the old map doesn't.
![Screenshot from 2021-09-06 11-55-48](https://user-images.githubusercontent.com/1764256/132189830-36b4dd99-fb7c-4a26-9187-a334169c037f.png)

**Comment by dimaopen** [comment]
Added [Optimize map](http://ec2-18-116-117-142.us-east-2.compute.amazonaws.com/doku.php?id=run_synthpop:optimize_map) page to our internal wiki.

**Comment by dimaopen** [comment]
SFBay optimized map that is got from r5-updated map is in the following commit `55d55f8e28b3e0464387f3b5f4fc77127f4ae39f`.

**Comment by dimaopen** [comment]
2 the same configurations (gemini-base-2035-activitysim-oakland.conf, gemini-base-2035-activitysim-oakland-r5updated.conf). The only difference is the network. Gave us the following numbers of failed routing requests:

**Old map**
```
BIKE                   576
CAR                   2120
RIDE_HAIL                3
RIDE_HAIL_TRANSIT       12
TRANSIT              34836
WALK                  2226
```

**Updated map**
```
BIKE                   600
CAR                   2070
RIDE_HAIL                3
RIDE_HAIL_TRANSIT       13
TRANSIT              37395
WALK                  2202
```
