### ISSUE TITLE
Separation of logic and data. Updating gradle deploy script and AWS lambda function

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3275]
here are two gradle commands for deploy
regular deploy:  https://github.com/LBNL-UCB-STI/beam/blob/develop/aws/build.gradle#L37
pilates deploy (maybe not require to be updated): https://github.com/LBNL-UCB-STI/beam/blob/develop/aws/build.gradle#L124

here is the lambda function code for deploy command 
https://github.com/LBNL-UCB-STI/beam/blob/develop/aws/src/main/python/beam_lambda/lambda_function.py

the lambda function itself is on AWS
deploy lambda - https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/simulateBeam?tab=code
deploy pilates lambda - https://us-east-2.console.aws.amazon.com/lambda/home?region=us-east-2#/functions/runPilates?tab=code

**Comment by alex-vv** [comment]
lambas are updated now in #3272 and in AWS as well
