### ISSUE TITLE
Another approach to use router during AgentSim: not as an Actor.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3289]
The idea is the following: we can get some performance improvement if all our actors that do route requests will instead extends router (in some way) and do requests directly to router without sending any messages through actor system.

The idea requires investigation and testing.

**Comment by dimaopen** [comment]
A branch created with this approach https://github.com/LBNL-UCB-STI/beam/tree/do/%233289-router-not-actor
No performance improvement happens.
