### ISSUE TITLE
Ride hailing company design and inital implementation 

### ISSUE THREAD

**Issue by dserdyuk** [LBNL-UCB-STI/beam#33]
think about how to define our ride hailing companies. You might want to take a similar approach and use MATSim taxis classes as the basis, see:

https://github.com/matsim-org/matsim/tree/master/contribs/taxi/src/main/java/org/matsim/contrib/taxi

related to #18 

GanttStart: 2017-10-01

**Comment by dserdyuk** [comment]
From Colin:  
to begin with the company would just be an actor that maintains a spatial index of all taxis and is responsible for do the spatial queries when PersonAgents need to see how available / close-by the taxis are. 

Then the company is responsible for reserving the taxi for each Person and sending the message to the taxi drive to being the process of driving over to pick up the customer, etc.

**Comment by colinsheppard** [comment]
The flow will be: 

1) Person requests info, 
2) Manager does spatial query and returns wait time and price, 
3) if person chooses to use the service, then
4) person sends a reservation request, 
5) manager assigns and dispatches the taxi to pickup the person.

**Comment by dserdyuk** [comment]
further work in #52
