### ISSUE TITLE
Metrics to measure health of simulation

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3308]
The problem is the following - often some problems are invisible for someone doing many parallel BEAM runs. 
For example: 
- a couple of died during simulation actors, 
- a critical error which did not end in simulation stuckness/unexpected termination

We need a script, probably a python script, to automatically run it after the simulation and analyze simulation output. 
Then this script output should be stored in the file.

The results of this script might be used in lambda function as part of notification about simulation completion (both in slack message and in google spreadsheet) 

So far let's calculate the following metrics:
- beamLog.out:  amount of all ERROR log entries
- beamLog.out:  amount of all WARN log entries
- beamLog.out:  amount of all stacktraces
- beamLog.out:  number of died actors
- beamLog.out:  number of dead letters

**Comment by rajnikantsh** [comment]
closed via https://github.com/LBNL-UCB-STI/beam/pull/3314
