### ISSUE TITLE
Create a new beam scenario for the Seattle city

### ISSUE THREAD

**Issue by heyrutvik** [LBNL-UCB-STI/beam#3310]
Subtasks:

- [x] create a new city scenario
- [x] update/improve instruction

Instructions to create new scenario:
https://ec2-18-116-117-142.us-east-2.compute.amazonaws.com/doku.php

**Comment by heyrutvik** [comment]
## Information gathering

#### Local CRS (Coordinate Reference Systems): 
- https://epsg.io/32048 [EPSG:32048] (alternate option: https://epsg.io/32148)

#### Counties to consider (flow of workers)
- King County
- Snohomish County
- Pierce County
- Thurston County
- Kitsap County

![Screenshot from 2021-09-20 21-23-45](https://user-images.githubusercontent.com/6268538/134033912-aa01991c-6493-4e49-a791-21bf5173b259.png)

#### synthpop:
- `docker run -it <image_id> "WA" "King County" <n_thread>`
- `docker run -it <image_id> "WA" "Snohomish County" <n_thread>`
- `docker run -it <image_id> "WA" "Pierce County" <n_thread>`
- `docker run -it <image_id> "WA" "Thurston County" <n_thread>`
- `docker run -it <image_id> "WA" "Kitsap County" <n_thread>`

---

#### CTPP [state]:
https://beam-outputs.s3.amazonaws.com/new_city/ctpp/wa.zip

#### TAZ [state]:
https://www2.census.gov/geo/tiger/TIGER2010/TAZ/2010/tl_2011_53_taz10.zip

#### BG (block group) [state]:
https://www2.census.gov/geo/tiger/TIGER2019/BG/tl_2019_53_bg.zip

#### County shapefile:
https://www2.census.gov/geo/tiger/TIGER2019/COUNTY/tl_2019_us_county.zip

#### state (.osm.pbf) file:
https://download.geofabrik.de/north-america/us/washington.html

#### GTFS data [city]:
https://transitfeeds.com/p/king-county-metro/73/latest (other resources: https://metro.kingcounty.gov/GTFS/)

---

#### Prepare data:

##### Congestion level data:
- https://www.tomtom.com/en_gb/traffic-index/seattle-traffic/

##### Conditional work duration:
- used [the script](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/python/nhts_analysis/generate-city-data-from-NHTS.py) with `"{42660:0.6, '-':0.4}" .` parameters
> filtered for just the seattle CBSA (42660). Because the sample size there is pretty small I used an 60/40 blend of seattle and the US average by using {42660:0.6, ‘-’:0.4} as the first arg
>     ― Zach Needell

##### State and county codes:
- ~`Washington WA 53, King County 33, Snohomish County 61, Pierce County 53, Thurston County 67, Kitsap County 35`~
- `53`

##### Off-peak speed (transform miles per hour into meters per second):
- 20.56 meters per second (https://inrix.com/scorecard-city/?city=Seattle%20WA&index=130)


Notes:
1. ~on scratching counties, the map end up too big to optimize. Either we can remove those counties or remove footway and residential from the map before running the osmnx script. (TODO)~

**Comment by heyrutvik** [comment]
## scenario template folder (WIP)

repo: https://github.com/LBNL-UCB-STI/beam-data-seattle/tree/rrp/beam-issue-3310

**Comment by heyrutvik** [comment]
Current status:
The map we cropped is too big to [optimize](https://ec2-18-116-117-142.us-east-2.compute.amazonaws.com/doku.php?id=run_synthpop:optimize_map). We may want to consider removing one (or two) of the counties included.

**Comment by heyrutvik** [comment]
Update:
The optimization script doesn't spits out valid pbf file, even tried to reduce considered counties. Continuing with filtered pbf file for now.

**Comment by heyrutvik** [comment]
Summarizing work so far:

prototype: https://github.com/LBNL-UCB-STI/beam/compare/rrp/change-scenario-generator-to-create-blocks-csv-extended-border

1. changes to generate blocks csv for urbansim_v2 inputs
2. generate scenario files
3. use [python script](https://github.com/LBNL-UCB-STI/beam/files/7905991/convert.py.txt) to finalize csv formats
4. changes in beam to use configured (beam parameter) linkRadiusMeters for split operations
5. r5 changes to add public APIs to take linkRadiusMeters as method param, rather than predefined constant

**Comment by heyrutvik** [comment]
**CRS**: 32048

**population count** (see [complete log](https://github.com/LBNL-UCB-STI/beam/files/7922969/beamLog.out.txt)):
```
Number of households: 1130405
Number of of people: 1760193
```
**data repo**: https://github.com/LBNL-UCB-STI/beam-data-seattle

**1k population result**:  https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/seattle/seattle__2022-01-24_06-35-08_sgk

**doc edited**: 
1. https://ec2-18-116-117-142.us-east-2.compute.amazonaws.com/doku.php?id=new_scenario_generation:prepare_scenario_generator
2. https://ec2-18-116-117-142.us-east-2.compute.amazonaws.com/doku.php?id=new_scenario_generation:run_scenario_generator

**Comment by zneedell** [comment]
Just at first glance, the ratio of persons to households feels kinda low to me. Do these numbers include non-workers?

**Comment by heyrutvik** [comment]
@zneedell missed your comment earlier. 

> Do these numbers include non-workers?

No. These are after removing <16 age people and applying work force sampler. See following figures. `3967172` is the unfiltered number. 

```
14:00:49.801 [main] INFO  b.u.d.synthpop.PopulationCorrection$ - Read 1530636 households with 3967172 people
14:00:49.904 [main] INFO  b.u.d.synthpop.PopulationCorrection$ - After filtering them got 1530624 households with 3141680 people.
Removed 12 households and 825492 people who are younger than 16
14:00:51.226 [main] INFO  b.u.d.synthpop.PopulationCorrection$ - After applying work force sampler got 1150136 households with 1797137 people.
Removed 380488 households and 1344543 people
14:00:52.816 [main] INFO  b.u.d.s.SimpleScenarioGenerator - Total number of households: 1150136
14:00:52.928 [main] INFO  b.u.d.s.SimpleScenarioGenerator - Total number of people: 1797137
```

Do we want to generate unfiltered population files just as we did for New York?

**Comment by heyrutvik** [comment]
These are after removing <16 age people. See following figures.

```
23:23:01.403 [main] INFO  b.u.d.synthpop.PopulationCorrection$ - Read 1530636 households with 3967172 people
23:23:01.476 [main] INFO  b.u.d.synthpop.PopulationCorrection$ - After filtering them got 1530624 households with 3141680 people.
Removed 12 households and 825492 people who are younger than 16
23:23:04.155 [main] INFO  b.u.d.s.SimpleScenarioGenerator - Total number of households: 1530624
23:23:04.239 [main] INFO  b.u.d.s.SimpleScenarioGenerator - Total number of people: 3141680

...

00:13:33.072 INFO  b.u.d.s.SimpleScenarioGenerator$ - Number of households: 1498174
00:13:33.519 INFO  b.u.d.s.SimpleScenarioGenerator$ - Number of of people: 3060577
```

**plans s3 location**: s3://beam-outputs/new_city/seattle/scenario_files_elderThan16Years_withoutWorkSampling/

**Comment by heyrutvik** [comment]
Closed by https://github.com/LBNL-UCB-STI/beam/pull/3451
