### ISSUE TITLE
Tests: flaky tests

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3324]
We have a bunch of tests that from time to time not working.
We need to investigate the possible reasons behind this and make them more stable.
One of solutions - create a trait that will lead the flaky tests to rerun a number of times.

Here are links with related information:
https://gist.github.com/dwickern/6ba9c5c505d2325d3737ace059302922
https://stackoverflow.com/questions/22799495/scalatest-running-a-test-50-times

Some of flaky tests:

- `beam.integration.ChargingSpec`
- `beam.integration.CAVSpec`
- `beam.agentsim.infrastructure.ChargingNetworkManagerSpec`

**Comment by nikolayilyin** [comment]
21:18:39 beam.agentsim.infrastructure.ChargingNetworkManagerSpec *** ABORTED *** (0 milliseconds)
21:18:39   java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: beam.agentsim.infrastructure.ChargingNetworkManagerSpec
21:18:39   at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
21:18:39   at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
21:18:39   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
21:18:39   at scala.collection.Iterator.foreach(Iterator.scala:943)
21:18:39   at scala.collection.Iterator.foreach$(Iterator.scala:943)
21:18:39   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
21:18:39   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
21:18:39   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
21:18:39   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
21:18:39   at scala.collection.TraversableLike.map(TraversableLike.scala:286)
21:18:39   ...
21:18:39   Cause: com.typesafe.config.ConfigException$Parse: String: 2: Expecting end of input or a comma, got '@' (Reserved character '@' is not allowed outside quotes) (if you intended '@' (Reserved character '@' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
21:18:39   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
21:18:39   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
21:18:39   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:535)
21:18:39   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
21:18:39   at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
21:18:39   at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:262)
21:18:39   at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:250)
21:18:39   at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
21:18:39   at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
21:18:39   at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)

**Comment by nikolayilyin** [comment]
21:16:44 beam.integration.ChargingSpec *** ABORTED *** (0 milliseconds)
21:16:44   java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: beam.integration.ChargingSpec
21:16:44   at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
21:16:44   at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
21:16:44   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
21:16:44   at scala.collection.Iterator.foreach(Iterator.scala:943)
21:16:44   at scala.collection.Iterator.foreach$(Iterator.scala:943)
21:16:44   at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
21:16:44   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
21:16:44   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
21:16:44   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
21:16:44   at scala.collection.TraversableLike.map(TraversableLike.scala:286)
21:16:44   ...
21:16:44   Cause: com.typesafe.config.ConfigException$Parse: String: 7: Expecting end of input or a comma, got '@' (Reserved character '@' is not allowed outside quotes) (if you intended '@' (Reserved character '@' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
21:16:44   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
21:16:44   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
21:16:44   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:535)
21:16:44   at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
21:16:44   at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
21:16:44   at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:262)
21:16:44   at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:250)
21:16:44   at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
21:16:44   at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
21:16:44   at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)

**Comment by nikolayilyin** [comment]
12:34:24 - must result is message being transmitted back and forth *** FAILED *** (5 minutes, 0 seconds)
12:34:24   something went wrong with the co-simulation (BeamHelicsInterfaceSpec.scala:58)

**Comment by alex-vv** [comment]
`ParkingSpec`

```
- must guarantee at least some parking used  *** FAILED *** (2 minutes, 32 seconds)
   org.matsim.core.utils.io.UncheckedIOException: java.io.FileNotFoundException: /home/ubuntu/workspace/beam-forced-prs/output/test/beamville__2021-10-15_11-09-31_xhu/ITERS/it.3/3.events.xml
```
https://beam-ci.tk/job/beam-forced-prs/3332/consoleFull

**Comment by alex-vv** [comment]
`ActivitiesDurationSpec`

```
- should have fixed Other,Shopping and Work activities duration *** FAILED *** (23 seconds, 461 milliseconds)
 509.0 did not equal 260.0 all Shopping durations should be equal to 260.0 (ActivitiesDurationSpec.scala:73)
```

https://beam-ci.tk/job/beam-forced-prs/3537/consoleFull

**Comment by JustinPihony** [comment]
Was this closed in https://github.com/LBNL-UCB-STI/beam/pull/3429 ?

**Comment by alex-vv** [comment]
> Was this closed in #3429 ?

no, this was just for one test case not listed in this ticket

**Comment by nikolayilyin** [comment]
13:16:51 - should have fixed Other,Shopping and Work activities duration *** FAILED *** (23 seconds, 720 milliseconds)
13:16:51   509.0 did not equal 260.0 all Shopping durations should be equal to 260.0 (ActivitiesDurationSpec.scala:73)

failing in 1 of 4 attempts, the value from simulation if always higher than expected even if expected value is increased up to 1000

**Comment by g-derzhavets** [comment]
>11:35:48 PopulationAdjustmentSpec:
11:35:48 PopulationAdjustment
11:35:48 - should logs excluded modes defined as strings (318 milliseconds)
11:35:48 - should logs excluded modes defined as iterable *** FAILED *** (38 milliseconds)
11:35:48   ArrayBuffer((INFO,Modes excluded:)) was not equal to Array((INFO,Modes excluded:), (INFO,bike -> 5), (INFO,car -> 2)) (PopulationAdjustmentSpec.scala:120)
11:35:48 - should logs excluded modes and alarms not all persons have required attribute (3 milliseconds)

Fails often on CI, but always passes locally
