### ISSUE TITLE
Teleportation: investigation of RH mode

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3326]
There are modechoice events happening with the mod Car-rh-only:car_hov2 | Car-rh-only:car_hov3, the reason behind this, probably, in the existing hov modes from plans, but it is require some investigation.

**Comment by HoneyTauOverTwo** [comment]
I could not reproduce the issue. The output events for ``test/input/beamville/beam-urbansimv2.conf`` did not contain any instances of the string "Car-rh-only".
Changing config to ``beam.agentsim.agents.modalBehaviors.multinomialLogit.params.ride_hail_intercept = 1000.0`` did not produce those events either.

**Comment by nikolayilyin** [comment]
Not reproducible
