### ISSUE TITLE
Input consistensy check. Use default vehicle types if missing dummySharedCar, rhVehicleTypeId

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3328]
Following values should be present in the vehicleTypes file (beam.agentsim.agents.vehicles.vehicleTypesFilePath), but if they are not there then for them should be added default vehicle types.

beam.agentsim.agents.rideHail.initialization.procedural.vehicleTypeId
beam.agentsim.agents.vehicles.dummySharedCar.vehicleTypeId

Consistency check implemented for these values here https://github.com/LBNL-UCB-STI/beam/pull/3318 should be replaced with logging out error instead of throwing exception.

**Comment by JustinPihony** [comment]
I don't know that it should NOT fail, but instead factor empty/defaults accordingly. Re [this comment](https://github.com/LBNL-UCB-STI/beam/pull/3318#discussion_r718476153)

**Comment by nikolayilyin** [comment]
> I don't know that it should NOT fail, but instead factor empty/defaults accordingly. Re [this comment](https://github.com/LBNL-UCB-STI/beam/pull/3318#discussion_r718476153)

the first approach with failing seems to be too harsh, so, instead, we need to use default values if any of two required vehicle types are missing.
This issue is about adding the default values for vehicle types and using them.

**Comment by nikolayilyin** [comment]
closed by https://github.com/LBNL-UCB-STI/beam/pull/3339
