### ISSUE TITLE
Prepare sioux falls scenario for beam with documentation

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#333]
Utilities needed:
-> create single person household
-> create one car per houshold
-> script that creates TAZ (input: number of TAZ - cluster; simplest solution: grid).
-> how to convert from MATSim?

Prepare input files
-> osm network files
-> gtfs files -> is dummy file needed if not pt? -> provide one.
-> population (houshold, vehicles)
-> taz centers -> local coordinate system
-> population -> local coordinate s
-> network: wsg
-> 

create defaults
-> TAZ centers: if file missing - define single one dynamically
-> Parking: create unlimited parking supply dynamically
-> write out dynamic structures to file when created.
-> 

r5: provide pbf and at least one(?) transit zip.

with and without facilities file

**Comment by fdariasm** [comment]
### Matsim data conversion to BEAM:
- Input data:
   - Matsim network file: network.xml
   - Matsim population definition: Population.xml
   - OpenStreetMap data file, pbf format file. Can be taken from http://download.geofabrik.de/north-america.html
   - Matsim vehicle definition vehicles.xml (Optional)
   - Cartographic Boundary Shapefiles for region, dbf, shp, shx files (Optional, can be taken from https://www.census.gov/geo/maps-data/data/cbf/cbf_taz.html)
 
- Matsim conversion tool instructions:
	- Create folder for scenario in test/input inside project directory, e.g: siouxfalls
	- Create conversion-input folder inside scenario directory
	- Create r5 folder inside scenario directory
	- Copy network.xml file to scenario folder and rest of input data to conversion-input folder
	- Copy beam-template from /src/main/resources/beam-template.conf to scenario folder, rename to scenario name, e.g: siouxfall.conf
	- Edit siouxfall.conf
	 	- Look for matsim.conversion section and update as required:
		 	- scenarioDirectory = "D:/tmp/siouxfalls" -> destination folder, must be copied to test/input to run BEAM
		 	- populationFile = "Siouxfalls_population.xml" -> matsim population file name
		 	- generateVehicles = true -> If true conversion will use population data from above to generate default vehicles for agents
		 	- vehiclesFile = "Siouxfalls_vehicles.xml" -> If generateVehicles is false, specify matsim vehicles file name
		 	- defaultHouseholdIncome -> this data will be used for default household incomes
		 	- osmFile = "south-dakota-latest.osm.pbf" -> Open Street map source data file that should be clipped to scenario network
		 	- shapeConfig
		 		- shapeFile -> file name shape file package, e.g: for shape file name tz46_d00, there should be following files: tz46_d00.shp, tz46_d00.dbf, tz46_d00.shx
		 		- tazIdFieldName = "TZ46_D00_I" -> Field name for TAZ id in shape file
		- Look for beam.spatial section:
			- localCRS = "epsg:26914" -> CRS used for distance calculations, network, population and shape file must be in this format
			- boundingBoxBuffer = 10000 -> meters to pad bounding box around network
	- Run conversion tool
		- Main class to execute: beam.utils.matsim_conversion.MatsimConversionTool
		- Program arguments, path to beam config file from above, siouxfalls.conf: path/to/beam.conf
		- Environment variables: PWD=/path/to/beam/folder
		- Copy to clipboard osmosis command generated by conversion tool
	- Download and install osmosis tool from: https://wiki.openstreetmap.org/wiki/Osmosis
	- Run osmosis command from previous step, e.g:
		- osmosis --read-pbf file=/path/to/osm/file/south-dakota-latest.osm.pbf --bounding-box top=43.61080226522504 left=-96.78138443934351 bottom=43.51447260628691 right=-96.6915507011093 completeWays=yes completeRelations=yes clipIncompleteEntities=true --write-pbf file=/path/to/dest-osm.pbf
	- Point BEAM runner config parameter to bean config file, siouxfall.conf. Run simulation with generated data
