### ISSUE TITLE
Deploy on AWS: automatically specify the maxRAM value depending on the instance size

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3349]
We need an automatic way to choose the maxRAM value based on the instance type.
I think the best place for it - lambda function, so, we will get rig of specifying it on the client side (i.e. in the gradle function)
We need to have a list of instance descriptions (with instance type, all available memory, number of available cpu, maxRAM value) and then pick the value of maxRAM from this list according to instanceType specified in gradle command.

**Comment by JustinPihony** [comment]
Is the idea to maximize available RAM I assume? We need to leave some wiggle room for other system tasks though.

**Comment by nikolayilyin** [comment]
> Is the idea to maximize available RAM I assume? 

this, and to get rid of human factor errors.

> We need to leave some wiggle room for other system tasks though.

yes, and currently I am not sure how many RAM should we leave for system.
usually I am leaving something in between 5g to 20g depending on the instance size

@JustinPihony, do you have any suggestions ?

**Comment by JustinPihony** [comment]
Sorry for not responding sooner - I believe [Rajnikant's PR](https://github.com/LBNL-UCB-STI/beam/pull/3381) addresses this now

**Comment by nikolayilyin** [comment]
Right, it is addressing this issue
