### ISSUE TITLE
Freight: add a way to use different types of reader for freight plans

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3385]
Currently, in https://github.com/LBNL-UCB-STI/beam/pull/3384 there is a new freight input reader for new NREL input format, but, we need to be able to use old reader as well (probably we will need third reader in the future).
One needs to 
1. add a way to specify which reader should be used in simulation by specifying configuration value in the similar way as scenario reader do. 
2. restore old freight input reader as separate reader
3. fix tests for old reader in src/test/scala/beam/agentsim/agents/freight/input/PayloadPlansConverterSpec.scala
4. fix tests for old reader in src/test/scala/beam/agentsim/agents/freight/FreightReplannerSpec.scala

**Comment by alex-vv** [comment]
PR: https://github.com/LBNL-UCB-STI/beam/pull/3402
