### ISSUE TITLE
Health Metrics: send slack notification with health metrics as a part of original slack notification.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3388]
Having two messages about completion of simulation makes it hard to understand where is what.
Instead of sending two separate messages we need to have one message about completion of simulation with included healthMetrics file.
(Sending health metrics as file - an already good approach, we will have more lines in this file)

**Comment by JustinPihony** [comment]
Where is the other notification? I only see one in the #beam-deployment?

**Comment by nikolayilyin** [comment]
@JustinPihony, here is an example. the first message is health metrics, the second is regular update:
![image](https://user-images.githubusercontent.com/5393513/146024925-4619d7a3-ae63-46b5-9103-3163cf674484.png)

**Comment by edwazhao** [comment]
Hi @nikolayilyin , please help to review the PR here https://github.com/LBNL-UCB-STI/beam/pull/3697, in this PR it also contains change from https://github.com/LBNL-UCB-STI/beam/issues/3389
