### ISSUE TITLE
dataBranch in gradle.deploy.properties doesn't work

### ISSUE THREAD

**Issue by dgm90** [LBNL-UCB-STI/beam#3397]
I am trying to run `./gradlew deploy` on my branch `gd/new-york-dead-actors-debug` in `beam-data-newyork` repository and lambda doesn't pick it up and uses develop
`dataBranch=gd/new-york-dead-actors-debug`

I've run the deploy task and then ssh into instance to check the data branch commit - and it is from develop.

**Comment by JustinPihony** [comment]
@dgm90 I added a debug line just now - my machine is not set up to deploy currently and I have to take care of something else - however if you try again and then let me know the time (with timezone) that you ran it then I can debug a bit more later.

**Comment by dgm90** [comment]
I think I found the root cause. We have this line in the lambda function
`    data_branch = event.get('data_branch', DATA_BRANCH_DEFAULT)`

And here is what we have in `aws#build.gradle`
```
        def pload = """{
  "title": "${ext.getParameterValue('runName') + '_' + getCurrentGitUserEmail()}",
  "git_user_email": "${getCurrentGitUserEmail()}",
  "deploy_type_tag": "${ext.getParameterValue('deployTypeTag')}",
  "branch": "${ext.getParameterValue('beamBranch') ?: getCurrentGitBranch()}",
  "dataBranch": "$dataBranch",
```
so we always use the default (develop) branch. It is a simple fix and I will do it @JustinPihony

**Comment by JustinPihony** [comment]
Agreed - merged. I'm going to close this since it is merged, but re-open if needed
