### ISSUE TITLE
Write skims in binary format? Exploring options

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#3408]
Loading the skims is getting to be a big bottleneck for the SF-Bay PILATES implementation and will only get worse. It feels very non-optimal to be writing to .csv from BEAM, converting .csv->HDF5, and then reading HDF5 into ActivitySim.

The January library (https://github.com/eclipse/january) looks like it allows for the creating of numpy-like arrays on the JVM that can then be sent to HDF5 by the h5jan library (https://github.com/h5jan/h5jan-core). Since the skims are basically a bunch of square matrices, would this be a good application for that?

**Comment by dimaopen** [comment]
There's a related [ActivitySim skims: using OMX format](https://github.com/LBNL-UCB-STI/beam/issues/3232) issue.

**Comment by dimaopen** [comment]
PILATES uses OMX for skims. Closing this issue as a duplicate. Continue working within https://github.com/LBNL-UCB-STI/beam/issues/3232.
