### ISSUE TITLE
Documentation: add documentation for shared bikes repositioning functionality

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3422]
In this PR https://github.com/LBNL-UCB-STI/beam/pull/3243 functionality was added, we need documentation for the functionality.

**Comment by Xuan-1998** [comment]
@nikolayilyin Wondering where is a good place to document this? Is there a place we document reposition for other modes?

**Comment by nikolayilyin** [comment]
I thinks it might be put into 'docs/behaviors.rst', there is already 'Parking' and 'Refueling', `Repositioning` might be there too

**Comment by Xuan-1998** [comment]
ready to review
