### ISSUE TITLE
Error: Customer has made two RideHail Inquiries

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#3426]
20:42:39.488 ERROR b.a.agents.ridehail.RideHailManager - Customer 016801-2012001020283-0-7430620 has made two RideHail Inquiries, with the departAt for the second being before or equal to the first: (27000 < 25600. This is likely to cause logical errors.

**Comment by dimaopen** [comment]
I fixed it by validating the order of RH inquiries. But I didn't quite get: if we have multiple RH inquiries but store in the cache only the latest response how we can be sure that the customer goes with the latest one later when they are reserving a ride?

**Comment by haitamlaarabi** [comment]
I have just answered your question in #3432
