### ISSUE TITLE
Move all utilities into an upper level folder for easier discovery

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#3445]
Utilities that use `extends App` or defines `main(args: String[])` to be run standalone should probably be moved to an upper folder so they are all easily discovered

**Comment by dimaopen** [comment]
To me, it looks like a good idea. I would suggest grouping the utilities to packages within that upper folder.

**Comment by nikolayilyin** [comment]
We have few scripts in that path - src/main/scala/scripts
Looks like a good place for the rest of them.
