### ISSUE TITLE
Routing Vehicle in Heavy-Duty Vehicle category along specific roads

### ISSUE THREAD

**Issue by haitamlaarabi** [LBNL-UCB-STI/beam#3448]
Heavy Duty Vehicles do not travel along certain roads. There are two steps to achieve this task:
1- Customize the router to filter only links that are flagged for HDV
2- Identify the links that are only HDV (e.g. look into OSM data, Graphhopper uses OSM tags translated to link cost functions per vehicle type..). Be aware that the sub road network should be connected and not disconnected (due to the filtering).

**Comment by heyrutvik** [comment]
We do not have specific PR for this as it was merged into its parent work. Here is the revision link https://github.com/LBNL-UCB-STI/beam/commit/a62850bdd5cc9984747bf340edf6bf0338722493

The idea is following: mark matsim link with hgv flag and take it into account while calculating travel time cost such a way to increase the chances of heavy duty vehicle to pick hgv link over regular links.
