### ISSUE TITLE
AWS: Save current git branch commit and git data branch commit into spreadsheet 

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3449]
In order to be able to reproduce past simulations we might need to save into spreadsheet the real git branch commit (in case a simulation was started without specifying a commit hash) and git data branch commit.

An example of simulations started without specifying a commit hash
![image](https://user-images.githubusercontent.com/5393513/150311419-c7f77afd-c559-46d5-b3d5-6cd2984d0fa5.png)

**Comment by JustinPihony** [comment]
`git log -1 --pretty=format:"%H"` will pull the current hash so that it can be used.
