### ISSUE TITLE
passengerPerTripSubway.csv contains duplicate columns

### ISSUE THREAD

**Issue by g-derzhavets** [LBNL-UCB-STI/beam#3457]
When the data for `0.passengerPerTripSubway.csv` is empty (meaning only zero numbers), then there are duplicate columns (header=1-0) in the file.

![image](https://user-images.githubusercontent.com/98255053/151694679-f7dc8cc8-1fcf-4133-bd17-7c8d0998b75b.png)

We should fix this and only print 1 column.

**Comment by HoneyTauOverTwo** [comment]
Would this be the desired output?

![IsDesirableOutput](https://user-images.githubusercontent.com/31476381/189398628-9e60bf74-5b50-493b-824d-ea15649b7082.PNG)

If that is, the fix is quite simple.
