### ISSUE TITLE
Snap coordinates from input scenario to the map after reading

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3489]
To avoid discrepancy between coordinates and a map replace coordinates in input plans/trips/households with the result of r5 snap function. 
A good idea might be to count, or even write out into csv file all coordinates that can not be used (e.g. - split function returning nothing or coordinates are outside of map bounding box)
For filtered out coordinates according input element (household/trip) should not be included in scenario.

There is already a place where filtration by bounding box happens, it needs to be improved:
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala#L62
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala#L87

**Comment by heyrutvik** [comment]
Use `beam.agentsim.snapLocationAndRemoveInvalidInputs` parameter to enable the snapping module. It will snap location and remove invalid plans (beam, urbansim, freight) before starting simulation.

Error csv can be found at the root of output directory:
1. `snapLocationPlanErrors.csv`: scenario plan errors
2. `snapLocationHouseholdErrors.csv`: scenario household errors
3. `snapLocationFreightTourErrors.csv`: freight tour errors
4. `snapLocationFreightPayloadPlanErrors.csv`: freight payload plan errors
5. `snapLocationFreightCarrierErrors.csv`: freight carrier errors

Csv will have `id,category,error,x,y` columns.
`error` could be either `OutOfBoundingBox` and `R5SplitNull`.
`category` defines the type of an entity for given id. (ex, Person, Household, PayloadPlan etc)
`x` and `y` is original location in plan.
