### ISSUE TITLE
Router Modifications

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#35]
I will add minor mods to this issue as I work through using R5 in the agentsim.

In class RoutingModel, please made the default timeFrame be a parameter in the configuration file.

**Comment by colinsheppard** [comment]
In R5RoutingWorker, I created a magic val localDateAsString (see agentsim branch after I complete a refactor this week). This should be specified in the config file.

**Comment by colinsheppard** [comment]
In R5RoutingWorker.buildResponse there is a line where you capture the time of each itinerary segment like this:

  ` BeamLeg(itinerary.startTime.toEpochSecond, access.mode match {
`
But this yields the time in seconds since 1970, we need seconds since midnight of that day. Please subtract away the date from localDateAsString mentioned above (which will also need to be converted into seconds since 1970) in get seconds today. While doing this, we need to think about how to manage routing requests that take place past the first day of the simulation. 

E.g. if the localDateAsString is '2016-10-01' but the departureTime is 90000, which is 1am on the second day of the simulation, then we need to make sure that the appropriate date is provided to profileRequest.date and that the conversion back from itinerary.startTime get's the date correct as well.

**Comment by zishanbilal** [comment]
I have incorporated the feedback and also reviews your code in agentsim, both are logically same. I just used bean config as you instructed in this issue. 

Work is completed from my side.
