### ISSUE TITLE
Debugging: when simulation is terminated do a thread dump into a file.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3550]
Recently we introduced a functionality to terminate simulation if there was no progress for configured time (#3539)
In addition to this functionality it would be helpful to have a thread dump at the time of ending BEAM and the content of the scheduler queue.
We need that dump in the file in the output folder, so, it will be moved into s3 output folder with the rest of the files.

**Comment by dimaopen** [comment]
`triggerQueue` should be dumped in priority order
`awaitingResponse`: only values could be dumped
we could just call `toString` method on each entry.

**Comment by nikolayilyin** [comment]
Also it might be a good idea to turn-on by-default the functionality to terminate BEAM if there is no progress in 3 hrs.
