### ISSUE TITLE
Beam Run Spreadsheet - add a status to a run in the simulations spreadsheet.

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3567]
Currently in [the simulations spreadsheet](https://docs.google.com/spreadsheets/d/1IV-DmD62vtTTWm0y97TcgpHw5n7ITdEYnETt6QGRw5g/edit#gid=0) we have two rows per each simulation: one with 'Run Started' and one with 'Run Completed' in the first column.
![image](https://user-images.githubusercontent.com/5393513/181289084-e6436695-26f2-430f-b800-a9870e0c1524.png)

But sometimes BEAM is failing and sometimes not even able to start (because of dependencies or because of compilation failure or other things)

What we need - to change 'Run Completed' text based on actual simulation status:
- if last row of beamLog.out contains 'Exiting BEAM' then the text should be 'Run Completed'
- if last row of beamLog.out is different - the text should be 'Run Failed'
- if there is no beamLog.out because simulation has failed to start - the text should be 'Unable to Start'

**Comment by g-derzhavets** [comment]
Fixed
