### ISSUE TITLE
Beam Stuck Guard: an improvement for bigger simulations

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3576]
We need to reduce the timeout up to 2 hours (or similar value) but it makes impossible for big runs to complete initialization phase.
The solution might be following: add 'completed' messages for each big initialization phase.

This is [a log of recently killed big simulation](https://beam-outputs.s3.amazonaws.com/output/sfbay/gemini-scenario-7-Advanced__2022-08-01_04-49-02_zth/beamLog.out) - there are two rows with 5 hours interval between them - we need to investigate if it is possible to add progress logs to this part.

Also we need to check if other parts require additional progress reports (to figure this out - we need to look at similar log from completed simulation of similar size)

**Comment by nikolayilyin** [comment]
Also a helpful thing will be to have timeout configurable via gradle parameter with default value set to 2 (or any other sensible value)
Probably we should not kill an instance if CPU activity is significant because no one saw endless loops in BEAM so far (it is not a proof we don't got one, but probability seems to be low)

**Comment by nikolayilyin** [comment]
The stuck guard is a shell script, it's content is here - https://github.com/LBNL-UCB-STI/beam/blob/develop/aws/src/main/python/beam_lambda/lambda_function.py#L137

**Comment by edwazhao** [comment]
Hi @nikolayilyin , could you please help to review the PR https://github.com/LBNL-UCB-STI/beam/pull/3630

**Comment by edwazhao** [comment]
New PR https://github.com/LBNL-UCB-STI/beam/pull/3644
