### ISSUE TITLE
Profiling of BEAM simulation - RAM

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3609]
We need to do a general profiling of RAM usage:
1. Check if there are any memory leaks
2. Figure out which code areas are the main source of memory usage
3. Figure out which simulation steps are the main source of memory usage

In order to do so one needs to do profiling of small simulation locally (beamville, sf-light) and then work on profiling of big runs.
There is a tool to check if there are memory leaks is in beam, probably it is required to be upgraded.
The config key to turn the tool on: beam.debug.vmInformation.createGCClassHistogram

**Comment by nikolayilyin** [comment]
There is a CPU/RAM usage graph for each simulation run on AWS during last months (for example - [cpu_ram_usage.csv.gz](https://beam-outputs.s3.amazonaws.com/output/sfbay/gemini-base-2035-activitysim__2022-09-05_06-08-38_bun/cpu_ram_usage.csv.gz))
We could analyze at which point in time what usage of RAM there was with the help of this graph and the log

**Comment by Xuan-1998** [comment]
@nikolayilyin Did we figured out:
1.Figure out which code areas are the main source of memory usage
2.Figure out which simulation steps are the main source of memory usage
What's the answer for these two?

**Comment by Xuan-1998** [comment]
![image](https://user-images.githubusercontent.com/58761221/200680481-4ffb9e0e-afd6-42d4-aa3d-5f9111f69148.png)
Is it possible to update beam.debug.vmInformation.createGCClassHistogram to produce CPU and Mem usage for different FSM? @nikolayilyin
