### ISSUE TITLE
Preparations for clean-up of AWS storage: simulations spreadsheet

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3611]
Probably we need to create a jupyter notebook (something like beam:jupyter/utility/simulations_output_analysis.ipynb)
with the code to read all the simulations from the simulations spreadsheet and check which of the output paths are still exist on AWS S3 storage. 
This list then needs to be grouped by projects/people in order to ask for keeping/deleting the output.

**Comment by edwazhao** [comment]
Hi @nikolayilyin , I have created a PR https://github.com/LBNL-UCB-STI/beam/pull/3643 to the current issue. And here is an example result csv file:
[issue3611_output.csv](https://github.com/LBNL-UCB-STI/beam/files/9830054/issue3611_output.csv)

**Comment by edwazhao** [comment]
PR https://github.com/LBNL-UCB-STI/beam/pull/3643 merged
