### ISSUE TITLE
CPU\RAM usage: check if data collected on the instance are close to the data collected from outside

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3614]
For latest simulations on AWS we have cpu_ram_usage graph with data collected from inside of the instance in the root of the output folder, for some of the same runs we have CPU and RAM usage collected from outside of the instance, they are stored [here](https://s3.console.aws.amazon.com/s3/buckets/beam-cpu-usage-history?region=us-east-2&tab=objects).

We need to check if the data collected from the inside are close to the data collected from the outside.

**Comment by nikolayilyin** [comment]
the link to the spreadsheet with simulations - https://docs.google.com/spreadsheets/d/1IV-DmD62vtTTWm0y97TcgpHw5n7ITdEYnETt6QGRw5g/edit#gid=0, the link to the output is in column 'S3 Url'

**Comment by alvinlee001** [comment]
Upon testing a few samples, 9/10 has a +- 1% deviation in differences between the 2 sources.

Below are the results:


[result.csv](https://github.com/LBNL-UCB-STI/beam/files/9567457/result.csv)


The source files and a python script can be found inside to get the results again, i.e.:

`python3 getMean.py -f test10/cpu*.csv -c 'CPU usage'`

`python3 getMean.py -f test10/09_05_2022_17_42_20_i-03d6a4fd2c4ec06f7_0.4pop-gemini-default_j503440616ATberkeley_edu.csv -c 'Average`


[BEAM_files.zip](https://github.com/LBNL-UCB-STI/beam/files/9567463/BEAM_files.zip)
