### ISSUE TITLE
Script commands are to be updated

### ISSUE THREAD

**Issue by dimaopen** [LBNL-UCB-STI/beam#3622]
Scripts like `scripts.BeamScenarioDataExtractor` were moved to the `scripts` package. The corresponding commands in the inline documentation (and also in the rst files) should be updated.
Now we have the old packages in the documentation.
`./gradlew :execute -PmainClass=beam.utils.data.synthpop.BeamScenarioDataExtractor`

**Comment by nikolayilyin** [comment]
closed by #3626
