### ISSUE TITLE
Clean temporary map files in the beginning of a simulation

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3647]
The temporary map files creates issues when they are created with a code from old branches, but in some scenarios having these temporary files will give a performance boost if multiple simulations is needed to be run.
The idea is the following:
1. add a config key 'keepMapTemporaryFiles' under `beam.routing` with default value `False`
2. add code which will in the beginning of simulation clean following files from their paths if the config key not set to True: 'network.dat', 'osm.mapdb', 'osm.mapdb.p', 'physsim-network.xml'  from 'beam.routing.r5.directory' and from 'beam.routing.r5.directory2' if present.

**Comment by dimaopen** [comment]
It will cause deleting the files in the most cases. It may impact beam run time.

**Comment by alex-vv** [comment]
After a discussion we decided it is not worth it, because this setting will break concurrent tests and will have no benefits for simulation runs on AWS.
