### ISSUE TITLE
Amazon vs Google cloud: comparison

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3652]
There are three parts of the issue:
1. to figure out the cost difference between google cloud and amazon cloud
2. to figure out if it is possible to use google cloud instead of amazon cloud
3. to figure out how much effort it will cost us to move from one cloud to another

**Comment by dimaopen** [comment]
Prices on compute resources: https://docs.google.com/spreadsheets/d/1IySE3xUrBANUBSvD2DNjm7Zdk-61CROs9ZvgM_o8u9M/edit#gid=0
Google Cloud looks a little bit cheaper.

**Comment by dimaopen** [comment]
Technology | Name | Description
--- | --- | ---
CLI tool	| gcloud |	It's possible to create/start VMs inclusing the startup scripts in differen languages
Python Client for Compute Engine | google-cloud-compute | Python API
Function as a Service | Cloud Functions | Run code in the cloud with no servers or containers to manage
Google Compute Engine Client for Java | https://github.com/googleapis/google-cloud-java/tree/main/java-compute | Can be used to create/start/stop VMs from gradle
Google Cloud Functions Client for Java | https://github.com/googleapis/google-cloud-java/tree/main/java-functions | Can be used to run Cloud Functions from gradle

**Comment by dimaopen** [comment]
To fully replace the existing features that we have built for Amazon we need to rewrite most of [the aws module](https://github.com/LBNL-UCB-STI/beam/tree/9d5f8a69885177b28b1f0143c10008b81d1fe7ce/aws). I would roughly estimate it to 2-4 weeks for a single developer.

**Comment by dimaopen** [comment]
What's [implemented](https://github.com/LBNL-UCB-STI/beam/tree/do/%233652-execute-beam-on-google-cloud-compute):

- Gradle `deployToGCE` task
- Getting the sources, executing, uploading to the cloud storage
- Instance deleting.

What needs to be implemented:
- The rest of deploy parameters (`profiler_type`, ~~`s3Backup`~~, ...)
- Transferring ~~`GOOGLE_API_KEY`~~ (other keys?) to the GCE instances
- ~~Automatic `maxRAM` calculation~~
- Zip and upload JFR files to the storage
- ~~Return the instance name (and other info like in `deploy` task) back to the user~~
- Saving run data to the [BEAM Deploy Status doc](https://docs.google.com/spreadsheets/d/1IV-DmD62vtTTWm0y97TcgpHw5n7ITdEYnETt6QGRw5g/edit#gid=0)
- Slack notifications (channels `aws-notifications`, ~~`beam-deployment`~~)
- Running Jupiter
- Running Grafana
- Running Helics
- Running file browser
- Budget control ?
- Executing multiple configs, experiments ?
- Anything missing...
