### ISSUE TITLE
UNEXPECTED: there should be mapped split location error

### ISSUE THREAD

**Issue by dimaopen** [LBNL-UCB-STI/beam#3661]
Config `production/sfbay/smart2/sfbay-base.conf` produces a huge amount of the following logs:
`ERROR b.u.scenario.ScenarioLoaderHelper$ - UNEXPECTED: there should be mapped split location for [x=565839.298829913][y=4185395.738014901] coord.`
We need to research why it happens and solve it.

**Comment by edwazhao** [comment]
Hi @dimaopen , I have tried the config `production/sfbay/smart2/sfbay-base.conf` with latest develop branch, but I cannot reproduce the error log, could you please help to point out which simulation you are using or do I miss something with the config?

**Comment by dimaopen** [comment]
@edwazhao Probably this issue was fixed indirectly. The last run that I could found with these lines in the output is https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/sfbay/sfbay-smart2__2022-10-23_02-44-15_jly/
