### ISSUE TITLE
Bug: Race condition in transit initialization

### ISSUE THREAD

**Issue by zneedell** [LBNL-UCB-STI/beam#3667]
It appears that the scheduler does not wait until the initialization of the transit schedule is completed before letting the rest of the simulation start running. This shows up in some production scenarios with big transit systems, especially NYC.

This can be replicated in beamville (and presumably the other scenarios) by setting a breakpoint in `initDriverAgents()` here: https://github.com/LBNL-UCB-STI/beam/blob/09ddf870347991388dc2234c9321bafeb5a43705/src/main/scala/beam/agentsim/agents/TransitSystem.scala#L74 and waiting a bit before continuing -- the simulation breaks and all the agents go to error.

**Comment by dimaopen** [comment]
I reproduced this issue. I think it happens because the StuckFinder is enabled. It terminates the "stuck" agents. If we disable it then Beamville works fine.
