### ISSUE TITLE
Simplification of 'beam deploy' lambda code

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3699]
Currently there are two ways to run multiple simulations on AWS with one deploy command - to run one simulation per instance and to run multiple simulations one by one on the same instance.
The second way is not used anymore, removing the code for it will make lambda code easier to work with.

The goals of this issue:
1. remove according code from aws/src/main/python/beam_lambda/lambda_function.py
2. remove according code from deploy command (if there is anything related)

**Comment by edwazhao** [comment]
Please review the PR https://github.com/LBNL-UCB-STI/beam/pull/3715/files
