### ISSUE TITLE
Create implicit class ExtendedBeamConfig for custom static properties

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#37]
GanttStart: 2017-10-01

**Comment by dserdyuk** [comment]
@colinsheppard  do need to add there some spicific properties ? i can't recall from original discussion

**Comment by colinsheppard** [comment]
I can't recall now... but an example will surely come up in the near future.

**Comment by dserdyuk** [comment]
Alright. I've added an implicit class in beam.sim.config.ConfigModule. Make sure you added import to activate implicit 
` import beam.sim.config.ConfigModule._ `
