### ISSUE TITLE
PWD in tests - a possible problem for windows users

### ISSUE THREAD

**Issue by nikolayilyin** [LBNL-UCB-STI/beam#3701]
In few tests a `$pwd` variable is used and for windows users this variable is not working.
We need to either configure something (windows or IDEA) in order for this variable to work and create a documentation entry about the configuration or, if impossible, we need to get rid of this variable and replace it with something OS-independent.

**Comment by edwazhao** [comment]
Please review https://github.com/LBNL-UCB-STI/beam/pull/3705
