### ISSUE TITLE
Incorrect pattern matching in PersonAgent.scala

### ISSUE THREAD

**Issue by HoneyTauOverTwo** [LBNL-UCB-STI/beam#3746]
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L961:

```
data @ BasePersonData(
            _,
            _,
            currentTrip @ headOfCurrentTrip :: restOfCurrentTrip,
            _,
            _,
            _,
            _,
            _,
            _,
            _,
            currentCost,
            _,
            _,
            enrouteData
          )
```

`currentCost` is positioned to match [`BasePersonData.numberOfReplanningAttempts (int)`](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L194) instead of [`BasePersonData.currentTripCosts (double)`](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/PersonAgent.scala#L193)

The fix for this should also include a test to make sure this is set properly.

**Comment by dimaopen** [comment]
This defect seemed to be fixed.
