### ISSUE TITLE
BEAM Must be Runnable in Offline Mode

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#39]
The transitVehicels.xml cannot be loaded when offline, this prevents anyone from developing or using BEAM without an active internet connection. This needs to be fixed and is a high priority. For example, I'm traveling on flights for 8 hours today and I had planned to do work in flight and won't be able to now.

GanttStart: 2017-10-01

**Comment by colinsheppard** [comment]
To be more clear. If you run offline currently, it works. But it pauses when trying to download DTD files from the web, e.g.:


```
2017-07-19 12:27:34,021  INFO ScenarioLoaderImpl:307 loading transit vehicles from transitVehicles.xml
2017-07-19 12:27:34,022  INFO MatsimXmlParser:155 starting to parse xml from url file:/Users/critter/Dropbox/ucb/vto/beam-developers/model-inputs/dev/transitVehicles.xml ...
2017-07-19 12:27:34,025  INFO MatsimXmlParser:269 Trying to load http://www.matsim.org/files/dtd/vehicleDefinitions_v1.0.xsd. In some cases (e.g. network interface up but no connection), this may take a bit.
```
But this adds ~20 seconds to every run of the model, which is a lot when trying to do rapid development and/or debugging. So instead, I want to be able to specify local DTD or schema files that get loaded quickly. For the other MATSim inputs (e.g. population and network) I can do this, but for transit vehicles I cannot.

**Comment by colinsheppard** [comment]
Final note, this is an example of how I modified the header of the network file to make the files source from a local path instead of downloaded:

```
<!DOCTYPE network SYSTEM "network_v1.dtd">
<!--<!DOCTYPE network SYSTEM "http://matsim.org/files/dtd/network_v1.dtd">-->
```

**Comment by dserdyuk** [comment]
wow. I've missed this issue. I will remove remote schema where possible

**Comment by colinsheppard** [comment]
I figured out how to do this at least for DTD's located in our shared google drive. 

See:
model-inputs/dtd/

and for examples of how to refer to these dtd's:
model-inputs/dev/transitVehicles.xml
model-inputs/dev/population.xml

Note that we still will need to edit the .xsd files to make the namespaces and paths all relative, but I've done this already for the ones we're using (e.g. vehicleDefinitions_v1.0.xsd).
