### ISSUE TITLE
Create R^5 Router

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#4]
Create a class analogous to:

https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/agentsim/routing/opentripplanner/OpenTripPlannerRouter.scala

but make this one use R^5:

https://github.com/conveyal/r5

The contract for this router is such that it must be able to receive these messages / return these responses:

`InitializeRouter responding with RouterInitialized
RoutingRequest(fromFacility, toFacility, departureTime, personId) responding with RoutingResponse`

While doing this, refactor the case classes in the OpenTripPlannerRouter companion object that are more general than OpenTripPlannerRouter. Put them into something more generic, like beam.agentsim.routing.BeamRouter.

**Comment by colinsheppard** [comment]
On the request message:

For now let's send in the request 2 pieces of information:

considerTransit: Boolean
accessModes: Vector[beam.agentsim.core.Mode]

The accessModes should be one of CAR, BIKE, WALK

You can start by assuming that considerTransit is FALSE and then you can just use a PointToPointQuery (with multiple Modes identified in the request)

**Comment by zishanbilal** [comment]
Create a time class with two specializations, one for fix time and the other for based window time. Request would support the generic time and would remain same for both otp and r5 and at run-time API caller would pass it dynamically. 

> Note: Default time for window would be 15 minutes.
