### ISSUE TITLE
Improper handling of InterruptedException - Should not be swallowed

### ISSUE THREAD

**Issue by carloscaldas** [LBNL-UCB-STI/beam#449]
> Only code that implements a thread’s interruption policy may swallow an interruption request. General-purpose task and library code should never swallow interruption requests.
 _"Java Concurrency In Practice" by Brian Goetz_

Inappropriate a can lead to Thread leaks, infinite loop and other thread related issues.

The following snippet of code of code:

```Java
} catch (InterruptedException e) {
    log.info("got interrupted while waiting for errorHandler to die.", e);
}
```

Should be replaced by the following snippet of code:
```Java
} catch (InterruptedException e) {
    Thread.currentThread().interrupt();
    log.info("got interrupted while waiting for errorHandler to die.", e);
}
```

**Comment by colinsheppard** [comment]
Where exactly are we handling InterruptedException?
