### ISSUE TITLE
Complete Traveling Implementation

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#48]
See:
http://beam.readthedocs.io/en/agentsim-drives-vehicle/protocols.html

And note that work is already under way under PR:

https://github.com/LBNL-UCB-STI/beam/pull/44

GanttStart: 2017-08-06
GanttDue: 2017-08-11

**Comment by colinsheppard** [comment]
New subtasks:

1. Re-integrate Reservation request handling in BeamVehicle (from earlier work by @dserdyuk), should forward to the driver if a driver exists and buffer requests if no driver present (then unwind the buffer when a driver appears).
2. Re-integrate Reservation handling in DrivesVehicle (also based on earlier work by @dserdyuk). 
3. Append to vehicle trajectory rather than replace
4. Fix Actor creation "props" in BeamVehicle to take the concrete class, not trait.
5. Make sure all indices of Objects and ActorRefs in BeamServices are actually being built.

**Comment by dserdyuk** [comment]
@colinsheppard subtasks have been done. The only problem was with personId-> vehicleId convertion.. I had to add "body-" prefix for humanbody vehicleId because the is overlap between person's and real vehicle ids. It leads to actor name duplication error.

**Comment by dserdyuk** [comment]
@colinsheppard please review and close it if there is no addition subtask. it looks finished for me.

**Comment by colinsheppard** [comment]
@dserdyuk 

I can now confirm that we have agents moving around successfully in the model, but only for walking and driving. I need to work through any issues for public transit, which will also coincide with resolving issue #51, so getting close.
