### ISSUE TITLE
diagnose why replanning not sensitive to parking pricing

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#500]
I recently set to "ignore" "ParkingSpec:expensive parking should reduce driving" because the price signal from the parking wasn't producing clear decreases in use of CAR mode.

I can see the prices reflected in the plan scores, but more work is needed to understand why the test isn't fully passing.

One hypothesis, maybe more iterations are needed.... we could allow the run to go 20 or 30 iterations for just the "default" and "expensive" scenarios and if we get the expected decrease, re-enable this test.

**Comment by fdariasm** [comment]
This will be solved when #858 is done
