### ISSUE TITLE
Tests contain expensive eager construction

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#528]
ScalaTest instantiates tests as part of discovery. All val in the constructor should be lazy.

**Comment by michaz** [comment]
@JustinPihony Does ScalaTest free tests that have run for GC? If not, we'll end up with the same maximum heap size in the end, right?

**Comment by JustinPihony** [comment]
@michaz The problem was the instances spun up on this discovery were just thrown away and then re-created when the tests actually were used - causing double processing. So, the heap wasn't the issue - it was the processing time. We shouldn't have any timely instantiations in anything but lazy val or pre-start methods to avoid this.

**Comment by michaz** [comment]
Arrrgh, I see. Thanks.
