### ISSUE TITLE
Build Simple PhySim wrapper

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#55]
Use base version of JDEQSim wrapped in an Actor.

GanttStart: 2017-08-06
GanttDue: 2017-08-14

**Comment by wrashid** [comment]
A JDEQSim instance wrapped behind an actor has been implemented. See example in branch "physsim-jdeqsim-performance", class   beam/src/main/java/beam/playground/jdeqsim/akka/ActorVersionJDEQSimMain.java
