### ISSUE TITLE
stuckAgentDetection default parameters not properly included in BeamConfig

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#558]
![image](https://user-images.githubusercontent.com/13569531/45331304-c5624c00-b51e-11e8-931f-9ce6427b2aba.png)

just the first value for RideHailManager$RideHailAllocationManagerTimeout is included

during config generation there is even a warning about this:

line 113: [{"markAsStuckAfterMs":"duration:ms | 40s","triggerType":"beam.agentsim.agents.ridehail.RideHailManager$RideHailAllocationManagerTimeout"},{"markAsStuckAfterMs":"duration:ms | 20s","triggerType":"beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegEndTrigger"},{"markAsStuckAfterMs":"duration:ms | 60s","triggerType":"beam.agentsim.agents.PersonAgent$ActivityEndTrigger"},{"markAsStuckAfterMs":"duration:ms | 20s","triggerType":"beam.agentsim.agents.ridehail.RideHailManager$BufferedRideHailRequestsTimeout"},{"markAsStuckAfterMs":"duration:ms | 18s","triggerType":"beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger"},{"markAsStuckAfterMs":"duration:ms | 20s","triggerType":"beam.agentsim.agents.PersonAgent$ActivityStartTrigger"},{"markAsStuckAfterMs":"duration:ms | 20s","triggerType":"beam.agentsim.agents.InitializeTrigger"},{"markAsStuckAfterMs":"duration:ms | 20s","triggerType":"beam.agentsim.agents.PersonAgent$PersonDepartureTrigger"},{"markAsStuckAfterMs":"duration:ms | 21s","triggerType":"beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegStartTrigger"},{"markAsStuckAfterMs":"duration:ms | 60s","triggerType":"beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger"}]: only first element will be considered
   

side question: is there a way to avoid that we have to include the following block in our config?

beam.debug.stuckAgentDetection {
  enabled = false
  thresholds = []
}

**Comment by REASY** [comment]
Solved in https://github.com/LBNL-UCB-STI/beam/pull/561
