### ISSUE TITLE
R5RoutingWorker in remote mode should initialize transits in constructor

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#591]
This will simplify the flow. New workers can just join the cluster, no need to have special code to treat uninitialized workers.

**Comment by JustinPihony** [comment]
I was thinking about having a flow of "Initializing, Initialized, ReadyForWork", but if we can do it in the startup itself then that simplifies that :)

**Comment by REASY** [comment]
Solved in https://github.com/LBNL-UCB-STI/beam/pull/593
