### ISSUE TITLE
fix issue: log error if wrong/non existing taz file name provided

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#627]
input was: taz-centers.csv.gz but the actual file was taz-centers.csv -> no warning /error came

**Comment by wrashid** [comment]
see beam.agentsim.taz.file

**Comment by bhavyalatha26** [comment]
@wrashid the code picks up a default whenever an invalid taz file path is provide in the conf file .
Should we now remove the default mapping and throw exception for an invalid file path ? 

Please Ref : BeamServices.scala  - line 115
