### ISSUE TITLE
Travel Time Override Interface

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#638]
Sometimes users of BEAM will have good data on travel times and be uninterested in simulating traffic / brining the system to equilibrium.

To facilitate this, please create an interface that looks like this:

overrideTravelTimeAndCostFor(origin,destination,departureTime,mode): TimeAndCost

case class TimeAndCost(time: Option[Int], cost: Option[Double])

Then, for every EmbodiedBeamTrip created in R5RoutingWorker, this interface should be called.

If None is returned, then the trip remains unchanged.

If values Some values are returned, then we use those to replace the defaults. 

In the case of cost, this should probably be done at the trip scale. I.e. we set to 0 all of the costs within the legs and then pick one of them to change to the cost returned by the interface (the choice of which leg to set can be approached on a mode by mode basis). 

In the case of travel time, we need to update the overall trip duration (i.e. by updating endPoint.time) as well as the individual link durations. The link durations should simply be scaled so the sum reflects the new travel time but the relative duration of each link to each other remains the same.

The default behavior for this will be to return TimeAndCost(None,None).

**Comment by REASY** [comment]
Closed by https://github.com/LBNL-UCB-STI/beam/pull/948
