### ISSUE TITLE
Scenario Loader Appears to Load 3X

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#64]
GanttStart: 2017-10-01
GanttDue: 2017-10-15

It looks like the matsim loading is happening three times instead of one. Maybe somehow related to our BeamConfig classes?

**Comment by dserdyuk** [comment]
I did quick debug test, it looks like Guice module has been installed several times in RunBeam when we create injector, which triggers scenario loading multiple times. we can workaround it by loading of scenario in separate variable to init it ones

**Comment by colinsheppard** [comment]
Looks like this is fixed.

**Comment by dserdyuk** [comment]
yes in  77cc0cdf930e611225b6bb84b95291d24aaf4f57
