### ISSUE TITLE
Standardize Coordinate Spec

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#7]
We need a standard way of specifying coordinate system for model inputs and outputs, analogous to our system for units (#6)

We should convert everything to UTM internally to enable more accurate distance calculations. The specific UTM zone to use should be user configurable, but if not specified by the user, then default behavior should be to auto-detect the best zone based on the location of the centroid of the network.

GanttStart: 2017-10-01

**Comment by dserdyuk** [comment]
I'll try to gather some info about what kind of MATSim config contains coords and what we really use.

**Comment by colinsheppard** [comment]
See here for how MATSim manages this. 

https://github.com/matsim-org/matsim/blob/master/matsim/src/main/java/org/matsim/core/network/io/MatsimNetworkReader.java

https://github.com/matsim-org/matsim/blob/master/matsim/src/main/java/org/matsim/core/network/io/NetworkReaderMatsimV2.java

What I dislike is that the coordinate reference system is specified in the config file. Much better if we add it to the data itself and automatically transform as we read from external sources. Ideally, we ensure that the network and plans files are still compatible with MATSim.

**Comment by dserdyuk** [comment]
yeah. I've found those sources. So far I see couple configs properties and data files with coordinates. I will enumerate them to give broader picture. Sorry for long post.

```
  # not sure where did we really use it ( usages is commented out) , but I've start using it in trajectory
  beam.routing.gtfs.crs = "epsg:26910"
  
  matsim.modules {
    #this values will be used if following properties is not specyfied
    # for toyGridScenario it's set to EPSG:4326 

    global.coordinateSystem = Atlantis (default)

    network.inputCRS

    facilities.inputCRS

    plans.inputCRS

    # for transitStops coords
    transit.inputScheduleCRS
  }
```  

There are several MATSim and GTFS data files that may contain coordinates:
```
inputNetworkFile.xml ( coordinates in network.inputCRS  or global.coordinateSystem)

inputFacilitiesFile.xml ( coordinates in  facilities.inputCRS or global.coordinateSystem)

inputPlansFile.xml  ( coordinates in plans.inputCRS  or global.coordinateSystem)

 transitschedule.xml   ( coordinates in transit.inputScheduleCRS  or global.coordinateSystem)


GTFS/shapes.txt ( coordinates latlon WGS84 )
GTFS/stops.txt  ( coordinates latlon WGS84 )

```

**Comment by colinsheppard** [comment]
So, e.g., when MATSim loads the network, if there is a difference between network.inputCRS   global.coordinateSystem, does it covert to global.coordinateSystem? If this is the case, then we're in good shape because this is the behavior we want, only it'd be preferable if we could specify the CRS in the data file itself (but we can still do this during boot-up of the config file and set the corresponding MATSim config params).

Also, in the case of BEAM, we're using open street map data as our source for the network (and potentially other data like facilities) which is all in WGS84.

**Comment by dserdyuk** [comment]
1. Yes. it does convert if input.inputCRS is not null. Take a look in ScenarioLoaderImpl.loadNetwork(). 
2. I really doubt setting CRS  from data file ( e.g. network.xml ) is possible. MatsimNetworkReader.transformation is set on upper layer ( in this case ScenarioLoaderImpl). it's a limitation of MATSim XML schema.

Having that first step I would like to implement is validation. to make sure that all mentioned above config properties consistent. 

Q1: @colinsheppard you has requested to autodetect/convert all coordinates to UTM. is it still relevant taking into account my finding ? 
Q2: regarding those data files in WGS84. We need to convert that files to  global.coordinateSystem ?
    I see already inconsistency for SF graph. GTFS data in WGS84 but  global.coordinateSystem is set to either EPGS projection or matsim's Atlantis  system. I guess we need to address that ?

**Comment by dserdyuk** [comment]
I'm going to postpone  this for a while. It seems like we have most of functionality in MATSim .
The only thing is nice to have is an ability to specify  inputCRS in data file directly. 
We need to: 
 1. changes dtd files and put them in scala/resources/dtd
 2. change XML headers in popultion.xml ( and all other data files) to use local dtd ( from our project resource files) rather  than from embedded matsim jar
 
Having that will  just peak at the data files first and set the MATSim config CRS parameters appropriately
