### ISSUE TITLE
add no calibration mode, which does not look for the benchmark file (e.g. during normal runs)

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#702]
Desired Improvements:

1) Configuration spread in multiple files: `beam.conf` and `experiment.yml`

2) Simplify the execution through command line

3) Rename the bechmark.csv file to a more suitable name, including the configuration names

**Comment by colinsheppard** [comment]
for reference:

https://sigopt.com/

**Comment by carloscaldas** [comment]
This issue will be revisited later
