### ISSUE TITLE
compare google cloud engine vs AWS

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#708]

**Comment by zishanbilal** [comment]
this document provides a good comparison.  [AWS vs GCP](https://www.parkmycloud.com/wp-content/uploads/2017/09/AWS-vs-GCP-Cloud-Cost-Comparison-1.pdf)
"When comparing AWS vs. Google Cloud pricing, AWS EC2 on-demand pricing may on the
surface appear to be more competitive than GCP pricing for comparable compute engine’s.
However, when you examine specific workloads and factor in Google’s more enlightened
approach to charging for CPU/Hr time and their use of Sustained Use Discounts, GCP may
actually be less expensive. AWS really needs to get in-line with both Azure and Google,
who charge by the minute and have much smaller minimums. Nobody likes being charged
extra for something they don’t use."

**Comment by zishanbilal** [comment]
[AWS, GCP and Azure Price Matrix](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4e12886d3bdf001353fcc1/125516c66e82c728ace21e0d46c9a3a9029896bb8aceb04ca351f5a43b4f24760405b739799da164fd52690e050a1de853524d41aefd8f2ea3b53a74dc0802bcd76d5f75943d43f9bf8517ad1da862da11d1e9e1d30695aa2f2ff58a89453f1b06118af65532a0904cce5ee406.pdf)
