### ISSUE TITLE
Redirect CompletionNotice messages to BeamAgentScheduler

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#71]
Right now, if an agent doesn't complete a trigger right away (e.g. during ModeChoice) then using the typical goto + replying doesn't work because the sender isn't the BeamAgentScheduler:

`goto(SomeState) replying completed(triggerId = _currentTriggerId.get)`

Instead we've been doing this, which makes the overall codebase sloppier and causes errors when we get mixed up about which situations we're in:

```
beamServices.schedulerRef ! completed(triggerId = _currentTriggerId.get)
goto(SomeState)
```

But if we made any of our participating Actors (including BeamAgents) implement a trait that automatically redirects any CompletionNotice messages to the scheduler, then we can forget about this issue and follow the same convention everywhere, just goto + replying.

**Comment by dserdyuk** [comment]
I've just spend another hour of debugging to find it out. +1 for this
