### ISSUE TITLE
Integrate git LFS and move model-inputs into the repository

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#72]
GanttStart: 2017-08-27
GanttDue: 2017-08-31

Let's solve the versioning headache on our model inputs with this:

https://help.github.com/categories/managing-large-files/

https://git-lfs.github.com/

This may eventually be able to replace our shared inputs folder entirely, but for now let's start by moving beamville into the repository. 

The extensions we should cover include:

.xml
.osm
.pbf
.csv
.zip
.gz
.gtfs
.dat
.mapdb
.p
.txt

**Comment by dserdyuk** [comment]
@colinsheppard Done.

**Comment by colinsheppard** [comment]
@dserdyuk the DTD schemas rarely change and will never be large, so please except them from LFS and commit into the regular repository.

**Comment by colinsheppard** [comment]
Also, the path to beamville is excessively long. Please cut out beam-developers/model-inputs so we have something like this:

test/input/beamville
test/input/dtd

This will require updating the relatively paths in beam.conf to remove "model-inputs".

**Comment by dserdyuk** [comment]
@colinsheppard Done

**Comment by colinsheppard** [comment]
Thanks!

**Comment by colinsheppard** [comment]
I'm getting a lot of errors that look like this when I checkout new branches that others have pushed:

```
Pointer file error: Unable to parse pointer at: "test/input/beam/toyGridScenario/three-charging-strategies_nestedLogit.xml"
Pointer file error: Unable to parse pointer at: "test/input/beam/toyGridScenario/toyNetwork.xml"
Pointer file error: Unable to parse pointer at: "test/input/beam/toyGridScenario/vehicle-types.csv"
```

This appears to be caused by LFS attempting to parse files it manages in the history of the repo but not finding pointers because those files were added before we enabled LFS. It looks like one way to fix this is to rewrite the git history as per this thread:

https://github.com/git-lfs/git-lfs/issues/1828

Can you please do some additional research and confirm that this is the right approach and then *CAREFULLY* (i.e. do a trial run on a dummy repository first) do this re-write over all branches on beam at a time when no developers are active (ideally in the middle of the night in Pacific Time Zone over the weekend).

**Comment by dserdyuk** [comment]
@colinsheppard I guess we can rewrite history of test/input/. I assume you are getting this error i=only with test/input files ? 
My point is that we don't need to rewrite whole repo history only for tracked by lfs files. Make sense ?

**Comment by dserdyuk** [comment]
@colinsheppard 
Alright.. It looks dangerous :). I created repo https://github.com/dserdyuk/test-lfs
added some file including csv. ( which one is tracked by lfs), did couple of  commits ( to have history) in different branch ( fork of master) , pushed. I installed lfs support and added test data. Original CSV file got this error point state. 

I was trying to run git filter-branch like:

```
git filter-branch -f --prune-empty \
  --tree-filter '
	git rm --cached -r -q .
	git lfs track "*.csv"
	git lfs track *.xml
	git lfs track *.osm
	git lfs track *.pbf
	git lfs track *.csv
	git lfs track *.zip
	git lfs track *.gz
	git lfs track *.gtfs
	git lfs track *.dat
	git lfs track *.mapdb
	git lfs track *.p
	git lfs track *.txt
	git add .
  ' --tag-name-filter cat -- --all
```
But receive error:
```Cannot rewrite branches: Your index contains uncommitted changes.```

I was able to rewrite when I commit all my changes ( including that csv file with error pointer )
So far so good.

But the story became interesting when I tried to do merge with master or push 
I'm getting this:

```
>git push

To git@github.com:dserdyuk/test-lfs.git
 ! [rejected]        dserdiuk/test-lfs -> dserdiuk/test-lfs (non-fast-forward)
error: failed to push some refs to 'git@github.com:dserdyuk/test-lfs.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```
Than: 

```
[dserdiuk@localhost test-lfs]$ git pull 
From github.com:dserdyuk/test-lfs
 + ee8f51f...774bf7c dserdiuk/test-lfs -> origin/dserdiuk/test-lfs  (forced update)
 + ee8f51f...774bf7c master     -> origin/master  (forced update)
Pointer file error: Unable to parse pointer at: "src/main/resources/GTFSOperators.csv"
Auto-merging src/main/resources/GTFSOperators.csv
CONFLICT (add/add): Merge conflict in src/main/resources/GTFSOperators.csv
Automatic merge failed; fix conflicts and then commit the result.
```
I merged all conflict by excepting "Theirs" , commit and push.. 

```
[dserdiuk@localhost test-lfs]$ git push
Git LFS: (28 of 28 files) 6.22 MB / 6.22 MB                                                                                        
Counting objects: 52, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (48/48), done.
Writing objects: 100% (52/52), 8.49 KiB | 0 bytes/s, done.
Total 52 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 1 local object.
To git@github.com:dserdyuk/test-lfs.git
   774bf7c..caf8743  dserdiuk/test-lfs -> dserdiuk/test-lfs

```
Note: Git LFS: (28 of 28 files) 6.22 MB / 6.22 MB 
It looks like LFS rewrite files again. The only drawbacks I see is that:
src/main/resources/GTFSOperators.csv is listed as tracked by ``` git lfs ls-files```

Besides that all looks fine, No changes were lost. I was able to create PR and merge it into master

**Comment by colinsheppard** [comment]
Thanks for figuring this out. But let's wait one week to actually follow through on this. We want all devs to push whatever they're working on before doing the rewrite and it's too late to do that given some folks might not be checking their mail or have the time to commit and push...

So we'll target the evening of 9/16 and make sure everyone is onboard / prepared by then.

**Comment by dserdyuk** [comment]
ok. it's better to reduce number of branch though.

**Comment by colinsheppard** [comment]
@dserdyuk  thanks for looking into this. but I think we're better off avoiding history rewrites, this will be a point of discussion in our upcoming meetings.
