### ISSUE TITLE
Clean up logging / Control from beam.conf

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#75]
Enable a way to mute logging statements from MATSim or other classes, e.g. Injector and ControlerUtils.

Make this configurable from beam.conf

Also, make the logging level (INFO vs. DEBUG vs WARN) configurable from beam.conf, it should pass that level on to the logging systems used by BEAM and MATSim.

**Comment by avinashchavanfidel** [comment]
Hi Colin,
 
Logging Information generating from below files::::

---------------------------------------------------------------------------------------------------------------------------------------

These Logging Messages are generating from  Different :JAR FILES >>>>>>>>>>>>>>>>>>>>>>>>
(I Observed these messages from logger console)

":::LOGGING INFO:::"

1. Reflections.java   line no 229                     reflections-0.9.10-sources.jar
2. ScenarioLoaderImpl  line no:108,  130              matsim-master-SNAPSHOT-sources.jar
3. MatsimXmlParser    line no: 92- 306 (4-5 places)   matsim-master-SNAPSHOT-sources.jar

"::::WARNING::::"

6. LinkImpl  line no 149,108,110               matsim-master-SNAPSHOT-sources.jar
7. NodeImpl  lineno 87,88                      axix-1.4.sources.jar


":::LOGGING INFO:::"

8.  ScenarioLoaderImpl   line no 182 - 199            matsim-master-SNAPSHOT-sources.jar
9.  MatsimXmlParser  line 155                         matsim-master-SNAPSHOT-sources.jar
10. PopulationReader  line 110                        matsim-master-SNAPSHOT-sources.jar
11. MatsimXmlParser  line  269                        matsim-master-SNAPSHOT-sources.jar
12. PopulationImpl  line 112                          matsim-master-SNAPSHOT-sources.jar
13. PopulationUtils line 986                          matsim-master-SNAPSHOT-sources.jar
14. ScenarioLoaderImpl line 229                       matsim-master-SNAPSHOT-sources.jar
15. MatsimXmlParser line 155                          matsim-master-SNAPSHOT-sources.jar
16. ObjectAttributesXmlReader line 110                matsim-master-SNAPSHOT-sources.jar
17. ScenarioLoaderImpl  line 242                      matsim-master-SNAPSHOT-sources.jar
18. MatsimXmlParser line 155                          matsim-master-SNAPSHOT-sources.jar
18. ParallelEventsManagerImpl  line 128               matsim-master-SNAPSHOT-sources.jar
19. EventsManagerImpl line 144                        matsim-master-SNAPSHOT-sources.jar
20. EventsManagerImpl 148                             matsim-master-SNAPSHOT-sources.jar
21. StrategyManager  line 59                          matsim-master-SNAPSHOT-sources.jar
22. GenericStrategyManager line 315                   matsim-master-SNAPSHOT-sources.jar
23. ParallelEventsManagerImpl line 128                matsim-master-SNAPSHOT-sources.jar
24. EventsManagerImpl  line 144                       matsim-master-SNAPSHOT-sources.jar
25. Gbl line 57                                       matsim-master-SNAPSHOT-sources.jar
26. AbstractController line 59                        matsim-master-SNAPSHOT-sources.jar
27. Injector line 77                                  matsim-master-SNAPSHOT-sources.jar
28. ControlerListenerManagerImpl   line 117           matsim-master-SNAPSHOT-sources.jar
29. NetworkImpl   line 134,138                        matsim-master-SNAPSHOT-sources.jar
30. TransportNetwork  line 84                         r5-2.1.1.-sources.jar
31. StreetLayer  line 1048                            r5-2.1.1.-sources.jar
32. TransitLayer line 448                             r5-2.1.1.-sources.jar
33. ControlerListenerManagerImpl line 120             matsim-master-SNAPSHOT-sources.jar
34. ControlerUtils line 58                            matsim-master-SNAPSHOT-sources.jar
35. ControlerUtils  line 63,64                        matsim-master-SNAPSHOT-sources.jar
36. VspConfigConsistencyCheckerImpl line 58           matsim-master-SNAPSHOT-sources.jar
37. ControlerUtils line 66                            matsim-master-SNAPSHOT-sources.jar
38. PrepareForSimImpl line 56                         matsim-master-SNAPSHOT-sources.jar
39. NetworkImpl  line 134,138		              matsim-master-SNAPSHOT-sources.jar
40. AbstractController 134                            matsim-master-SNAPSHOT-sources.jar
41. ControlerListenerManagerImpl line 155             matsim-master-SNAPSHOT-sources.jar
42. EventsManagerImpl line 144		              matsim-master-SNAPSHOT-sources.jar
43. StreetRouter line 272		              r5-2.1.1.-sources.jar
44. PointToPointQuery  line 273                       r5-2.1.1.-sources.jar


"::::WARNING::::"

45. PointToPointQuery line 273                        r5-2.1.1.-sources.jar
46. StreetRouter line 421                             r5-2.1.1.-sources.jar
47. RideHailingManager.scala  line 166                Scala CLass From Project




":::LOGGING INFO:::" 

48. McRaptorSuboptimalPathProfileRouter line 141     r5-2.1.1.-sources.jar
49. PointToPointQuery line 144                       r5-2.1.1.-sources.jar
50. Config line 131                                  config-1.3.0.sources.jar


-------------------------------------------------------------------------------------------------------------------------------------------------


These Logging Messages are generating from  Different Scala Classes >>>>>>>>>>>>>>>>>>>>>>>>
(I Observed these messages from logger console)


ConfigModule.scala                        These are Scala Files From Project Directory
RideHailigManager.scala                   These are Scala Files From Project Directory
BeamSim.scala                             These are Scala Files From Project Directory


So here we can make changes in scala files only or do we have source of jars
Please comments

**Comment by colinsheppard** [comment]
Thanks @avinashchavanfidel. 

So the ideal solution would allow us to elect to put any of these messages on mute with a configuration option (i.e. by adding the fully qualified class name to a list in beam.conf). 

I'd like to avoid touching the source code of our dependencies (matsim and r5). All of the logging messages from inside beam are there for a good reason and we don't want to filter and can trivially modify in the future if it's too much.

Do the logging utilities offer the ability to filter out logging by class at runtime?

**Comment by sfwatergit** [comment]
You may need to have a custom log4j conf as well.

**Comment by avinashchavanfidel** [comment]
we dont have log4j.conf configured in the application.

**Comment by colinsheppard** [comment]
@avinashchavanfidel one final request on this issue:

There is a warning message being logged at the beginning of each run:

`09:51:21.628 WARN (Reflections.java:208) could not create Vfs.Dir from url. ignoring the exception and continuing`

Can you please figure out how to mute this message?

**Comment by colinsheppard** [comment]
Ok, something else. 

It looks like you made manual changes to BeamConfig class in order to mute logging:

`Log4jController.muteLog($_L$_str(c.getList("loggerLevels")))
`
This won't work in general, BeamConfig.scala is automatically created through code generation (please see our [documentation](http://beam.readthedocs.io/en/latest/developers.html#configuration)).

So the please to do this kind of modification is in ConfigModule.

**Comment by avinashchavanfidel** [comment]
ohh I understand. Making changes

**Comment by avinashchavanfidel** [comment]
Let me take look .This seems to be repeatative portion. Also I looked at the reflection issue as well. As per solution I have added code in scala RefectionUtils.scala. So java code could not be use in scala so checking work around for that .

**Comment by avinashchavanfidel** [comment]
Hi Colin ,
Could you please check once you get time on duplicate occurrences of logs.

**Comment by avinashchavanfidel** [comment]
Hi Colin ,
I have added code to mute reflection warning as well. Could you please check that too. I have note tested since it is not reproduce on Ubuntu.
