### ISSUE TITLE
fix bug: DumpDataAtEndImpl

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#79]
ERROR DumpDataAtEndImpl:139 writing output events did not work; probably parameters were such that no events were generated in the final iteration

=> cause: file not found.
=> expecting events.xml.gz file, but instead events.xml file present in folder.

**Comment by colinsheppard** [comment]
This is more likely due a change I made recently allowing us to specify "xml" as the format for the events file (which prevents gzip and now flushes in order to facilitate debugging). The DumpData at end must be expecting xml.gz when there's only .xml present.
