### ISSUE TITLE
BugFix: Concurrent write to non-thread-safe variable

### ISSUE THREAD

**Issue by REASY** [LBNL-UCB-STI/beam#814]
Multiple threads can append to this collection https://github.com/LBNL-UCB-STI/beam/blob/master/src/main/scala/beam/agentsim/agents/Population.scala#L51 concurrently - `initHouseholds` uses futures

**Comment by zishanbilal** [comment]
map would execute in the main thread and then it returns a list of futures that would pass to Future.sequence, and all of this be executed in a single thread. So its safe, we may not need concurrent collection.

**Comment by JustinPihony** [comment]
I'd make a caveat to that statement for future review - the BULK would run single threaded. The identify would still run concurrently - but that's pretty minor - so ultimately it still doesn't require a concurrent collection
