### ISSUE TITLE
Route Transit Vehicles through Streets and Save

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#83]
During R5RoutingWorker.createTransitVehicle we should add a step where we actually use the router and do a point to point route between each set of stops. Then we should add the resulting BeamStreetPath to beamServices.transitSegmentToStreetPath = map[BeamTransitSegment,BeamStreetPath]. This map will contain the R5 stop ids for the origin and destination stops and then the street path that is returned.

The routing profileRequest should *not* be a transit route, just a direct CAR-based route.

Finally, this should only be done for street based transit vehicles (modes TRANSIT, BUS)

**Comment by dserdyuk** [comment]
@colinsheppard I've done with BeamPath refactoring. I did link resolution based on stopId  for transit. However I've just realized  those links may be not fully relevant because a route between adjacent stops can consist of several street links. right ?

**Comment by colinsheppard** [comment]
@dserdyuk I like what you've done with the BeamPath so far, but I think we need to iterate a bit more:
- For street-based transit, we definitely need the full path (all link Ids) between stops for each transit vehicle to be contained in the BeamLeg.travelPath. This will require a route calculation. For now, let's do this on-the-fly inside R5RoutingWorker.initTransit, but if the computations are lengthy, we might want to serialize these paths since they won't change from iteration to iteration. 
- StreetPathTrajectoryResolver seems mis-named, this is what we would use for paths that do *not* move through streets, correct? They are just moving in a straight line from one stop to the next. Can we rename to something like StopToStopTrajectoryResolver?

**Comment by colinsheppard** [comment]
Also, re: doing the route calculation, we still want to take advantage of concurrency, so either we should move the whole initTransit process up into the Router (instead of the RouterWorker) or we should spawn some child actors... I think the former is going to be the better solution, but will require a dependency between BeamRouter and R5RoutingWorker (i.e. we will have to access R5RoutingWorker.transportNetwork and other static data). 

I'm ok with this, the idea of keeping the router solution separate and interchangeable is just unrealistic as there have been many design choices throughout agentsim that assume our router is R5. If we want to make things more generic in the future, we'll have to redesign then, but I doubt we'll get to that point any time soon.

**Comment by colinsheppard** [comment]
Note to self, once we've completed the BeamPath refactor, someone should go back and fix the new PathTraversalEvent to output the link IDs again.

**Comment by dserdyuk** [comment]
@colinsheppard Are we done with it ?
