### ISSUE TITLE
remove unused config options

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#848]
There may be several, but for now:

beam.basePackage 

is unused in code but still in our example config files, please remove.

**Comment by colinsheppard** [comment]
beam.agentsim.agents.drivingCost.defaultLitersPerMeter
beam.agentsim.agents.drivingCost.defaultPricePerGallon 

These should come from BeamVehicleType.defaultCarBeamVehicleType instead of appear in the config file. Please remove.

**Comment by colinsheppard** [comment]
Remove:

beam.agentsim.agents.rideHail.vehicleRangeInMeters

unused.

**Comment by colinsheppard** [comment]
Remove:

beam.debug.skipOverBadActors = true
beam.debug.secondsToWaitForSkip = 30

also unused.

**Comment by colinsheppard** [comment]
Please also create separate PR for analogous changes to config files in sfbay branch.

**Comment by bhavyalatha26** [comment]
@colinsheppard 
I do not find any related fields for "drivingCost.defaultLitersPerMeter" and "drivingCost.defaultPricePerGallon" in BeamVehicleType.defaultCarBeamVehicleType . Should I look for any specific fields in this class ?
