### ISSUE TITLE
integrate google OR tools and test small problem

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#857]
Get Google OR Tools to run inside of BEAM. Note, this will require that anyone who runs BEAM has OR tools installed, so this is an extra / non-JVM dependency. If this can be solved automatically using gradle, that would be ideal.

One installed, have everyone household actor use the tool to solve a small problem (linear programming problem) just like this one:

https://github.com/google/or-tools/blob/master/examples/java/LinearProgramming.java

Then test the performance of adding this. Does OR tools scale if tens of thousands of households are all trying to use the solver in parallel? We just want to learn whether this will be viable for general use in BEAM.

**Comment by colinsheppard** [comment]
also check out:

https://index.scala-lang.org/vagmcs/optimus/optimus-solver-oj/2.0.0

**Comment by JustinPihony** [comment]
@colinsheppard Is it known what types of problems might be attempted? Optimus is looking really good, but I realized that Quadratic constraint quadratic programming (QCQP) requires a proprietary solver. Linear programming (LP), Quadratic programming (QP), and Mixed integer programming (MIP) solvers are open source, though. But if a constraint solver is needed then that might be an immediate stopper and I should double back over the other choices (and possibly go back to the more cumbersome OR tools)

**Comment by JustinPihony** [comment]
As this is a bit stale I'm going to leave my testing notes and close it - but if it is ever needed there will be this at least - https://docs.google.com/spreadsheets/d/1GrjWdgtIuaaF9U-7ToMfPxEFeI56PTSFJQGEA4yACFc/edit?usp=sharing
