### ISSUE TITLE
Deploy on AWS

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#87]
Configure BEAM for deployment on Amazon instances. Create script or other tool for initiating multiple parallel runs with uniquely defined beam.conf file.

Do trial runs of Beamville on small instances.

**Comment by colinsheppard** [comment]
As we just discussed, please move toward a user-initiated workflow where a user can specify from their local project directory (or IDEA) the instance type and the branch to build and a script then does the work for procuring and booting the instance which then pulls and builds the requested branch so it is ready for use. The user should be given the IP to use for connecting to the instance.

Also, please set up an s3 data store (file based system for now) for storing model outputs and configure our AMI so that the store is automatically mounted and configured using the BEAM_OUTPUTS environment variable so that when the model runs it writes to s3.

**Comment by zishanbilal** [comment]
All tasks are completed from my side. Also put some doc in project readme.
