### ISSUE TITLE
delay stopping of transit drivers?

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#879]
First task is to determine if this is actually an issue, second task is to fix **if** it's the cause.

Observation: when schedulerParallelismWindow >300, many more people experience errors like  "Person attempted to reserve ride with agent that was not found, message sent to dead letters."

Hypothesis on cause: these drivers are ones that completed their route and have stopped, see this block in TransitDriverAgent:

  when(PassengerScheduleEmpty) {
    case Event(PassengerScheduleEmptyMessage(_), _) =>
      val (_, triggerId) = releaseTickAndTriggerId()
      scheduler ! CompletionNotice(triggerId)
      stop

If they are stopped, then person agents attempting to board the bus "after-the-fact" are getting dead letters and are being stopped as well.

Solution: when a transit drive receives PassengerScheduleEmptyMessage, then he should schedule a PoisonPillTrigger into the future by schedulerParallelismWindow + 1 seconds and at that time take the pill, rather than doing so immediately.

**Comment by michaz** [comment]
Working on this (almost done) -- using as opportunity to stress-test scheduler+transit drivers+person agent a bit, by setting the time window as big as the whole day (everything can happen simultaneously). Almost works, only minor issue.

**Comment by michaz** [comment]
(Your explanation and solution seems correct...)
