### ISSUE TITLE
Document outputs

### ISSUE THREAD

**Issue by sfwatergit** [LBNL-UCB-STI/beam#902]
Develop a documentation .rst file in docs describing the output files

**Comment by sfwatergit** [comment]
Currently there is no documentation page describing simulation outputs. Having one would be generally useful for  the purposes of providing BEAM users and developers with a way of interpreting the simulation as well as how these inputs may be used for debugging. 

@colinsheppard,  it may also make sense to move some of the R scripts for visualization and analysis to either a new repository, beam-utils, or else describe their use in the docs.

**Comment by colinsheppard** [comment]
This issue is already being addressed with #837. Once that is in place we can automatically reformat our output documentation to rst

**Comment by colinsheppard** [comment]
FYI - for completeness, task #936 now covers the last step of the process where we format the output descriptions for .rst
