### ISSUE TITLE
Remove or re-architect all blocking code

### ISSUE THREAD

**Issue by JustinPihony** [LBNL-UCB-STI/beam#907]
`Await.result` or the like should be mapped to wait until the rest of the work completes - otherwise there's no point in it being a Future. The only blocking should be the one block that keeps the app alive while everything else runs non-blocking. It just impedes performance.

**Comment by michaz** [comment]
I just learned that a place where you particularly don't want to blocking-wait on another actor is in an actor's constructor. As in: Wait for my child to be up and running.

It _technically_ works when it works, but if the child dies during initialization, we never see the exception, not even in the log, and the parent waits forever. Reason: The parent only sees and handles the child's exception when _its own event loop_ has started, i.e. _after_ the constructor is finished. 

(Learned something today, just wanted to share.) :-)

**Comment by michaz** [comment]
The remaining places where we ``Await`` something are few, and only in initialization.
