### ISSUE TITLE
Events Logging Improvements

### ISSUE THREAD

**Issue by colinsheppard** [LBNL-UCB-STI/beam#91]
Make events logging more flexible and configuration more understandable.

Currently, we have a method of customizing whether particular types of Events are logged to the events file(s):

```
# Logging Levels:
# >0 enables loggin, <=0 suppresses logging.
# Any event types not explicitly listed take on Default.level
beam.outputs.defaultLoggingLevel = 1
beam.outputs.overrideLoggingLevels = [
  { classname: "beam.playground.metasim.events.ActionEvent", value: 1},
  { classname: "beam.playground.metasim.events.TransitionEvent", value: 1}
]
```

Let's revise this system slightly. Instead of using integers for the level, let's adopt the following Enums (which would be strings in the config file just like the log4j way of configuring:

```
beam.outputs.defaultLoggingLevel = "REGULAR" // one of VERBOSE, REGULAR, SHORT, OFF
```
The idea here is that with a different logging level we would include different amounts of data in the event as written to the events file, e.g. this might be REGULAR:

```
	<event time='21240.0' type='PathTraversal' vehicle_id='1' departure_time='21240' mode='CAR'  />
```

while this might be VERBOSE:

```
	<event time='21240.0' type='PathTraversal' vehicle_id='1' departure_time='21240' mode='CAR' links='142,156,150,172,166,188,182,204,198,192,397'  />
```

As a first step, please just make logging either be on or off depending on whether the level is VERBOSE/REGULAR/SHORT or OFF, respectively.

Note that the logging of events is now organized and controlled under the class BeamEventsLogger, you can see on line 50 how the current integer-based system is being used to turn logging on or off.

Once you have completed this first task, please come up with one or two proposals on how to add the extra control (REGULAR vs VERBOSE vs SHORT) of which fields within the events are actually logged. Ideally, this would happen automatically in a similar way that the method BeamEventsWriterCSV.registerClass is determining which fields to collect. 

The complicating factor is that we do not want to change any MATSim Events, so we either have to extend those (actually we would need to wrap them because they are "final" in MATSim) or create our own registry of what fields within those classes that correspond to VERBOSE and SHORT versus the default REGULAR. I'm inclined to create a single registry so it's easy to see what is what for all event types.

**Comment by avinashchavanfidel** [comment]
@colinsheppard  
I have added code to make the defaultLoggingLevel  informative like VERBOSE, REGULAR, SHORT, OFF.
Now I am checking the way we can control the VERBOSE, REGULAR, SHORT and OFF to make differentiate the log.

**Comment by colinsheppard** [comment]
This is mostly implemented, but work is still needed to complete. In particular, verbose fields are not currently implemented, one solution is to wrap MATSim events in our own class in order to make distinction between regular and verbose fields easier to specify.
