### ISSUE TITLE
add parameter for physsim events samping to facilitate via visualization

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#943]

**Comment by rajnikantsh** [comment]
related PR's

https://github.com/LBNL-UCB-STI/beam/pull/1898 
https://github.com/LBNL-UCB-STI/beam-utilities/pull/5

**Comment by rajnikantsh** [comment]
closed via https://github.com/LBNL-UCB-STI/beam/pull/1898
