### ISSUE TITLE
check on master, if physsim throws "vehicle leaves traffic" events twice

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#951]
-> seen in physsim events file from a gui release
-> check afterwards gui release...

![image](https://user-images.githubusercontent.com/13569531/48956525-4d45d880-ef08-11e8-8708-3329d7df130e.png)

**Comment by rajnikantsh** [comment]
I have found on master that physsim is throwing "vehicle leaves traffic " events twice like.
![Screenshot from 2018-11-30 01-02-55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b59e2a42c7a8600132d4e2c/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227149f27a3dd6b368ef1336515d424ba953444d04bea6d37ef5f22e7a985959e9d7685a77c03947f8b1d319bf01bb728b1dd0b1bb825edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cf54ee34f51ad153662e6647b.png)
