### ISSUE TITLE
Actor-based Parallel JDEQSim: Use Zone Actors instead of Road Actors

### ISSUE THREAD

**Issue by wrashid** [LBNL-UCB-STI/beam#96]
The actor-based parallal JDEQSim version (modelling each agent/road as an actor) did not render performance gains, amongst others due to the too small computation units within each actor. Trying moving towards zone actors (successfully implemented in past with threads/moving time window in JDEQSim). 

High Priority:
1.) Adapt DEQSim model for zonal actors (restructure code for embedding in actors, replace MPI communication with actor messages, adapt inputs and out formats of DEQSim to make them consistent with current MATSim formats)
2.) Add actor-based parallel event handling at output, with calculation of dynamic travel times per link.
3.) do manual network partitioning for testing (2-4 zones)
4.) conduct performance tests

Medium level priority:
Replace manual network partitioning with automatic one, according to 
a) space
b) network average load
c) initially according to a) or b), but with dynamic load balancing during simulation 

Low priority:
- include teleportation and other features to reach full compatibility with MATSim

**Comment by carloscaldas** [comment]
Maybe implement later
